### ISSUE TITLE
Need to Explain Reports and Auditing Capabilities in More Detail and in a Separate Chapter

### ISSUE THREAD

**Issue by rightker** [ortelius/ortelius#1]
Need to Explain Reports and Auditing Capabilities in More Detail and in a Separate Chapter. Also need to have some of the reports rewritten a with a bit more detail and better organization.

**Comment by kanokwanmaneeon** [comment]
@sbtaylor15 ###1 ### #11

**Comment by sbtaylor15** [comment]
Docs have been reworked.
