### ISSUE TITLE
How may I change the port of DeployHub

### ISSUE THREAD

**Issue by Geekays** [ortelius/ortelius#10]
DeployHub by default runs on port 8080. How may I change the port?

**Comment by pgibbs-openmake** [comment]
On Linux, there is a "port" property which can be used to overwrite the default. To change the default:
1) Login as root.
2) Stop the existing web interface (if running):
    **systemctl stop deployhub-webadmin**
4) Edit the service configuration file:
    **vi /usr/lib/systemd/system/deployhub-webadmin.service**
5) Change the java launch line to include the port as a property. Change this line:
    **ExecStart=/usr/bin/java  -jar -server deployhub-webadmin.war**
    to this (if you want to web admin to listen on 8090):
    **ExecStart=/usr/bin/java -Dport=8090 -jar -server deployhub-webadmin.war**
6) Save the file back. Reload the daemon content:
    **systemctl daemon-reload**
7) And restart the web service
     **systemctl start deployhub-webadmin**

**Comment by Geekays** [comment]
I tried this @pgibbs-openmake and it didn't work. Once this is doen, the webpage simply times out. This should work, but seems something is amiss.

Taking out the -Dport parameter or even using it with port 8080 works well,

However I see the service status as running. Here is the status
```
# systemctl status deployhub-webadmin
● deployhub-webadmin.service - Release Engineer Web Admin Interface
   Loaded: loaded (/usr/lib/systemd/system/deployhub-webadmin.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2017-07-31 23:44:18 EDT; 4min 1s ago
 Main PID: 13769 (java)
   CGroup: /system.slice/deployhub-webadmin.service
           └─13769 /usr/bin/java -Dport=8070 -jar -server deployhub-webadmin.war

Jul 31 23:48:04 USTR-ERL-8091.na.uis.unisys.com java[13769]: <parameter name="NtpIncludefile" type="Entry" required="N" default_value="${ntp_includefile}" />
Jul 31 23:48:04 USTR-ERL-8091.na.uis.unisys.com java[13769]: <parameter name="NtpKeys" type="Entry" required="N" default_value="${ntp_keys}" />
Jul 31 23:48:04 USTR-ERL-8091.na.uis.unisys.com java[13769]: <parameter name="NtpTrustedkey" type="Entry" required="N" default_value="${ntp_trustedkey}" />
Jul 31 23:48:04 USTR-ERL-8091.na.uis.unisys.com java[13769]: <parameter name="NtpRequestkey" type="Entry" required="N" default_value="${ntp_requestkey}" />
Jul 31 23:48:04 USTR-ERL-8091.na.uis.unisys.com java[13769]: <parameter name="NtpControlkey" type="Entry" required="N" default_value="${ntp_controlkey}" />
Jul 31 23:48:04 USTR-ERL-8091.na.uis.unisys.com java[13769]: <parameter name="NtpStatistics" type="Entry" required="N" default_value="${ntp_statistics}" />
Jul 31 23:48:04 USTR-ERL-8091.na.uis.unisys.com java[13769]: <parameter name="NtpBroadcast" type="Entry" required="N" default_value="${ntp_broadcast}" />
Jul 31 23:48:04 USTR-ERL-8091.na.uis.unisys.com java[13769]: <parameter name="NtpBroadcastclient" type="Entry" required="N" default_value="${ntp_broadcas...ent}" />
Jul 31 23:48:04 USTR-ERL-8091.na.uis.unisys.com java[13769]: <parameter name="NtpMulticastclient" type="Entry" required="N" default_value="${ntp_multicas...ent}" />
Jul 31 23:48:04 USTR-ERL-8091.na.uis.unisys.com java[13769]: </fragment>
Hint: Some lines were ellipsized, use -l to show in full.

```

**Comment by pgibbs-openmake** [comment]
That should work fine. A few things to ask/check:
1) Could you check netstat (netstat -n | grep 8070) to confirm that port 8070 is open and listening.
2) Are you running locally? If you have X running on your Linux desktop, could you connect firefox to http://localhost:8070/dmadminweb/Home? Is there the same issue?
3) If you're connecting remotely, is there a firewall blocking access to port 8070?
4) It looks like DeployHub is currently downloading the Ansible Galaxy roles. Given that everything works fine on 8080 it seems unlikely that this is causing CPU throttling but it can take a fair bit of time and CPU to do this initial download - especially if the VM does not have many CPU cores or sufficient memory.

**Comment by pgibbs-openmake** [comment]
Another thought. If you don't have a Linux desktop, you can check if the web server is up and listening locally by running:

curl -sL "http://localhost:8070/dmadminweb/API/login?user=admin&pass=admin"

If the web server is listening on 8070 you should see:

{"success":true}

If that works then the timeout may well be down to a firewall issue.
