### ISSUE TITLE
 Enhance directions around the Hipster store

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#100]
Need to enhance directions on how to use the Hipster Store sample.

Documentation updates go in the [ortelius/ortelius-docs repo](https://github.com/ortelius/ortelius-docs).  See this [documentation section](http://docs.ortelius.io/userguide/introduction/0-hipster-store-tutorial/) for the directions on using the sample Hipster Store.

**Comment by TracyRagan** [comment]
Hipster store has been removed as the SaaS is no longer supported. More has been done around the Ortelius CI/CD CLI for getting started.
