### ISSUE TITLE
Enhance integration doc around Jenkins

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#101]
Add more details around using Ortelius with Jenkins.  Integrating the Groovy Doc into the Jenkins section.
The documentation repo [ortelius/ortelius-docs](https://github.com/ortelius/ortelius-docs) and [documentation section](http://docs.ortelius.io/userguide/integrations/jenkins/) is where the updates are needed.

**Comment by TracyRagan** [comment]
The Ortelius CI/CD CLI can be used for this. No custom plugin is now needed.  See https://docs.ortelius.io/guides/userguide/integrations/ci-cd_integrations/
