### ISSUE TITLE
Enhance documentation around integration with CI/CD in general 

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#102]
Add details around using Ortelius with CI/CD tools and principals.  The documentation repo [ortelius/ortelius-docs](https://github.com/ortelius/ortelius-docs) and documentation [section](http://docs.ortelius.io/userguide/integrations/ci-cd_integrations/) is where the updates are needed.

**Comment by shahkv95** [comment]
hey @sbtaylor15 
wanted to check with you if the issue is still open and if solving it will add value to the project.
if so, could you brief me a bit about it, and probably I can work on it thereafter?
Thank you!

**Comment by TracyRagan** [comment]
See https://docs.ortelius.io/guides/userguide/integrations/ci-cd_integrations/
