### ISSUE TITLE
Enhance first step setup

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#104]
Add details for the "first hour" first step setup.  Need to give first time users an easy to follow steps on how to use Ortelius.
The documentation repo [ortelius/ortelius-docs](https://github.com/ortelius/ortelius-docs) and [documentation section](http://docs.ortelius.io/userguide/first-steps/) is where the updates are needed.

**Comment by TracyRagan** [comment]
Done with the Ortelius CLI
