### ISSUE TITLE
Spinnaker Integration

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#105]
Integrate Ortelius into Spinnaker as part of the CI/CD process.

**Comment by sbtaylor15** [comment]
Need to create an Ortelius Spinnaker plugin for capturing configuration, deployment data and relationships for visualization in the Ortelius UI.  [Spinnaker Plugin Guide](https://spinnaker.io/guides/developer/plugin-creators/).

Configuration Data:

| **Field**| **Description** |
| --- | --- |
|**Build Job** | The Continuous Delivery Build Job that is used to build/compile the _Component_.  |
|**Last Build Number** | The number of the last Continuous Delivery (CD) Workflow that created the files referenced within the _Component._ This number will default to the Build ID if one is not set by the CD Workflow.|
| **Build ID** | The internal identifier for the _Build Engine_. |
|**Build URL**| The URL to the _Build Engine_. |
|**Build Date**| The timestamp from when the last build job was run.|
|**Helm Chart** | The Helm Chart used to deploy the _Component_. |
|**Helm Chart Version** | The Helm Chart Version from the Helm Repository. |
|**Helm Chart Namespace** | The sub-division of the Kubernetes cluster where your _Component_ Container should run. |
|**Operator**| The RedHat Operator used to deploy your _Component_ container.|
|**Container Registry**| The Container registry where the Container is stored. |
|**Container Digest**| The SHA number of the Container image. |
|**Container Tag**| The tag that was assigned to the Container image. ||
|**Git Commit**| The Git SHA number. Populated when integrated into Continuous Delivery Pipelines.|
|**Git Repo**| The Git Repository that triggered the build.Populated when integrated into Continuous Delivery Pipelines.|
|**Git Tag**| The last tag for the Git Repository. Populated when integrated into Continuous Delivery Pipelines.|
|**Git URL**| The URL for the Git Repository.Populated when integrated into Continuous Delivery Pipelines.|

Deployment Data:
| **Field**| **Description** |
| --- | --- |
|**Application Version** | Version of the application deployed |
|**Environment**|Name of the environment that the application was deployed to|
|**Endpoints**|Endpoints in the environment that were updated by the deployment|

Relationships:
| **Field**| **Description** |
| --- | --- |
|**Application Version** | Version of the application|
|**Components Versions**|Component versions that belong to the Application Version|

The plugin should grab this information and push it to Ortelius via the Ortelius RestAPIs

**Comment by TracyRagan** [comment]
The Ortelius CI/CD CLI can be used for this. No custom plugin is now needed.  See https://docs.ortelius.io/guides/userguide/integrations/ci-cd_integrations/
