### ISSUE TITLE
Tekton Integration

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#107]
Add integration to Tekton for Ortelius.  Ortelius was added to Puppet's Relay which is based on Tekton.  The Relay integration could be used for Tekton as a starting point.

**Comment by TracyRagan** [comment]
The Ortelius CI/CD CLI can be used for this. No custom plugin is now needed.  See https://docs.ortelius.io/guides/userguide/integrations/ci-cd_integrations/
