### ISSUE TITLE
Integration to Jenkins X

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#108]
Add Ortelius to the Jenkins X CI/CD process.  [ortelius/compupdate](https://github.com/ortelius/compupdate) docker image should be used as a starting point for this integration.

**Comment by TracyRagan** [comment]
The Ortelius CI/CD CLI can be used for this. No custom plugin is now needed.  See https://docs.ortelius.io/guides/userguide/integrations/ci-cd_integrations/
