### ISSUE TITLE
Err msg on initial DeployHub sign in attempt: Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by rightker** [ortelius/ortelius#11]
Email from customer:

Recently install in my computer DeployHub 8

My computer has:
 Windows 7 64bit
 PostgreSQL 9.3
 Java jdk1.8.0_144
 Java jre1.8.0_144
 Posgres psqlodbc_09_03_0400

When I run:

localhost:8080/dmadminweb/Home in any of the web browser I got the folling error message:

HTTP 500 - dmadmin/Home : Unsupported major.minor version 52.0
Apache Tomcat/7.0.54

What do I have to do to correct it?

Thanks in advance,
Ricardo Lorenzi

**Comment by rightker** [comment]
My response to Ricardo via email:

Ricardo,

I have entered bug number #11 into our github bug tracking system, which you can respond to by going to:
https://github.com/OpenMake-Software/DeployHub/issues

Bug #11 is in the list, and you can view and respond to us through this bug entry.

In the meantime, have you reviewed the installation guide for Windows? It can be found at:
https://www.openmakesoftware.com/helpRE75/NetHelp/index.html#!Documents/deployhubinstallationguideforwindows.htm

Thanks,
Kirk Righter
OpenMake Software

**Comment by pgibbs-openmake** [comment]
52.0 is Java 8 so the only thing I can think of is that you have Java 7 or earlier installed somewhere and that is being picked up on the path before Java 8. Could you open a DOS prompt and enter:

java -version

If that reports anything earlier than 1.8 then you may need to fiddle with the path.

**Comment by sbtaylor15** [comment]
Definitely, an older java version being used to run the tomcat server.  Whats JAVA_HOME set to?

**Comment by rightker** [comment]
Sent email to customer, who's having trouble signing into GutHub:

Ricardo,

Go here: https://github.com/OpenMake-Software/DeployHub/issues/11

You should be made to sign in using your id. Then go to the Subscribe button on the right and click it. This should allow you to read and add posts to this issue. There are updates with suggestions for solving your problem.

Thanks,
Kirk

**Comment by lorenzir** [comment]
Definitely I had some Java mixed versions, so I uninstalled all and reinstalled de last Java version (jdk1.8.0_144)
I also unistalled all Tomcar that I had and Install the new one (apache-tomcat-8.5.9)
I don't the error message that I had before but I have a new one

HTTP 404 - /dmadminweb/Home

Can you help me with this?

**Comment by pgibbs-openmake** [comment]
Hi Lorenzir.

Tomcat is installed with DeployHub (the only pre-requisites are Postgres and Java) so the chances are you're looking at your new Tomcat instance and not the DeployHub one. 404 is "page not found" so it looks like you're talking to the wrong Tomcat instance. I would stop the Tomcat version you've installed and restart the Deploy Hub web admin service (probably called Release Engineer Admin).

Cheers,

Phil.

**Comment by lorenzir** [comment]
Thanks, now It's working

**Comment by rightker** [comment]
Customer responded:

Definitely I had some Java mixed versions, so I uninstalled all and reinstalled de last Java version (jdk1.8.0_144)
I also unistalled all Tomcar that I had and Install the new one (apache-tomcat-8.5.9)
I don't the error message that I had before but I have a new one

HTTP 404 - /dmadminweb/Home

Can you help me with this?

**Comment by rightker** [comment]
Phil's response:

Hi Lorenzir.

Tomcat is installed with DeployHub (the only pre-requisites are Postgres and Java) so the chances are you're looking at your new Tomcat instance and not the DeployHub one. 404 is "page not found" so it looks like you're talking to the wrong Tomcat instance. I would stop the Tomcat version you've installed and restart the Deploy Hub web admin service (probably called Release Engineer Admin).

Cheers,

Phil.

**Comment by rightker** [comment]
Customer says it's working now, closing this issue.

**Comment by sbtaylor15** [comment]
@rightker we need to update the install docs to specify only JDK 1.8 64-bit is required.
