### ISSUE TITLE
Install Istio into Azure Cluster

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#110]

**Comment by jgarverick** [comment]
Do we have any preferences around the version to use, add-ons to install, or logistics for where to store things like virtual services, gateways, certificates, etc.?

**Comment by sbtaylor15** [comment]
No, opinion since I am more familiar with Google.  I would throw out that it should be structured so we can move to any cloud provider per out discussion in the Architecture working group.  So the more generic the better in IMHO.

**Comment by jgarverick** [comment]
Ok, I will go forward with:
- Istio v1.7.2
- Extra installations of Kiali, Grafana, Prometheus, Jaeger
- Assumption that gateways and virtual services will live in the namespace of the application they correspond to

**Comment by jgarverick** [comment]
Install complete via `istioctl` and using https://istio.io/latest/docs/ops/integrations/ as a reference to install the addons.  I did not install cert-manager but can if you would like.
How would you like to have the install information captured--in a script or as part of a readme?

**Comment by sbtaylor15** [comment]
Yes, add a chapter to the userguide on how this is setup [ortelius/ortelius-docs](https://github.com/ortelius/ortelius-docs)

**Comment by sbtaylor15** [comment]
Completed by @jgarverick
