### ISSUE TITLE
odbc error message

### ISSUE THREAD

**Issue by lorenzir** [ortelius/ortelius#12]
traying to deploy the application sample I got the following error message:

![odbc error](https://user-images.githubusercontent.com/30667013/29131252-b1c1888c-7d02-11e7-9822-bbf28c2be520.png)

**Comment by pgibbs-openmake** [comment]
Looks like you've not set up the ODBC data source. You should have done this before running the deployhub installer. What datasource did you specify when you ran the installer?

**Comment by lorenzir** [comment]
I uninstall Deplyhub, configure ODBC and reinstall and nothing in the DeployHub installer didn't ask for ODBC data source information what ask me is the information of Postgres, What I trying to do is teh exercise in the DeployHub Guide

**Comment by pgibbs-openmake** [comment]
Apologies, it appears the installer asks for Postgres credentials but not the Data Source Name. Setting up an ODBC connection is a pre-requisite on Windows.

You don't have to uninstall DeployHub again. Perform the following steps:

1) Run "odbcad". This will launch ODBC Data Source Administrator (64-bit). Make sure you're running the 64 bit version (it will say 64-bit on the title bar)
2) Select the "System DSN" tab
3) Click "Add"
4) Select "PostgreSQL ANSI (x64)" as the driver type and click FINISH
5) Set the following values:

Data Source = dm
Database = postgres
Server = (name of server where Postgres is running, probably localhost)
User Name = (postgres user name you entered when installing DeployHub)
SSL Mode = disable
Port = (port on which postgres is listening for connections, you entered this during install)
Password = (postgres password you entered when installing DeployHub)

6) When these values are all in place, click "Test". You should get "Connection Successful"
7) Click Save to create the Data Source
8) Click OK to close the ODBC Data Source Administrator

The deployment engine should now be able to connect to the Postgres database. Please try the demo deployment again.

**Comment by lorenzir** [comment]
Despite I'm having tried many times, finding over internet other people having similar problem with odbc 64 bit I also installed Devart ODBC Driver for PostgresSQL but it's not working.

I really would like to find a solution with this so I come to you if you have a solution for this?

![odbc error 2](https://user-images.githubusercontent.com/30667013/29396151-73833224-82ec-11e7-871f-38a9c6872944.png)

**Comment by pgibbs-openmake** [comment]
That's an architecture mismatch - it's saying you're trying to use a 32 bit ODBC driver with a 64 bit application (or vice versa!).

You're testing an ODBC Data Source there but there doesn't appear to be any properties specified - that will normally fail anyway so the error you're seeing is probably the engine failing to connect to the database. Did you try the demo deployment? Is that the same error?

Can you include a screen shot of the ODBC setup screen and confirm the version of the driver that you have installed? I would use the official PostgreSQL driver. We use 9.03.02 with no issue.

Here's what it looks like on my machine:

![odbc1](https://user-images.githubusercontent.com/14827319/29402710-e32924e4-832d-11e7-84dd-f5089e88081e.png)

![odbc2](https://user-images.githubusercontent.com/14827319/29402738-fb7a192c-832d-11e7-9ee0-709790a2e03a.png)

And the driver:

![odbc3](https://user-images.githubusercontent.com/14827319/29402760-0acd8fd0-832e-11e7-935e-464e4d183324.png)
