### ISSUE TITLE
HacktoberFest: Prepare to participate to get new contributors

### ISSUE THREAD

**Issue by Neetuj** [ortelius/ortelius#128]
- Identify issues suitable for Hacktoberfest (new comers) 
- Tag those issues 
- Create a Landing Page

**Comment by Neetuj** [comment]
@sbtaylor15  I can probably work on this issue with your guidance.

**Comment by Neetuj** [comment]
@TracyRagan @markyjackson-taulia  let me know your thoughts on landing page.

**Comment by sbtaylor15** [comment]
Hacktoberfest is now over
