### ISSUE TITLE
Footer needs to be updated for https://ortelius.io/ page

### ISSUE THREAD

**Issue by ayesha-kr** [ortelius/ortelius#130]
The footer of ortelius.io says **2109 DeployHub** It should be 2020 DeployHub

**Comment by sbtaylor15** [comment]
This is on the Wordpress side:  https://ortelius.io/wp-admin for the login page.

**Comment by divya-mohan0209** [comment]
@sbtaylor15 this is done. Please check. Do you think it'd look better centered? Or is the right alignment preferred?

**Comment by sbtaylor15** [comment]
@divya-mohan0209 I would say centered.  Also, we can probably change it to Ortelius Open Source Project as the copyright holder for the website.

**Comment by divya-mohan0209** [comment]
Sure, so it should be -

© 2020 Ortelius Open Source Project
www.DeployHub.com

Right?

Or would 

© 2020 Ortelius Open Source Project
https://ortelius.io/

be more appropriate?

**Comment by sbtaylor15** [comment]
@divya-mohan0209  Lets go with the second one.

**Comment by divya-mohan0209** [comment]
Done, I've tried centering it as far as the widgets allow. Let me know if this needs further changing, please.

**Comment by sbtaylor15** [comment]
@divya-mohan0209 that works.  Thanks for fixing it.
