### ISSUE TITLE
Component Items should display a message when none are defined

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#14]
It should say something other than giving a blank page.  This typically happens when a custom action is used for the deployment.

**Comment by VinaykumarEndla** [comment]
This is how it looks.

![image](https://user-images.githubusercontent.com/33646669/32788397-191d15c6-c927-11e7-8e8a-2b00329ef1f7.png)

**Comment by pgibbs-openmake** [comment]
Is the Loading icon staying where it is or does it clear?

**Comment by VinaykumarEndla** [comment]
Earlier, I did not read your email sent to me. 
After installing the latest version, I am able to create the Component Item.

Thank you.

**Comment by VinaykumarEndla** [comment]
Now, I see the component Item dialog box popping on the screen but once it is saved [click OK], nothing is visible on Component Items Screen

![image](https://user-images.githubusercontent.com/33646669/32800788-48fb1122-c949-11e7-9b16-7e469ac82a27.png)

![image](https://user-images.githubusercontent.com/33646669/32800801-52b313f4-c949-11e7-8ab5-a04045927a29.png)

**Comment by pgibbs-openmake** [comment]
I've got the latest Windows build fired up here and this is working fine for me.

The component item should be created on the page before the pop-up edit dialog is displayed. Can you drag the dialog to one side to see if the component item is present under the dialog whilst it is being displayed?

Is there any error being displayed on the browser console?

**Comment by VinaykumarEndla** [comment]
Yes, I see that after dragging the dialog box. But still after I clicked on OK, nothing can be seen
![image](https://user-images.githubusercontent.com/33646669/32802521-4b078a4a-c94e-11e7-945f-e951040e0bf2.png)

![image](https://user-images.githubusercontent.com/33646669/32802571-6e887812-c94e-11e7-8504-26a51e455dce.png)

**Comment by VinaykumarEndla** [comment]
And When I click on cancel, I can see the item on the screen.

**Comment by pgibbs-openmake** [comment]
That is really strange. That means the item is getting created but clicking OK is removing it. That literally makes no sense! :-(

If you click on the "Component Items" tab again is the page still blank?

What browser are you using? Can you open up a browser console (Edge/IE - F12 Developer Tools, Firefox - Developer -> Web Console, Chrome - More Tools -> Developer Tools) and see if there's any error reported? Or any logging that may be of interest.

**Comment by pgibbs-openmake** [comment]
So clicking Cancel leaves the component item there? And if you right click on the component item and say "Edit Details" can you then change the content?

**Comment by VinaykumarEndla** [comment]
Yes. But the moment I click on OK again, I see it is lost

**Comment by VinaykumarEndla** [comment]
Yea. When I open in chrome, I could see all of them present. Earlier I was using IE. Looks crazy :) :P 

![image](https://user-images.githubusercontent.com/33646669/32803072-6271aa88-c950-11e7-8177-8b294c1d0b3e.png)

**Comment by pgibbs-openmake** [comment]
Okay. Which version of IE are you using?

**Comment by pgibbs-openmake** [comment]
Does it work okay in Chrome?

**Comment by VinaykumarEndla** [comment]
Yes. In Chrome, it is working fine. 

I am using IE 11.17...

**Comment by pgibbs-openmake** [comment]
It's working for me with Edge... let me try opening it in IE.

**Comment by pgibbs-openmake** [comment]
Yep, that's it. It's not working in IE11.

**Comment by pgibbs-openmake** [comment]
It looks like IE11 is caching when it shouldn't be. When you click OK to save the component item, the browser makes a request to reload the page. It looks like IE11 is NOT making that call and is simply using the old data - all the other browsers (including Edge) resubmit the Ajax query and get the new data.

**Comment by pgibbs-openmake** [comment]
This is a problem specific to GetComponentItemLayout and IE. GetComponentItemLayout is based on HttpServlet and not HttpServletBase. HttpServletBase correctly sets Cache-Control: no-cache whereas GetComponentItemLayout does not. I've added Cache-Control to the GetComponentItemLayout servlet to explicitly switch caching off and that seems to have fixed the issue. I will submit these changes into trunk and do a new build for OSS and Pro.

**Comment by pgibbs-openmake** [comment]
New OSS and Pro Windows builds are done - Linux build is available under "latest". Will leave issue open until it can be retested by user.

**Comment by sbtaylor15** [comment]
Component Items have been rolled into Summary section.
