### ISSUE TITLE
Create personas for Opensource community contributors (wrt to ortelius)

### ISSUE THREAD

**Issue by Neetuj** [ortelius/ortelius#145]
Just like the product has user/buyer personas which helps us understand who they are , what they are looking to do and why same way opensource contributers persona can help us understand the who , what and why behind our contributors and help us support them

**Comment by Neetuj** [comment]
@sbtaylor15  @TracyRagan @jiakalita

**Comment by Neetuj** [comment]
@tlazebnyk  this will be a good one to start with here are a couple of personas I have in mind (we can use the same persona format that we have been using in the past) 
1) Programmer Polly ( professional already in this space and interested in contributing to this project) 
2) Programmer Paula ( early career new to this space/language but already into programming looking to expand her skills and build an online resume for breaking into a new job) 
3) Enthusiast Ellie ( Interested in learning new skills and getting involves in some open source project to find a tribe and get involved) 
4) Project- Prachi (interested in helping with project mgmt side of f/oss project to help it grow) 
5) Product- Peter( interested in helping with the end-user-value-focused development and communication of  this f/oss to help with marketing, evangelization and prioritization and stakeholder communication) 
6) Veteran- volt ( experienced f/oss contributor interested in helping in growing this project by helping others onboard and get ramped up)

**Comment by tlazebnyk** [comment]
Sounds good @Neetuj I will start working on the suggested list. Thank you.

**Comment by tlazebnyk** [comment]
I've started Google doc for contributors personas: https://docs.google.com/document/d/1lLsYp_CiNoKo96ErrcTGeKNXUhJmktMDhofc0vlDInI/edit?usp=sharing

**Comment by Neetuj** [comment]
@sbtaylor15  fyi

**Comment by tlazebnyk** [comment]
@Neetuj @sbtaylor15 @TracyRagan 
I have finished 2nd document with personas for Ortelius community contributors.
Can be found by the link and in the comment below:
https://docs.google.com/document/d/1lLsYp_CiNoKo96ErrcTGeKNXUhJmktMDhofc0vlDInI/edit?usp=sharing

1.
### **Programmer Polly (professional already in this space and is interested in contributing to this project)**
**Who**
Role:

- Takes part in technical design discussions, share knowledge and experience insights via communication channels 
- Implements solutions for microservices management according to agreed technical design
- Provides mentorship and conduct code reviews 
- Participates in overall Ortelius community sessions, shares ideas on common questions (e.g. contribute to release notes, vote for logo theme etc)

Skills:

- Strong understanding of microservices architectures (leveraging APIs, containers and automation)
- Expert level programming skills
- Hands-on experience implementing microse/rvices, application troubleshooting and debugging skills
- Experience leading the engineering team and acting as mentor for colleagues 

**What**
Goals:

- based on engineering experience help Ortelius community to build world class solutions for managing microservices in most efficient way
- Meet new professionals and build community

RTM: Conferences, trainings, code reviews, blogs, book/online resources, technology review sessions with Senior Engineering Leadership

Motivations:
- Innovate in the area of interest and bring to life ideas to improve day-to-day real life challenges
- Share knowledge and vice versa - get new perspectives from Ortelius community members, get details on learning points from others  
- Try new ‘hat’, e.g. security engineer, delivery/project manager, product manager etc.

**Why**:
Frustrations/Blockers/Pain Points:

- Determining and tracking differences across microservices versions
- Relatively complex deployment


2.
### **Programmer Paula (early career, new to this space/language, but already into programming looking to expand her skills and build an online resume for breaking into a new job)**
**Who**
Role:

- Takes part in technical design discussions, gets guidance from senior community members on tasks to be accomplished
- Ready to work on new level of engineering tasks, with new frameworks which were never used in past experience
- Participates in overall Ortelius community sessions, shares ideas on common questions (e.g. contribute to release notes, vote for logo theme etc)

Skills:

- Basic programming skills
- Hands-on experience working with microservices and cloud solutions
- Database and scripting languages knowledge

**What**
Goals:

- Extend knowledge about microservices in general and specifically about Ortelius mission with simplifying microservices management and versions control
- Reflect new knowledge and experience in resume for breaking into new job 
- Meet new professionals and build community

RTM: Conferences, trainings, code reviews, blogs, book/online resources, technology review sessions with Senior community members

Motivations:

- Be a contributor to the cutting edge open source project in the area of engineering interest
- Be a part of Ortelius community and build new connections
- Learn from Senior community members with ability to work on new level of engineering tasks; try working as a full stack engineer and deal with both back-end and front-end tasks

**Why:**
Frustrations/Blockers/Pain Points:

- No experience working with microservices
- No experience in supporting deployment

3. 
### **Enthusiast Ellie (Interested in learning new skills and getting involved in some open source project to find a tribe and get involved)**
**Who**
Role:

- Participates in overall Ortelius community sessions, shares ideas on common questions (e.g. contribute to release notes, vote for logo theme etc)
- Contributes with creating technical documentation, product marketing assets, branding

Skills:

- Technical background (degree in Business Analysis)
- Hands on experience working in tech world as Product Manager on B2B products
- Hands-on experience working with database, scripting languages and API

**What**
Goals:

- Extend knowledge about microservices in general and specifically about Ortelius mission with simplifying microservices management and versions control
- Contribute to Ortelius as product manager based on current experience
- Contribute to Ortelius as data scientist to get new experience
- Build community and work with enthusiasts from other fields (data scientists, software engineers, dev ops engineers etc) 
- Reflect experience in resume for breaking into new job/reinforce promotion

 
RTM: Conferences, trainings/meetups, blogs, book/online resources

Motivations:

- Be a contributor to the cutting edge open source project in the technology world
- Be a part of Ortelius community and build new connections
- Try a new role as data scientist and learn from professionals in this field by solving real-life tasks

**Why**:
Frustrations/Blockers/Pain Points:

- No experience contributing to open source project
- No experience working on data science related tasks on the project

 4.
### **Project manager - Prachi (interested in helping with project mgmt side of f/oss project to help it grow)**
**Who**
Role:

- Participates in overall Ortelius community sessions, shares ideas on common questions (e.g. contribute to release notes, vote for logo theme etc)
- Contributes with managing project scope and delivery plans
- Facilitates community sessions, meeting notes and keeps eye on follow up items 

Skills:

- Excellent communication skills and time management
- Hands on experience working in tech world as Project Manager and leading projects for enterprise clients
- Technical background (degree in Project Management)
- Programming languages, database, scripting languages basic understanding

**What**
Goals:

- Contribute to Ortelius as project manager based on current experience
- Help with project growth through excellent management of project scope and associated delivery
- Help with release updates and overall project awareness through external communication channels (dev ops communities, social networks)
- Build community and work with enthusiasts from other fields (data scientists, software engineers, dev ops engineers etc) 

RTM: Conferences, trainings/meetups, blogs, book/online resources

Motivations:

- Be a contributor to the cutting edge open source project in the technology world
- Be a part of Ortelius community and build new connections
- Lead Ortelius open source project through all the stages of Software Development and support growth
- Get recognition for successful project rollout

**Why**:
Frustrations/Blockers/Pain Points:

- Need to contribute not only as ‘traditional’ Project Manager and be at some point responsible for different delivery/communications aspects as partnerships for product growth, awareness and adoption


5.
### **Product manager - Peter (interested in helping with the end-user-value-focused development and communication of this f/oss to help with marketing, evangelization and prioritization and stakeholder communication)**
**Who**
Role:

- Participates in overall Ortelius community sessions, shares ideas on common questions (e.g. contribute to release notes, vote for logo theme etc)
- Contributes with roadmap management and features prioritizations, user journeys and personas, tracks product metrics

Skills:

- Excellent communication and presentation skills
- Hands on experience working in tech world as Product Manager 
- Technical background (degree in Computer Science)
- Programming languages, database, scripting languages basic understanding

**What**
Goals:

- Contribute to Ortelius as product manager based on current experience
- Help with product strategy and growth by defining Ortelius end users pain points and outlining functionalities to tackle them
- Analyze product metrics to measure product success 
- Build community and work with enthusiasts from other fields (data scientists, software engineers, dev ops engineers etc) 

RTM: Conferences, trainings/meetups, blogs, book/online resources

Motivations:

- Be a contributor to the cutting edge open source project in the technology world
- Be a part of Ortelius community and build new connections
- Work with other Product Managers in Ortelius community on product scope, go-to-market strategy and continuous delivery success 
- Run competitive analysis and keep identifying new opportunities in the industry to be handled by Ortelius

**Why**:
Frustrations/Blockers/Pain Points:

- Very basic understanding of microservices and no hands-on experience working on CI/CD software development


6.
### **Veteran - Volt (experienced f/oss contributor interested in helping in growing this project by helping others onboard and get ramped up)**
**Who**
Role:

- Participates in overall Ortelius community sessions, shares ideas on common questions (e.g. contribute to release notes, vote for logo theme etc)
- Leads product growth, promotion and go-to-market activities leveraging personal connections with industry leaders 
- Provide mentorship to Ortelius community

Skills:

- Excellent communication and presentation skills
- 20+ years of experience working in tech world in different roiles
- Great domain understanding and good knowledge of competitive landscape
- Hands-on experience leading diverse teams with different level of knowledge 

**What**
Goals:

- Contribute to Ortelius as industry leader and serve as great supporter of the product
- Help with product strategy and growth by making introductions with industry professionals for Ortelius community members
- Promote Ortelius and represent it on conferences and meetups 
- Continue building community and supporting/teaching new enthusiasts contributing to Ortelius project

RTM: Community board meetings, conferences, trainings/meetups, blogs, book/online resources

Motivations:

- Support new initiative in the industry leveraging own connections within professional network
- Be part of community of pioneers improving microservices management
- Share senior leadership knowledge and experience with Ortelius community members

**Why**:
Frustrations/Blockers/Pain Points:
With industry innovations evolving, it might be a challenge to find a good new product to support and invest your time and effort 

7.
### **Data** Scientist - Anna (experienced professional interested in growing this project by providing data insights)
**Who**
**Role:**

- Participates in overall Ortelius community sessions, shares ideas on common questions (e.g. contribute to release notes, vote for logo theme etc)
- Performs ad-hoc data analysis within Ortelius version control engine to continuously improve core features like microservices dependency map, domain structure cataloging, microservices sharing
- Identifies new potential product feature opportunities based on data insights
- Presents data insights / overall analysis results in a clear manner
**Skills**:

- Excellent communication and presentation skills
- Excellent understanding of machine learning techniques and algorithms
- Experience with common data science toolkits and data visualisation tools
- Good scripting and programming skills (SQL, R)

**What**
**Goals:**

- Drive innovation by providing data insights for Ortelius core features (like microservices dependency map, domain structure cataloging, microservices sharing) to make sure Ortelius delivers transparency into the continuous delivery process 
- Outline potential anomalies and suggest enhancement to existing features accordingly
- Continue building community and supporting/teaching new enthusiasts contributing to Ortelius project

**RTM**: Conferences, trainings/meetups, blogs, book/online resources
**Motivations**:

- Work within new domain and apply knowledge and experience in a new area
- Belong to the team of pioneers and work on a brand new features within the domain

**Why:**
**Frustrations**:

- Basic understanding of microservices and no hands-on experience working on CI/CD software tools development

8.
### **Support Engineer - Dave (professional in supporting systems within FinTech domain with no experience in CI/CD tools development)**
**Who**
**Role**:

- Participates in overall Ortelius community sessions, shares ideas on common questions (e.g. contribute to release notes, vote for logo theme etc)
- Takes ownership of reported customer issues, troubleshoots and identifies solutions to resolve reported issues
- Follows standard procedures for proper escalation of unresolved issues to the Orteius community
- Provides prompt and accurate feedback to Ortelius customers

**Skills**:

- Excellent problem-solving and communication skills
- Hands-on experience with Windows/Linux/Mac OS environments
- Familiarity with remote desktop applications and help desk software (e.g, Zendesk)

**What**
**Goals**:

- Support Ortelius customers as product adoption spins off
- Promote Ortelius and build momentum with customers by educating how to use Ortelius features

**RTM**: Conferences, trainings/meetups, blogs, book/online resources

**Motivations**:

- Support Ortelius adoption and drive improvements through customers feedback
- Belong to the team of pioneers and support Ortelius community in reimagining microservices management

 
**Why**:
**Frustrations**:
- No hands-on experience working on CI/CD software tools development project

**Comment by Neetuj** [comment]
This looks great! @tlazebnyk ! great work!
@jiakalita  you can find the personas here.

**Comment by Neetuj** [comment]
@jiakalita @tlazebnyk  @sbtaylor15  @TracyRagan  to be able to use these personas in a form either we can use the one-line description of the personas we have at the beginning of the issue .. or we can  simplify and create some visuals around them ? these persona details  are good for our "deep dive" and understanding into how to serve these personas but they are not "readily/easily consumable in current format" by a new contributor who is just exploring. Let me know what you think/prefer

**Comment by Neetuj** [comment]
Option 1:- use the online description of each persona in the volunteer entry form
Option 2:- create visuals based on the current personas we have for usability. 
If we go with option 2 :- 
here is a Visuals for Personas template (we will have to customize it based on our needs)  tracy@deployhub.com  Steve Taylor  we will need your inputs on which fields from above are more important to add to the visual ..once we have the fields finalized I can modify the template and then we can populate the visuals if you think visual will add value. 
https://docs.google.com/presentation/d/1fBQeSdXuUHsMUMoft-11QA_8l4MgorYLhkCbjIblCJg/edit?usp=sharing

**Comment by jiakalita** [comment]
Thanks @Neetuj and @tlazebnyk for the user personas. For the purpose of the Google form, I suggest we stick to the brief, one-line descriptions to keep it simple and later can share these detailed templates once they are ready.

**Comment by tlazebnyk** [comment]
@Neetuj Thank you too! From my experience visuals would be great to represent personas. 
I am also thinking about adding one more - Support Engineer/Customer Support internal contributor to support Ortelius once adoption by developers is spin off.

**Comment by tlazebnyk** [comment]
@Neetuj @TracyRagan @jiakalita Edited initial comment with personas details above, added:

- Data Scientist Anna 
- Support Engineer Dave

**Comment by Neetuj** [comment]
sounds good @tlazebnyk. Do you have a started template to work for the visuals? if not I pulled one here feel free to edit that one https://docs.google.com/presentation/d/1fBQeSdXuUHsMUMoft-11QA_8l4MgorYLhkCbjIblCJg/edit#slide=id.p1 
we might want to change some fields -

- skip demographics (not sure if they help at this point .. we can add them later) 
- collapse professional background into Work Experience section and Skills section  (the already defined WHO section can be copied here ) 
- remove defining traits, person preference and favourite brand sections and may be communication style section too 
- highlight.concentrate on psychographics .. values,  goals, challenges  ( the already defined WHAT , WHY section can be copied here in a concise manner) 

These are just suggestions .. feel free to suggest/make any other changes that you feel make sense. 


@jiakalita n the form you can add the one-line descriptions and then link to a google doc if they are interested in knowing more about the personas.

**Comment by tlazebnyk** [comment]
@Neetuj thank you! I will pick it up and continue with visuals for both internal and external personas. ETA - next Tuesday 12/8.

**Comment by tlazebnyk** [comment]
@Neetuj @jiakalita Added corresponding visuals to all personas - https://docs.google.com/presentation/d/1Cbe2CJ0Y_0Z3MM2ZS49NUxuW5N6JpmkhWfqH0opU7iA/edit?usp=sharing

@Neetuj I was not able to remove sections we do not need in the template from Compose.ly so worked on another template.

**Comment by Neetuj** [comment]
This looks great! Thanks @tlazebnyk
