### ISSUE TITLE
Jenkins Plugin does not update DeployHub when Component Selection alone is selected and filled in

### ISSUE THREAD

**Issue by cawale** [ortelius/ortelius#17]
When I try and just set the component selection tab only, Deployhub does not create a component version or updated attributes.

Thanks.

**Comment by sbtaylor15** [comment]
So it will only create a new component version when you do an application deployment, correct?

**Comment by cawale** [comment]
yes as far as I can test that is correct.

**Comment by sbtaylor15** [comment]
Jenkins plugin is being deprecated.  The DeployHub Jenkins Groovy Library is the replacement.
