### ISSUE TITLE
Slack integration

### ISSUE THREAD

**Issue by chicks-net** [ortelius/ortelius#170]
Write a bot to integrate with Slack.  Start with notifications of updates.

**Comment by sbtaylor15** [comment]
Here is the [C code](https://github.com/ortelius/ortelius/blob/master/dmengine/notifiers/slack/slack.cpp) that does a Slack Notify.  This is called as a Notifier to an Application.  I think we should be duplicated into the [ortelius/compupdate](https://github.com/ortelius/compupdate) python code since that is the main integration point into CI.

Need to flush out where the notifications should happen in the CI pipeline.

**Comment by bradmccoydev** [comment]
I have experience in writing Slack Bots, so am happy to help here where required

**Comment by sbtaylor15** [comment]
@bradmccoydev there was discussion of going the route of ChatOps and have Slack kick of a deployment of an application to an environment via Ortelius.  Any experience with ChatOps?

**Comment by bradmccoydev** [comment]
@sbtaylor15 yes I have lots of experience in chatops I will get an async meeting going for this to demonstrate a project in the past I have done in this space

**Comment by bradmccoydev** [comment]
@sbtaylor15 please find our overview of how we have used chatops here: https://www.youtube.com/watch?v=GHQelgBGOzc

Notes:
In this part we show previous experience with ChatOps.  The idea is to show what is possible with Slack and how we can contribute this knowledge into the project.

Agenda:
- Show our bot "shelly" working in production
- Show high level Architecture of the framework
- Show how we use metadata and config

About Shelly:
When I was the Engineering Manager at Temenos, one of my jobs was to automate unplanned work coming in so we could focus on planned work.  We, therefore, developed Shelly.  This considerably dropped the support tickets coming in and we were able to focus on innovation.

**Comment by bradmccoydev** [comment]
Part 2 of the meeting: https://www.youtube.com/watch?v=nQ9UO_DPXi4 here we discuss a high level overview of the teams capability, not related to slack but shows how our framework can talk to both.

**Comment by bradmccoydev** [comment]
@wonboyn we will need to investigate Discord integration also API docs can be found here: https://discord.com/developers/docs/intro

**Comment by sbtaylor15** [comment]
No longer needed
