### ISSUE TITLE
cdf: code of conduct/cla signoff 

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#177]
New contributors need to sign the CLA before getting access to everything.  Need an automated process to verify CLA is done before access is provided. 

Can a person come to the meetings before signing a CLA?  And can the access the Google Docs before a CLA?

LF uses EasyCLA to keep track of the signatures.  Should integrate with EasyCLA.

**Comment by sbtaylor15** [comment]
Awesome, thank you! EasyCLA should now be installed under the CDF account. From here, you can sign as an individual or you can add DeployHub as a corporate signatory. I'll include a link with instructions for that below.

Add a company: https://docs.linuxfoundation.org/lfx/easycla/cla-manager/add-a-company-to-a-project

Approve contributors: https://docs.linuxfoundation.org/lfx/easycla/cla-manager/approve-contributors

If you run into any bumps, our CLA admin can be reached via ticket here. 

Thank you!
Gale

**Comment by sbtaylor15** [comment]
Submitted google form to request that Ortelius be added to EasyCLA.

**Comment by TracyRagan** [comment]
https://ortelius.io/guidelines/
