### ISSUE TITLE
developer guide 

### ISSUE THREAD

**Issue by Neetuj** [ortelius/ortelius#178]
Developer guide to help incoming contributors

**Comment by markjacksonfishing** [comment]
I will have this skeleton out later this morning

**Comment by markjacksonfishing** [comment]
The base dev guide is here: https://docs.google.com/document/d/1SwcDbd71XEakzx4jisqKK5L8MVV0bbBHS71y1AM3_jw/edit?usp=sharing

cc: @Neetuj

**Comment by TracyRagan** [comment]
https://docs.ortelius.io/guides/contributorguide/
