### ISSUE TITLE
doc: Change logo on userguide

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#180]

**Comment by sbtaylor15** [comment]
Need to use alien svg

**Comment by sanjeepan23** [comment]
I would like to contribute to this project, but I'm new here. can someone guide me?

**Comment by sbtaylor15** [comment]
@goat023 we need to take the [ortelius logo](https://github.com/TracyRagan/artwork/blob/master/ortelius/ortelius-logo.svg) and add it to the userguide.  It goes in the [ortelius/ortelius-docs repo logo,svg](https://github.com/ortelius/ortelius-docs/blob/master/themes/docsy/assets/icons/logo.svg).

You will need to fork the [ortelius/ortelius-docs](https://github.com/ortelius/ortelius-docs) repo, make the change and then do a pull request to merge your changes back in.  Ping us on Discord if you need help on this.

**Comment by sanjeepan23** [comment]
thank you so much. I will do the change.

**Comment by scanalesespinoza** [comment]
> userguide

Hi @sbtaylor15 where exactly the logo need to be?
![image](https://user-images.githubusercontent.com/11546953/103106856-cfd58080-4617-11eb-998c-bca6bec1c431.png)
A screenshot with the draft will be great

**Comment by sbtaylor15** [comment]
@scanalesespinoza looks like the change has been made.  It's the logo in the top left of the page.  This issue was not closed when the PR was merged.  Right now closing issues is a manual process.
