### ISSUE TITLE
On-prem install admin cred setup

### ISSUE THREAD

**Issue by dnilasor** [ortelius/ortelius#184]
I'm playing with Ortelius for the first time and did a local install. 

![image](https://user-images.githubusercontent.com/36797588/102827929-5bd97500-4398-11eb-8335-2a21a75a56f1.png)

[This part of the doc](http://docs.ortelius.io/guides/userguide/installation-and-support/0-on-premise-installation-for-pro/#step-5---access-ortelius-from-your-browser) mentions that I should be prompted to set up admin credentials, but I only see a login prompt which, naturally, hates my phony credentials. Is there another way to get the initial admin account set up via config, or a direct path in the GUI?

Thanks for this project!!!

**Comment by sbtaylor15** [comment]
For a local install creds should be user: admin pw: admin

**Comment by sbtaylor15** [comment]
Did the admin/admin work to get you in?

**Comment by dnilasor** [comment]
Yes! It did. Thanks for your help. When I get the chance I will make a PR with a small doc update to clarify this.

**Comment by sbtaylor15** [comment]
[Access Ortelius from your browser](http://docs.ortelius.io/guides/userguide/installation-and-support/0-on-premise-installation-for-pro/#step-5---access-ortelius-from-your-browser) section needs to be changed.  The prompt is no longer used instead, first userid is `admin` with password `admin`.

**Comment by sbtaylor15** [comment]
@Javailabe - here is another doc update.  Make sure your fork is in sync with the ortelius/ortelius-docs#master branch before making the change.  Let us know if you need help getting your forked repo in sync and ready to go.

**Comment by Javailabe** [comment]
@sbtaylor15 - I am still not familiar with GitHub interface and functionalities and need some help here.

![image](https://user-images.githubusercontent.com/68078922/104961535-cc46d680-59d6-11eb-9559-48b0b0feef80.png)

 I think, I forked  ortelius/ortelius but now cannot find the issue. I would appreciate any hint how I can get there.

Thank you!

**Comment by sbtaylor15** [comment]
@Javailabe the issue remains tied to the original repo and doesn't move over to your forked repo.  We need to get your forked repo in-sync with the original one.  Contact me on our Discord server ( handle sbtaylor15) so we can schedule some time to do a quick web meeting.  Here is the [link to the channel](https://discord.gg/ZtXU74x).  Thanks, Steve
