### ISSUE TITLE
404 Error on Installation and Support Guide link

### ISSUE THREAD

**Issue by scanalesespinoza** [ortelius/ortelius#185]
Hello Team!

At ortelius github home, preview of "README" has a link for "_Installation and Support Guide_" who points to "http://docs.ortelius.io/userguide/installation-and-support/" giving a **404** page error.

**Comment by sbtaylor15** [comment]
We added a new chapter that changed the directory structure.  The correct url is:
http://docs.ortelius.io/guides/userguide/installation-and-support/

**Comment by sbtaylor15** [comment]
PR merged
