### ISSUE TITLE
Change the Logo of the Ortelius Project

### ISSUE THREAD

**Issue by gkdevops** [ortelius/ortelius#188]
Change the Logo of the Ortelius Project from alien to another logo which clearly represents the project

**Comment by scanalesespinoza** [comment]
Hello I start reading about Ortelius, I don't know if this represents crearly the project but is an idea, and with feedback I can do another trys:

So the proposal is this abstract logo, who represents in the old ages the sunset/horizont, the limit of what we see and what exist, then is sorrounding with grounds, seas and skies (the world) what we complete/achieve after years of collaboration.

It make sense? comments are wellcome.

![ortelius-logo01](https://user-images.githubusercontent.com/11546953/103256643-c0826a00-496c-11eb-8e03-21a70cff3d11.png)
![ortelius-logo01-text](https://user-images.githubusercontent.com/11546953/103256645-c1b39700-496c-11eb-9b3b-c2b1333dd709.png)
![ortelius-logo-name](https://user-images.githubusercontent.com/11546953/103257200-03454180-496f-11eb-856f-47ca53f450f6.png)

PD: Yes I know, it looks like a pokeball  xD

**Comment by markjacksonfishing** [comment]
I really like this

**Comment by scanalesespinoza** [comment]
what did you think @gkdevops ? For the aceptance criteria we need a minimun of options and then voting?

**Comment by TracyRagan** [comment]
Its a great design.  What was discussed during our logo talks was to have a logo that could be used as a mascot. Something that user groups could make their own.  Think of the Jenkins "Butler" or GitHub Octacat.  A mascot type logo is more 'approachable' and can be used in many ways. For example our Alien logo can be used to create achievement badges with the alien wearing different hats.  We could create an Alien logo for each country that the community represents.  Also we just completed this effort and launched with the alien image.  I think for now we leave it and address this in the future if the community thinks a different logo approach is needed.  The design is great and would work really well for a corporate image, but I would encourage us to think of a logo mascot and how the broader community could 'play' with the alien and make it their own.   We also did some testing with the alien image with a Jenkins logo and it did really well.

**Comment by scanalesespinoza** [comment]
Totally understood, a mascot a lot friendly too. When that time arrieve just let me know to help with the design.

**Comment by Neetuj** [comment]
So are we slating this issue for now @TracyRagan ?

**Comment by sbtaylor15** [comment]
@Neetuj - yes.   We are going to table this for now and go with what we have already got for the logo.
