### ISSUE TITLE
RTC type repository

### ISSUE THREAD

**Issue by alanromo** [ortelius/ortelius#19]
I got the OSS DeployHub version.
In the documentation I can see that there are RTC repository types. But on what I have installed I only can see: File system, ftpprep, harvest, http, meister, perforce, and svn.  
Can you help telling me what is the best option for RTC repositories ?

**Comment by sbtaylor15** [comment]
RTC exposes items as a file system repository.    You create the file
system repo first by checking out the RTC artifacts initially.  If you need
to do an update of that file system from RTC prior to a deployment then you
would to a pre action at the application level that run the appropriate RTC
command for the update.

Thanks, Steve

Steve Taylor
