### ISSUE TITLE
Blog 1 "Tips and Tricks"

### ISSUE THREAD

**Issue by TracyRagan** [ortelius/ortelius#193]
We need to add content for the " Ortelius Tips and Tricks" blog category.  Please create your blog in Google docs under the /blog directory. https://ortelius.io/category/ortelius-tips-and-tricks/

A good place to start would be a blog about signing up and testing out the Hipster store.

**Comment by Neetuj** [comment]
This blog helps us reach our "increase the sign ups by Q2021". Having tips and tricks for informational blogs on setting up Ortelius will be really helpful in meeting this goal.
