### ISSUE TITLE
Blog 2 - "Tips and Tricks"

### ISSUE THREAD

**Issue by TracyRagan** [ortelius/ortelius#194]
We need to add content for the " Ortelius Tips and Tricks" blog category.  Please create your blog in Google docs under the /blog directory. https://ortelius.io/category/ortelius-tips-and-tricks/

A suggestion would be 'how to publish your microservice to a domain.'

**Comment by Neetuj** [comment]
This blog helps us reach our "increase the sign ups by Q2021". Having tips and tricks for informational blogs on setting up Ortelius will be really helpful in meeting this goal.
