### ISSUE TITLE
Business Model / Value Proposition Canvas 

### ISSUE THREAD

**Issue by tlazebnyk** [ortelius/ortelius#195]
Build product vision and analyze key indicators to fulfill go-to-market strategy

**Comment by Neetuj** [comment]
I can help with that.

**Comment by tlazebnyk** [comment]
[Ortelius_BusinessModelCanvas.pdf](https://github.com/ortelius/ortelius/files/5837979/Ortelius_BusinessModelCanvas.pdf)


@Neetuj please see attached, appreciate your thoughts. and please feel free to update as needed

**Comment by Neetuj** [comment]
Looks good to me. we can certainly modify based on inputs ..
