### ISSUE TITLE
Training videos to activate first-time users and improve their onboarding experience to help them adopt ortelius : Training Video 1

### ISSUE THREAD

**Issue by Neetuj** [ortelius/ortelius#197]
First impressions are important. We want firs-time users of ortelius to have a good experience. One way to do is to provide training videos to help them see how to get started. 

few ideas :- 
Define the goal this video will accomplish. 
Define what users should do first to adopt Ortelius. 
Add a step by step guide to download and get started with Ortelius.
Show how to follow/act on that guide in the video. 
Think about what are the key actions that will make them stick around.

**Comment by TracyRagan** [comment]
https://ortelius.io/blog/2021/03/31/getting-started-with-saas-version-of-ortelius/
