### ISSUE TITLE
Training videos to help first-time users get started and adopt ortelius : Training Video 2

### ISSUE THREAD

**Issue by Neetuj** [ortelius/ortelius#198]
First impressions are important. We want first-time users of ortelius to have a good experience. One way to do is to provide training videos to help them see how to get started.

few ideas :-

video 1:- 
Define the goal this video will accomplish.
Define what users should do first to adopt Ortelius.
Add a step by step guide to download and get started with Ortelius.
Show how to follow/act on that guide in the video.
Think about what are the key actions that will make them stick around.

Video 2:- 
Troubleshooting setup ? 
Hacks  and tricks to get started quickly ?

**Comment by nishantminerva** [comment]
@Neetuj Mam I would like to make the video  but I need some help cause I am new and don't know much about cloud computing.

**Comment by Arvind644** [comment]
@TracyRagan I think we can we add it as lightning talk for our may visionaries summit.

**Comment by TracyRagan** [comment]
That is a great Idea - don't think we have one yet tho.
