### ISSUE TITLE
Database Management Support

### ISSUE THREAD

**Issue by alanromo** [ortelius/ortelius#20]
I see on the documentation that DeployHub can help with database management support. i.e.  database changes from development to QA or PROD. 
Do you have an example on how this can be used or configured ?

**Comment by pgibbs-openmake** [comment]
Here's a quick 10 minute video which shows this in action:

https://www.youtube.com/watch?v=vQoZcMcqCeM

There's a few steps you need to do to get this configured:
1) Create a database component that pulls and delivers the SQL alter scripts
2) Create a post-action to that component that executes the SQL against the database
3) Assign the component type to the appropriate end-point(s) within your target environment(s) - this ensures that the SQL code is delivered to the database server(s) within your environment.
4) Set the component item(s) within the database component to be ROLLUP or ROLLBACK. Rollup component items have their "interim" versions delivered automatically when deploying a later version. Rollback component items have their "interim" versions delivered automatically when deploying an earlier version.

The last step works when you starting versioning applications. If you've got application version 5 running in TEST and you deploy application version 8, then DeployHub will deploy the interim versions of any component item which is marked as Rollup. So it will deploy version 6, 7 and 8 of any SQL alter scripts, thus rolling the DB schema forward from version 5 to version 8.

This is really useful when you're running CI/CD but not every new build is moving forward into the later test and production environments (or you're moving from an Agile model in Dev/Test to a more traditional waterfall approach in Prod).

**Comment by alanromo** [comment]
I have problems with step 1
I created a database component "dbch". I'm guessing that the file ddl1.qry should be copied to the end point. Once in the end point I would be able to execute it.  The problem is that it never gets there.

Here the log


WARNING: component 118 'dbch' is not associated with any servers
--
INFO: Deploying roll-forward items of Component dbch
INFO: Checked out ddl1.qry;0
INFO: Item "Roll Forward": Checked out 1 file(s) from repository "Local PC2"
exit status is 0
INFO: Time taken 236.229004 seconds

**Comment by pgibbs-openmake** [comment]
It looks like you've not done step 3:

_3) Assign the component type to the appropriate end-point(s) within your target environment(s) - this ensures that the SQL code is delivered to the database server(s) within your environment._

What that error message is saying is that no end-points (servers) within the target environment has an associated component type that is the same as component 'dbch'. So DeployHub can't place that component anywhere in the environment (it has nowhere to deploy it to).

Just ensure that the "dbch" component type is associated with at least one end-point within the target environment and all should be well.

**Comment by alanromo** [comment]
It has been associated along with other 2 components (shells and jars) to the same endpoint. The other 2 components move OK to the endpoint, but this one (dbch) does not.

Here the full log


INFO: Starting deployment #181
--
INFO: Deploying Application "CPE" into Environment "DevelopmentCPE"
INFO: Deploying Component shells
INFO: Checked out CallSetupCPE1.ksh;
INFO: Checked out CallSetupCPE2.ksh;
INFO: Checked out CallSetupCPE3.ksh;
INFO: Item "CPEsetupScripts": Checked out 3 file(s) from repository "Local PC"
INFO: Deploying Component shells to Server serverZ61
INFO: Deployed File CallSetupCPE1.ksh -> serverZ61:/home/alanromo/CallSetupCPE1.ksh
INFO: Deployed File CallSetupCPE2.ksh -> serverZ61:/home/alanromo/CallSetupCPE2.ksh
INFO: Deployed File CallSetupCPE3.ksh -> serverZ61:/home/alanromo/CallSetupCPE3.ksh
INFO: Deploying Component jars
INFO: Checked out concurrent.jar;0
INFO: Checked out cpeauto.jar;0
INFO: Checked out ipfaarchive.jar;0
INFO: Checked out pioarchive.jar;0
INFO: Checked out rcmanager.jar;0
INFO: Item "Item 1": Checked out 5 file(s) from repository "Local PC3"
INFO: Deploying Component jars to Server serverZ61
INFO: Deployed File concurrent.jar -> serverZ61:/home/alanromo/concurrent.jar
INFO: Deployed File cpeauto.jar -> serverZ61:/home/alanromo/cpeauto.jar
INFO: Deployed File ipfaarchive.jar -> serverZ61:/home/alanromo/ipfaarchive.jar
INFO: Deployed File pioarchive.jar -> serverZ61:/home/alanromo/pioarchive.jar
INFO: Deployed File rcmanager.jar -> serverZ61:/home/alanromo/rcmanager.jar
WARNING: component 118 'dbch' is not associated with any servers
INFO: Deploying roll-forward items of Component dbch
INFO: Checked out ddl1.qry;0
INFO: Item "Roll Forward": Checked out 1 file(s) from repository "Local PC2"
exit status is 0
INFO: Time taken 63.451000 seconds

I have this endpoint serverZ61, I see in the "deployed components" tab the 3 components.
Actually I have added it and removed it from that tab  many times expecting see it working. 
Every time I do a deploy of the application I can see that the other 2 components show in the details column the deployment number where they participated but for this component only shows the date/time when the component was added to the endpoint by the admin.
Any idea what else can be wrong?

**Comment by sbtaylor15** [comment]
Can you send a screen shot of the General Tab for this component dbch?

And a screen shot of the General Tab for the end point that should be
receiving this component?

Thanks, Steve

Steve Taylor


CITA and Co-Founder / OpenMake Software / tel: + 1.505.424.6439 x114 / mob:
+1.505.920.6106


*Book at time slot with us
<https://www.openmakesoftware.com/devops-experts>*

Follow us on: Blog <https://www.openmakesoftware.com/insights/> / Twitter
<http://www.twitter.com/openmake>/ Facebook
<https://www.facebook.com/pages/OpenMake-Software/478045172208305> /
LinkedIn <https://www.linkedin.com/in/steve-taylor-b539205> / YouTube
<https://www.youtube.com/channel/UCSgF51hv2Qy88POFsA59uJQ>/ Google+
<https://plus.google.com/u/0/+Openmakesoftware>

*Winners of the Jolt Award in Change and Configuration Management*

**Comment by alanromo** [comment]
While trying to get the screen shots you asked me I think I found the problem.
The problem is with the "endpoint component type"
This was set to: "application file".... so the first two components were able to make it
I just tried changing it to "DB2 DDL & SQL" and this way the first 2 components failed and the dbch made it!.
So, I think I need to define 2 different endpoints, one for the application files and another for the DB2 stuffs although they are being moved to the same place.

**Comment by sbtaylor15** [comment]
The component types enable the routing of a component to the right end
points.  So in dev, the database and the application may live on the same
server.  Then in QA, the database and application are on separate servers.
Prod may have a database cluster and 20 apps servers.

FYI, multi-select the component types on the end point to enable moving
different components types to the same server.

Steve Taylor


CITA and Co-Founder / OpenMake Software / tel: + 1.505.424.6439 x114 / mob:
+1.505.920.6106


*Book at time slot with us
<https://www.openmakesoftware.com/devops-experts>*

Follow us on: Blog <https://www.openmakesoftware.com/insights/> / Twitter
<http://www.twitter.com/openmake>/ Facebook
<https://www.facebook.com/pages/OpenMake-Software/478045172208305> /
LinkedIn <https://www.linkedin.com/in/steve-taylor-b539205> / YouTube
<https://www.youtube.com/channel/UCSgF51hv2Qy88POFsA59uJQ>/ Google+
<https://plus.google.com/u/0/+Openmakesoftware>

*Winners of the Jolt Award in Change and Configuration Management*
