### ISSUE TITLE
Submit this project for GSOC Google Summer of Code 

### ISSUE THREAD

**Issue by Neetuj** [ortelius/ortelius#200]
GSoc is a great way to get contributors, visibility etc. 

Timeline https://developers.google.com/open-source/gsoc/timeline

- [x] Identify project ideas for GSOC

- [x] Submit those ideas to CDF/SOC

- [ ] Evangelize our GSOC entry to seek applicants 
- [ ] create a meeting plan for GSOC to welcome, set context+expectations and timelines with 3-4 meetings

**Comment by Neetuj** [comment]
@sbtaylor15  @TracyRagan  we still have time ..applications open on  Jan 29th and deadline is feb 19th 2021. 

Please review the entry criteria :- https://summerofcode.withgoogle.com/get-started/
Organization Eligibility
Mentor organizations must run an active open source or free software project.
Have produced and released software under an OSI approved license.
Must not be based in a country currently embargoed by the United States.
COMPLETE ORGANIZATION TERMS

and terms https://summerofcode.withgoogle.com/terms/org

**Comment by sbtaylor15** [comment]
@neettuj - everything looks good except we need to change our license from Affero to Apache 2.  Let's put that change to the members at our next General working group meeting.

**Comment by sbtaylor15** [comment]
@Neetuj the CDF is going to apply for us.  We will need to come up with a project idea, and who wants to be a mentor.

Here is what Jenkins is doing:  https://www.jenkins.io/blog/2020/12/16/call-for-mentors/

**Comment by sbtaylor15** [comment]
Need to update the [CDF Summer of Code](https://github.com/cdfoundation/soc) page with Ortelius

**Comment by Neetuj** [comment]
@sbtaylor15 Cool in that case I can submit a PR  here https://github.com/cdfoundation/soc/blob/master/project-ideas-2021 once we decide on project ideas. 

would Helm, Cloudbuild, Dockerbuilds issues clubbed together make good project ideas? or will they be too small for such a  duration?

**Comment by sbtaylor15** [comment]
@Neetuj we need to look at bigger ideas such as Application Sets.  Going to open up the discussion at the Architecture working group this Thursday.

**Comment by Neetuj** [comment]
@sbtaylor15   @TracyRagan  let me know when the ideas for gsoc are identified. I will like to work with you to get them ready so that students can easily selects and work on them. 

This should give us some idea of how it works :- https://gist.github.com/anjali-dhanuka/76563d3c9b953b2e754a5a03ddc300e7

based on this we should 
1) clearly identify some projects ( each project should have an overview , goal , skills/tech involved for that project , other relevant information) 
2) we should ask students to submit a proposal of how they intend on work on that project ( sort of like a project plan) 
3) our team will be reviewing the proposals and selecting those proposals (we should identify the people who will review those proposals)
4) once  the students are accepted with their project proposal we should :-
  
    - do a welcome meeting, introduce them to ortelius and match them with their mentors 
    - do 1-2 mid sem demo/check-in meeting
    - request for weekly status report 
    - do an end of semester demo and thank you meeting.

**Comment by Neetuj** [comment]
@sbtaylor15  @TracyRagan  I see 3 issues (apart from this one) tagged for gsoc. 

- are we expecting more ? 
- If not should I go ahead and submit this PR https://github.com/cdfoundation/soc/compare/master...Neetuj:patch-2 ?
- once we have finalized I can write a blog about our plans to enter GSOC, what to expect etc

**Comment by sbtaylor15** [comment]
@Neetuj just three issues at this time.  I updated the soc readme with our project ideas and created the PR https://github.com/cdfoundation/soc/pull/15.  It sounds like there will be a limited number of students based on what they were telling us on the CDF TOC meeting last week.

**Comment by Neetuj** [comment]
@sbtaylor15  cool! 

1. I will go ahead and write a blog about our plans to enter GSOC in that case and get it reviewed by you and @TracyRagan 
2. I will also create some Issues (more like to-dos) regarding the welcome meeting, mid point checkup and final demo for us to collaborate on how to communicate expectations and welcome the new mentees.

**Comment by sbtaylor15** [comment]
CDF added my userid to the CDF team gsoc-admin-and-mentors

**Comment by sbtaylor15** [comment]
Our PR cdfoundation/soc#19 has been merged.  CDF is submitting application to Google on 2/19.

**Comment by sbtaylor15** [comment]
Closing issue since CDF is handling the rest of the process for us.
