### ISSUE TITLE
documentation:  add variable names for attributes being updated by CI/CD tools

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#209]
Key name column needs to be added to the tables on [Defining Components](https://docs.ortelius.io/guides/userguide/publishing-components/2-define-components/#container-specific-data-definition).  The key name is used to map the value to the specific entry field on the Component Definition.

- BuildId
- BuildUrl
- Chart
- chartversion
- operator
- DockerBuildDate
- DockerSha
- DockerRepo
- GitCommit
- GitRepo
- GitTag
- GitUrl
- buildnumber
- buildjob
- ComponentType
- ChangeRequestDS
- Category
- AlwaysDeploy
- DeploySequentially
- BaseDirectory
- PreAction
- PostAction
- CustomAction
- Summary

**Comment by sbtaylor15** [comment]
Change needs to be made in [ortelius/ortelius-docs](https://github.com/ortelius/ortelius-docs) repo

**Comment by sbtaylor15** [comment]
Application Definition key names:

- FailureTemplate
- SuccessTemplate
- CustomAction
- PostAction
- PreAction
- ChangeRequestDS

Note: The templates are unique so no domain name is required.

**Comment by Javailabe** [comment]
Hello @sbtaylor15,

Are these keys should be added to subsections: [Container Specific Data Definition](https://docs.ortelius.io/guides/userguide/publishing-components/2-define-components/#container-specific-data-definition) and [Application Specific Data Definition](https://docs.ortelius.io/guides/userguide/publishing-components/2-define-components/#application-specific-data-definition) ?

For some lines I am not able to identify _keys_ (e.g. on below screenshot, lines with nulls: 96, 98, 99...). Is there any other matching key - different than _name related_?

![image](https://user-images.githubusercontent.com/68078922/107878486-52b9df80-6ed3-11eb-9eb3-df665f93f9ac.png)

Thank you.

**Comment by sbtaylor15** [comment]
@Javailabe the keys that need to be updated are just for the Application Specific Data Section.

| Field | Description |
| ---- | -------------|
| FailureTemplate | The name of the Failure Notification Template to use on a deployment failure. |
| SuccessTemplate | The name of the Success Notification Template to use on a deployment succes. |
| CustomAction | The name of the custom action to execute for the deployment.  This will override the Post Action and Pre Actions. |
| PostAction | The name of the Pre Action to execute at the very beginning of the deployment. |
| PostAction | The name of the Pre Action to execute at the very end of the deployment. |

Note: ChangeRequestDS should not be in the list. Added to the issue by accident.
