### ISSUE TITLE
Integration with ArgoCD resource hook : create an Ortelius resource hook for capturing deployment data and relationships for visualization in the Ortelius UI

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#215]
**Project Overview**
@sbtaylor15  It will be useful to back up a little but and provide them some overall big picture view

**Project Goals**
Need to create an Ortelius resource hook for capturing deployment data and relationships for visualization in the Ortelius UI.  [ArgoCD Resource Hook Example](https://argoproj.github.io/argo-cd/user-guide/resource_hooks/).

**Related Documentation**
Deployment Data:
| **Field**| **Description** |
| --- | --- |
|**Application Version** | Version of the application deployed |
|**Environment**|Name of the environment that the application was deployed to|
|**Endpoints**|Endpoints in the environment that were updated by the deployment|

Relationships:
| **Field**| **Description** |
| --- | --- |
|**Application Version** | Version of the application|
|**Components Versions**|Component versions that belong to the Application Version|

The plugin should grab this information and push it to Ortelius via the Ortelius RestAPIs

**Comment by sbtaylor15** [comment]
Argo does not have a CI/CD process so no way to hook into the build process for docker image creation.  This means that the Git info that triggered the docker build does not exist.  For example, Jenkins would be the orchestration tool that has a pipeline step to do the docker build, docker push and git push to the application git repo to update the manifests with the new docker digest/tag info.  Argo will monitor that application Git Repo for resource changes in which trigger syncing the k8s manifests with the clusters. 

The ArgoCD resource hook (PostSync) logic could be used to capture updates to the clusters from other GitOps controllers such as fluxd.

**Comment by Neetuj** [comment]
@sbtaylor15  are there any skills /tech that students will need to know/learn ? for this issue? It will help students see if they are interested in picking up this issue.

**Comment by sbtaylor15** [comment]
Here are the ArgoCD notification methods - https://argoproj.github.io/argo-cd/operator-manual/notifications/

The [deployhub CLI ](https://github.com/ortelius/compupdate) is able to create components versions and application versions using the json output from `kubectl get deployment` and `kubectl get rollout`.

Hooking together GitOps Notifications Webhook with the deployhub python library we can automatically create new component and application versions without the need to update any orchestration tools, ie Jenkins.

To make this happen we need:

1. Microservice webhook to accept the notification payload from the GitOps Notifications Sender.
2. After the webhook has been triggered, the deployhub CLI should be executed against that cluster
3. The deployhub CLI needs to change to run `kubectl get deployment` and `kubectl get rollout` against the cluster. The CLI can already process the kubectl json output.
4. The deployhub CLI needs to determine the docker digest for each container and see if there is a component that already exists and use that component otherwise create one.

**Comment by sbtaylor15** [comment]
Closing.  This should be replaced with Kept-lite integration
