### ISSUE TITLE
Typos correction in Pull Request Cheat Sheet

### ISSUE THREAD

**Issue by Javailabe** [ortelius/ortelius#227]
Typos in [Pull Rest Cheat Sheet](https://docs.ortelius.io/guides/contributorguide/pull-request-cheat-sheet/) need to be corrected

![typos](https://user-images.githubusercontent.com/68078922/109568211-e18b4680-7ae6-11eb-8397-f016e8933d7f.png)

**Comment by Neetuj** [comment]
@marcvelasco I am unable to assign this issue to you .. feel free to assign it to yourself ..
