### ISSUE TITLE
Broken link to contributors page

### ISSUE THREAD

**Issue by scanalesespinoza** [ortelius/ortelius#232]
There is a broken link in https://docs.ortelius.io/guides/contributorguide/community-membership/ page
Link need to be updated
![image](https://user-images.githubusercontent.com/11546953/110247874-2979f580-7f4d-11eb-86d3-5adcd8e9f7df.png)
![image](https://user-images.githubusercontent.com/11546953/110247894-3d255c00-7f4d-11eb-8a57-e3860c5520d0.png)

The right link should be https://ortelius.io/contributor/

**Comment by Neetuj** [comment]
Please move it to "done" project state when the PR is closed.

**Comment by scanalesespinoza** [comment]
ready in production (master Branch)
