### ISSUE TITLE
website: Preview on PR

### ISSUE THREAD

**Issue by obowersa** [ortelius/ortelius#238]
# Description
For content creators ( and PR reviewers ) it would be useful to have a preview of the website changes available as a comment on the PR.

# Potential Workflow
The rough workflow would be:
-> PR Opened
-> Base build of website carried out
-> Static content published to a dynamicly generated preview URL
-> Preview URL made visible to the Pull Request
-> URL can be reviewed
-> Loop repeats until PR is approved
-> On merge, build/deploy under current process continuous.

# Reasons
While  it is possible to run hugo locally, it can be a barrier to entry to both reviewing and creation of content. This would enable a smoother workflow from mardkwon to published content.

**Comment by sbtaylor15** [comment]
Istio just needs to be tweaked to do this.  Right now both the dev.ortelius.io and ortelius.io hosts are backed by the same container.  Just need to split the hosts to separate containers.  Also change the cloud build to handle actions on a merge

**Comment by sbtaylor15** [comment]
preview can be run locally.  closing
