### ISSUE TITLE
Using variables in Command Line Interpreter Path

### ISSUE THREAD

**Issue by cawale** [ortelius/ortelius#24]
Hi,

Looking to use the getcredential function in a command line interpreter path but it does not seem to work. I am trying to do something like 

${PATH_TO_WSADMIN}/wsadmin.${EXT} -lang jython -user "${getcredential("${was_credential_name}"}.username}" -password "${getcredential("${was_credential_name}"}.password}" -p ${soap_client_props_dir}/mysoap.client.props -f
The direct variables work fine PATH_TO_WSADMIN, etc.. but not the get credentials.  

I have tried attributes to do this as well, on the endpoint, but doing a getcredential there has issues as well since it seems to have problems navigating the quotes. 

I have tried the following syntax in both locations:

getcredential("Cred_Name"}.username
getcredential('Cred_Name'}.username
getcredential(''Cred_Name''}.username
getcredential""Cred_Name""}.username
getcredential(/'Cred_Name/'}.username
getcredential(/"Cred_Name/"}.username
${getcredential([With all the combinations above]}.username}

Any thoughts?

**Comment by pgibbs-openmake** [comment]
I think you MAY have hit a limitation of the DMScript parsing engine.

Try something like this:

set CRED1 = getcredential("Cred_Name");
set username = ${CRED1.username};

P.

**Comment by sbtaylor15** [comment]
I do the following:

![image](https://user-images.githubusercontent.com/14826572/37219096-a62fdd92-237f-11e8-9fb5-7d1a82f330a3.png)

![image](https://user-images.githubusercontent.com/14826572/37219120-bd43c89a-237f-11e8-8617-c7f41734b8f9.png)

![image](https://user-images.githubusercontent.com/14826572/37219156-d04004a4-237f-11e8-8891-f73ca0f63c16.png)

The the Function/Procedure that needs the userid password just uses the Global Variables (line 13-14).

**Comment by sbtaylor15** [comment]
Here is the code for the setting the credential as a global variable:

```
if ($SalesforceCredential != "") {
	// Use Supplied Credential Name
	echo "INFO: Using Supplied Credential $SalesforceCredential";
	set cred = getcredential($SalesforceCredential);
} else {
	// Use Server Credential
	set cred = ${server.credential};
	if (${cred.id}) {
		echo "INFO: Using Credential for Server ${server.name}";
	}
}
if (${cred.id}) {
	set -g SFUserName = ${cred.username};
	set -g SFPassword = ${cred.password};
} else {
	echo "INFO: No Salesforce credentials available";
}
```

**Comment by cawale** [comment]
Hi,

Yes I am doing that but I just wanted to simplify it all since it is used by each and every function. Why do I need to do it more than once for all scripts. Putting it in the command line interpreter line in the procedure definition seemed like a nice way to do it.

Thanks.

Chris

**Comment by cawale** [comment]
Just to be clear this is a remote procedure call not a local one.
