### ISSUE TITLE
documentation: PR Cheatsheet needs to use git rebase

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#242]
git rebase works better than git merge for keeping the commit history in sync.  

I will add the exact changes after testing them out.

**Comment by sbtaylor15** [comment]
Step 9 should be: `git rebase upstream/master`
Step 10 should be: `git rebase master`
Step 11 should be: `git push -f`  (forced push)

Add step 12 - After the PR has been merged you need to do steps 9 - 11 in order to bring your repo in sync with upstream since it has new commits.

**Comment by Javailabe** [comment]
I am thinking about rebuilding of PR Cheat Sheet to understand whole workflow easier. I will make proposal and let you know.

**Comment by Javailabe** [comment]
Maybe two things:

1. Sort alphabetically _Terms_ section.

2. I would divide _Example scenario_ section for 2 sections:

- 1st would include some basic settings like: forking repo, making local copy, creating branches, creating remotes and finally changes in the files and then push and pull requests,

- 2nd could be shorter section when you already have configured everything and working in _fetching-updating-pulling_ regime.

Is that make sense?

**Comment by sbtaylor15** [comment]
@Javailabe Yes, those are good suggestions.  Please make the changes.
