### ISSUE TITLE
Archiving of unused components

### ISSUE THREAD

**Issue by Javailabe** [ortelius/ortelius#244]
Possibility of archiving not used components might be useful for sake of space saving and better arrangement.

I am opening the discussion:

- Any pros and cons?
- How this functionality could work?

**Comment by sbtaylor15** [comment]
Need to change the filter dropdown to add "show archived".

**Comment by sbtaylor15** [comment]
Changed UI for Application Versions and Component Versions to act like GitHub Commits. Showing the latest version with button to see older versions.
