### ISSUE TITLE
Attributes not getting expanded.

### ISSUE THREAD

**Issue by cawale** [ortelius/ortelius#25]
Hi,

I am trying to get an attribute set as ${server.name} echo'd in my deployment script.

So I have my attribute set to:
![image](https://user-images.githubusercontent.com/34170905/37285329-1bdcc062-25d5-11e8-8452-21686dfbd321.png)

I then have my script set to 

action WS_Clean_Cluster
{
  echo "${test_attr}";
  return;
}

My output is this

INFO: Starting deployment #67216
--
INFO: Deploying Application "CFM_1_0;1" into Environment "Old_UAT"
INFO: Deploying Component CFM
INFO: Checked out /job/CFM_AD_4.1_Int/4/ca.ontario.gov.health.GAPP.CFM$CFMWebEAR/artifact/ca.ontario.gov.health.GAPP.CFM/CFMWebEAR/4.1/CFMWebEAR-4.1.ear;4
INFO: Item "CFM WebSphere": Checked out 1 file(s) from repository "Jenkins"
${server.name}
INFO: Pre Action for Component CFM exits code 0
INFO: Deploying Component CFM to Server Dev WebSphere 8_5 Admin
INFO: Deployed File CFMWebEAR-4.1.ear -> Dev WebSphere 8_5 Admin:/export/home/walec/deploy/CFMWebEAR-4.1.ear
INFO: Time taken 2.810000 seconds

Is this expected behavior? It does not seem to evaluate the attribute.

**Comment by sbtaylor15** [comment]
Where is that attribute defined, environment, component, application?

**Comment by cawale** [comment]
I have tried attributes defined in both the environment and server objects and I get the same result.

**Comment by sbtaylor15** [comment]
Can you try the modified script?  I believe the test_attr is not being set due to the way the stack is being processed.  Let me know the results.

action WS_Clean_Cluster
{
echo "ATTR=${test_attr}";
echo "SRVN=${server.name}";
return;
}

**Comment by cawale** [comment]
This is the log output.


INFO: Starting deployment #67247
--
INFO: Deploying Application "CFM_1_0;1" into Environment "Old_UAT"
INFO: Deploying Component CFM
INFO: Checked out /job/CFM_AD_4.1_Int/4/ca.ontario.gov.health.GAPP.CFM$CFMWebEAR/artifact/ca.ontario.gov.health.GAPP.CFM/CFMWebEAR/4.1/CFMWebEAR-4.1.ear;4
INFO: Item "CFM WebSphere": Checked out 1 file(s) from repository "Jenkins"
ATTR=${server.name}
SRVN=Dev WebSphere 8_5 Admin
INFO: Pre Action for Component CFM exits code 0
INFO: Deploying Component CFM to Server Dev WebSphere 8_5 Admin
INFO: Deployed File CFMWebEAR-4.1.ear -> Dev WebSphere 8_5 Admin:/export/home/walec/deploy/CFMWebEAR-4.1.ear
INFO: Time taken 2.810000 seconds

**Comment by sbtaylor15** [comment]
Looks like the values for the Attrs for the Server are being set outside of the stack scope, ie. before ${server.name} is resolved.  You will need to use ${server.name} in your script instead of ${test_attr}.

**Comment by cawale** [comment]
ok. So to work around this I created a generic pre-action script that set the variables as global. It seems to work. 

Thanks.

**Comment by sbtaylor15** [comment]
You can also do the following from the script:

set -g TEST_ATTR=${server.name}

which will set it at the global level.

**Comment by cawale** [comment]
The reason I am trying to do this is to support WebSphere remote procedure calls and the operation values that are required to pass through to the wsadmin function. If I don't put them in a common place then everyone using any of these remote procedure calls need to know that:

1) They need to do something special for these specific sets of functions/procedures. Different from many of the other functions/procedures we have.
2) What the names need to be and what the values need to be.

Without the attribute evaluation happening, which would be optimum since I could set the end point attributes with the right names/values (DMscript'ish), I can at least mitigate the second item above by creating the common action so that it can be easily added to the pre-action of a component that needs to use these procedures. I get the reuse and reduced debugging problems going forward.

Personal preference I guess.

Thanks.
