### ISSUE TITLE
Recommended local dev environment

### ISSUE THREAD

**Issue by obowersa** [ortelius/ortelius#250]
We briefly discussed options around local dev stacks, just gathering a new notes/thoughts here to expand on.

None of these will be required, but, recommendations/guidelines might help folk get up to speed.

There are a few use cases for local environments, which might have different solutions.

- Local dev environment for ortelius service development
This is not necessarily requiring a full environment, and could comprise of simple containers or if contracts between services are well defined, isolated service being worked on with contracts to validate against.

- Local dev environment for validating deployment/integration
Depending on the recommended deployment approach, this will likely need some form of k8s + deployment tooling. Potentially something along the lines of kind/k3s + skaffold. Cross platform is a must.

- Local dev environment for integrations with external tooling
This will depend on the external tooling ( saas vs self hosted with monolithic app vs self hosted with helm deployment ). 

Local dev is likely to be a mix of the previous two considerations depending on the tool being integrated with.

---
A couple of other notes, it's worth including information around how to debug against the recommended local dev stack. This can be a stumbling block for folk particularly when it comes to debugging services against k8s. Could make for some good blog posts off the back of it as well.

**Comment by sbtaylor15** [comment]
Need to make sure we handle a dev env for a least Windows and OS/X.

**Comment by sbtaylor15** [comment]
See #50

**Comment by sbtaylor15** [comment]
Closing. See Ortelius-In-A-Box by Sacha
