### ISSUE TITLE
microservice:  flask bubble sort 1

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#253]
Need python flask program to return json string of the following array sorted using the bubble sort algorithm.

[ 10, 1, 200, -19, 21, 321, 0, 200 ]

Use [ortelius/ortelius-ms-dep-pkg-cud](https://github.com/ortelius/ortelius-ms-dep-pkg-cud) repo for your code.

**Comment by ayesha-kr** [comment]
@munnyraht this going to be the issue that you will be working on

**Comment by sbtaylor15** [comment]
Resolved in PR ortelius/ortelius-ms-dep-pkg-cud#1
