### ISSUE TITLE
microservice: flask bubble sort 2

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#254]
Need python flask program to return json string of the following array sorted using the bubble sort algorithm.

[ 10, 1, 200, -19, 21, 321, 0, 200 ]

Use [ortelius/ortelius-ms-dep-pkg-r]( https://github.com/ortelius/ortelius-ms-dep-pkg-r) repo for your code.

**Comment by ayesha-kr** [comment]
@BBimie this is going to be the issue that you will be working on.

**Comment by sbtaylor15** [comment]
Resolved by PR ortelius/ortelius-ms-dep-pkg-r#1
