### ISSUE TITLE
database: add table for Component Version to Dependency Packages

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#255]
| Column | Type | Desc |
| ------- | ---- | --- |
| compid | int | Component Id |
| packagename | vchar(1024) | Name of the package |
| packageversion | vchar(256) | Version of the package |
| cve | vchar(80) | Name of the CVE |
| cve_url | vchar(1024) | Url to the CVE details in the CVE website |
| license | vchar(256) | Name of the License for the package |
| license_url | vchar(1024) | Url to the License File |

_Note: Data is denormalized to simplify queries._

**Comment by zacharyljones** [comment]
Reopening to modify table name
