### ISSUE TITLE
plumbing: postgres docker image for test data

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#256]
Need a docker image that can be run locally to serve up postgres test data.

**Comment by sbtaylor15** [comment]
Instructions are in the readme in [ortelius/test-database](https://github.com/ortelius/test-database).

@Javailabe can we add this to the [Testing Environment](https://docs.ortelius.io/guides/contributorguide/developer-resouces/ )?

**Comment by Javailabe** [comment]
@sbtaylor15 update of Developer Resources pushed
