### ISSUE TITLE
Assignees issue

### ISSUE THREAD

**Issue by scanalesespinoza** [ortelius/ortelius#257]
Assign issue, checking I can assign to myself

**Comment by scanalesespinoza** [comment]
![image](https://user-images.githubusercontent.com/11546953/113587268-888a6300-95fc-11eb-9c53-b9f6630874ea.png)
No edit permissions @sbtaylor15

**Comment by sbtaylor15** [comment]
@scanalesespinoza see if you can self assign now.  Change the Dev team to have maintainer access.

**Comment by scanalesespinoza** [comment]
![image](https://user-images.githubusercontent.com/11546953/113603069-7535c280-9611-11eb-93e1-cbf3bae5a54d.png)
Fixed!
