### ISSUE TITLE
plumbing: istio routing for new microservices

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#258]

**Comment by sbtaylor15** [comment]
@scanalesespinoza thinking this for url paths:

/ms/deppkg - POST -> dep-pkg-cud container
/ms/deppkg - GET -> dep-pkg-r container

Open to suggestions on this.

**Comment by scanalesespinoza** [comment]
@sbtaylor15 works fine, I test it with:
```
  http:
  - match:
    - method:
          exact: POST
    redirect:
      uri: /dmadminweb/Home
```
And got a nice 301

```
[scanales@scanales-t470s ortelius-istio]$ curl -X POST -v http://192.168.99.101:30208/
*   Trying 192.168.99.101...
* TCP_NODELAY set
* Connected to 192.168.99.101 (192.168.99.101) port 30208 (#0)
> POST / HTTP/1.1
> Host: 192.168.99.101:30208
> User-Agent: curl/7.59.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< location: http://192.168.99.101:30208/dmadminweb/Home
< date: Tue, 13 Apr 2021 12:46:11 GMT
< server: istio-envoy
< content-length: 0
< 
* Connection #0 to host 192.168.99.101 left intact
```
I only have running the monolith, so need to deploy the other MS, thats why I ask for the meeting with you, want to check all the deployment we have

**Comment by scanalesespinoza** [comment]
@sbtaylor15 do you think we can close this one with the quickstart video? Prob we can open a new one with the implementation of the new microservices, to having a more specific use case

**Comment by sbtaylor15** [comment]
Removing isto
