### ISSUE TITLE
docker build: base image for python with odbc libraries

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#259]
Need base python 3 image that has the python odbc libraries.  Should be base on Apline or better yet a [Distroless image](https://github.com/GoogleContainerTools/distroless).

Goal is to minimize CVEs and only include what is needed.  

Following issues will consume this base image:
#153 
#154
#155 
#156

**Comment by karamjotsingh** [comment]
@ayesha-kr please refer to the latest Dockerfile from [here](https://github.com/ortelius/ortelius-ms-rpt-comp2env/blob/dev/Dockerfile). Tried for a multi-stage build, but python being an interpreted language no benefit in using a multi-stage build. Have added cyclonedx and trivy, both will generate their output JSON files which would be pushed to Ortelius down the line. Trivy might be moved to cloudbuild in the future. Have also fixed the vulnerabilities in the image.
