### ISSUE TITLE
Trying to use a Remote Procedure outside of a deployment

### ISSUE THREAD

**Issue by cawale** [ortelius/ortelius#26]
So I am trying to create an admin script that uses an environment and then calls some procedures. What I am finding is that the remote procedure call get totally bypassed. There is no error and no indication that the system has even acknowledged that the procedure call is actually in the code. The call works in a normal deployment.

This is my dmscript

```
using environment "${env}" { // use an environment 
    set servers = ${environment.servers};
  iterate(s: $servers) {
    if (${s.attributes.PATH_TO_WSADMIN} != "") { // I do this so that I can pick the right server to run the procedure on.
       set -g server = $s;                               // set the server so that one is selected before the call. This might be the problem since it is not really on the stack. Is there a way to force it on the stack?
       echo "Server: ${server.name}";            // check it. Yes it displays the correct server name.
       myecho(test: @"TEST***");                 // This is a procedure created in the database that I call to make sure I can call out. and Yes it displays a string successfully. It just does an echo.
       ws_all_remove_sharedlibs(Cluster: @"${cluster}"); // !!! This procedure is completely bypassed. !!!!
    }
  }
}
```

My output looks like this.

bash-3.2$ engine/bin/dm "-pw" "[password]" "-usr" "admin" "-appid" "127" "-sessionid" "C38487E8049A77805A184BCF1018CB9E" "-runtask" "222" "appsrv2=asdas" "cluster=SOACCluster" "appsrv1=asdas" "adminserver=Dev WebSphere 8_5 Admin" "was_credential_name=Dev_WAS_8_5_Admin" "env=GLOBAL.Claims.CFM.Development.Old_UAT" -debug 3
Server: Dev WebSphere 8_5 Admin
In My Echo TEST***

I am assuming that I have missed something that the remote procedure needs on the stack or somewhere. It's just odd that I don't get any kind of error or crash or anything?

I guess the root question is is this even possible to do?

Thanks.

**Comment by sbtaylor15** [comment]
Can you do an echo after ws_all_remove_sharedlibs(Cluster: @"${cluster}") to see if that gets executed or if its silently failing in the ws_all_remove_sharedlibs?

**Comment by cawale** [comment]
I see both echo's the one before and after.

**Comment by pgibbs-openmake** [comment]
Hi Chris,

What is ws_all_remove_sharedlibs? Is that another DMScript procedure or is that an external script?

A couple of things...you're setting "server" as a global object. (set -g) which is a bit "meh". It _should_ work as long as there's no other server on the stack but it's not great.

You're using "iterate" to walk through the server objects returned from the environment but that's a "generic" way of walking through lists of objects. I think there's a better way.

Once you have an environment on the stack, any "if" statement will filter the "server list" (the list of end-points associated with that environment) to only those end-points whose attributes match the given criteria. You can then use a psloop:

[https://www.openmakesoftware.com/helpRE75/NetHelp/index.html#!Documents/psloop.htm](https://www.openmakesoftware.com/helpRE75/NetHelp/index.html#!Documents/psloop.htm)

psloop iterates through all the current server list (which - if you're using it inside an "if" - will be restricted to those matching the criteria), and it will automatically push a "server" object onto the stack with each iteration.

So your code then becomes something like:

```
using environment "${env}" { // use an environment 
    if ($PATH_TO_WSADMIN != "") { // Filter the server list
        psloop {  // Loop through all the servers with PATH_TO_WSADMIN set  
             echo "Server: ${server.name}";            // psloop pushes current server object onto stack
             myecho(test: @"TEST***");                 // 
             ws_all_remove_sharedlibs(Cluster: @"${cluster}");
        }
    }
}
```
That's a bit simpler and ensures that there's a "server" object properly on the stack.

I presume "cluster" is an attribute stored against the server, in which case the above will ensure that the "cluster" variable will be available from the server on the stack. In the original case, I'm not sure it will be, but if it's not calling the procedure at all, then we have another issue.

**Comment by cawale** [comment]
ws_all_remove_sharedlibs is an external script.

Cool code. It does iterate through the server list but unfortunately does not change the result that ws_all_remove_sharedlibs is passed over.

The cluster variable is an argument for this DMScript procedure not in the server object.

One thought. I have changed the name of the external script procedure since it was originally created. Maybe it is not linking this name to the procedure? I have had some issues with this before. I am going to create a new one and see if that helps the situation.

**Comment by cawale** [comment]
ok so my thought was not the problem. If I don't setup the calling parameters right I get a runtime error and when I correct the issue it must call it but not do the remote part of it (transfer the script, run it). 

I see the same results as I did before. Everything gets run and I see no errors but the remote script call did not occur,

**Comment by pgibbs-openmake** [comment]
Ah, so the script is supposed to run on the target server? It's set to execute remotely?

**Comment by cawale** [comment]
Yes

**Comment by pgibbs-openmake** [comment]
Okay, well having a psloop should at least make that work a bit better (I'm not sure your original code would have worked without the pushing of a server object onto the stack... having it stored globally may have caused issues). However, if it's still not working, then that's an oddity. 

Does "myecho" run remotely or is that just set to run on the DeployHub server?

I presume the target is Unix? Has the script that sits behind ws_all_remove_sharedlibs being copied to /tmp on the target?

**Comment by pgibbs-openmake** [comment]
*supplemental* How are you invoking this? As a stand-alone action with parameters passed in?

**Comment by cawale** [comment]
myecho is a DMScript run locally.

Yes it is Unix. The script is not copied to the server on the target.

I am invoking it through an action attached to a Run Task.

**Comment by pgibbs-openmake** [comment]
Okay, that makes sense. I'm wondering if there's an issue running remote scripts when we're not in a deployment. We should have an environment and a server on the stack so in theory, it should work.

Steve - I'm on site all week - can you try and reproduce?

**Comment by pgibbs-openmake** [comment]
Chris, whilst Steve is setting this up on our test bench, can you email me the entire debug 3 output?

**Comment by cawale** [comment]
This is all there is.

bash-3.2$ engine/bin/dm "-pw" "May202017" "-usr" "admin" "-appid" "127" "-sessionid" "C38487E8049A77805A184BCF1018CB9E" "-runtask" "222" "appsrv2=asdas" "cluster=SOACCluster" "appsrv1=asdas" "adminserver=Dev WebSphere 8_5 Admin" "was_credential_name=Dev_WAS_8_5_Admin" "env=GLOBAL.Claims.CFM.Development.Old_UAT" -debug 3
Finished Setting WAS Vars
In Clean
GLOBAL.Claims.CFM.Development.Old_UAT
SOACCluster
Server: Dev WebSphere 8_5 Admin
In My Echo TEST***
Server Name in My Echo Dev WebSphere 8_5 Admin

Chris

**Comment by pgibbs-openmake** [comment]
It's not reading the -debug 3 because you've got it at the end after all the environment variables are set. You need to have it with all the other switches - put it after -runtask 222 and that should produce a lot more output!

**Comment by cawale** [comment]
Well that was silly of me.

Here it is.

**Comment by pgibbs-openmake** [comment]
I think it's been truncated Chris. Can you email me the log?

**Comment by cawale** [comment]
OK. So I think my initial issue is resolved but it does bring up a second issue.

Firstly, I was running it from the command line most of the time which seems to have shown a second issue with dmtransfer.

So your code suggestions I believe fixed the issue with the remote script not being setup correctly with the server. If I run it through the gui, as a run task, it shows that the remote script gets copied, run and succeeds. So I think that issue is resolved.

The new issue is that when running from the command line dmtransfer fails when invoking remote script calls. I have seen this before and know about this limitation but obviously in this new scenario when a remote procedure is being called from a dmscript the exception/crash gets gobbled up and you don't see it. That is why this didn't immediately jump out at me.

Thanks for all your help.

**Comment by pgibbs-openmake** [comment]
Well I guess there's good news and bad news there. The good is that the problem is resolved. The BAD is that I've absolutely NO IDEA why running it from the WebUI works and running it from the command line doesn't. However, that's a problem for another day!

**Comment by pgibbs-openmake** [comment]
Steve - I'm going to close this on the basis that it's working okay from the Web UI. However, can you see if you can reproduce the issue where a remote script fails to execute when running dm from the command line? If you can't then this may be a Solaris special....

**Comment by cawale** [comment]
Here is the log file for the last command line run I did. Just in case it can give you any info.
