### ISSUE TITLE
Error when creating and managing components

### ISSUE THREAD

**Issue by hatati** [ortelius/ortelius#260]
I have installed ortelius on our IBM Cloud Kubernetes service. When I try to create, edit and save a new component I get the following error in the console
`SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at n.parseJSON (jquery.min.js:4)
    at Qc (jquery.min.js:4)
    at x (jquery.min.js:4)
    at XMLHttpRequest.b (jquery.min.js:4)`
It looks like this:
![image](https://user-images.githubusercontent.com/8775749/113683048-0d8c7f80-96c4-11eb-9ea8-dd2fe31b66a8.png)

The component is still created but when I try to access it the UI gets stuck in some form of deadlock and never resolves
![image](https://user-images.githubusercontent.com/8775749/113681687-8ee31280-96c2-11eb-8254-1eca6889e9f0.png)

These are the console errors I get from the browser when accessing the component
![image](https://user-images.githubusercontent.com/8775749/113681865-ca7ddc80-96c2-11eb-93c1-11791204291b.png)

I have tried different tags of the ortelius software, but no luck.

The logs from the ortelius container doesn't show anything beside the standard setup logs:
```
+ sudo chown -R postgres:postgres /var/lib/pgsql
+ sudo chmod -R 777 /opt/deployhub
+ pkill postgres
+ sudo test -f /var/lib/pgsql/data/pg_hba.conf
+ echo 'Database already initialized'
+ sudo chmod 700 /var/lib/pgsql/data
Database already initialized
+ sudo -u postgres /usr/pgsql-10/bin/pg_ctl start --pgdata=/var/lib/pgsql/data
waiting for server to start....2021-04-06 08:19:06.356 UTC [19] LOG:  listening on IPv6 address "::1", port 5432
2021-04-06 08:19:06.356 UTC [19] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-04-06 08:19:06.360 UTC [19] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-04-06 08:19:06.364 UTC [19] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-04-06 08:19:06.372 UTC [19] LOG:  redirecting log output to logging collector process
2021-04-06 08:19:06.372 UTC [19] HINT:  Future log output will appear in directory "log".
 done
server started
+ sleep 10
+ sudo -u postgres /usr/pgsql-10/bin/pg_ctl status --pgdata=/var/lib/pgsql/data
pg_ctl: server is running (PID: 19)
/usr/pgsql-10/bin/postgres "-D" "/var/lib/pgsql/data"
+ '[' '!' -e /opt/deployhub/logs ']'
+ sudo mkdir /opt/deployhub/logs
+ '[' '!' -e /opt/deployhub/engine ']'
+ sudo chmod -R 777 /opt/deployhub
+ sudo chown -R omreleng /opt/deployhub
+ cd /opt/deployhub/engine
+ export LD_LIBRARY_PATH=/opt/deployhub/engine/lib:/opt/deployhub/engine/bin
+ LD_LIBRARY_PATH=/opt/deployhub/engine/lib:/opt/deployhub/engine/bin
+ export PATH=/opt/deployhub/engine/lib:/opt/deployhub/engine/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/google-cloud-sdk/bin:/usr/pgsql-10/bin:/usr/local/google-cloud-sdk/bin
+ PATH=/opt/deployhub/engine/lib:/opt/deployhub/engine/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/google-cloud-sdk/bin:/usr/pgsql-10/bin:/usr/local/google-cloud-sdk/bin
++ cut -d: -f6
+++ whoami
++ getent passwd omreleng
+ HOME=/home/omreleng
+ export HOME
+ sudo cp -r '/keys/*' /root/.ssh
cp: cannot stat '/keys/*': No such file or directory
+ sudo chown -R root /root/.ssh
+ sudo chmod 755 /root/.ssh
+ '[' -e /root/.ssh/known_hosts ']'
+ cp -r '/keys/*' /home/omreleng/.ssh
cp: cannot stat '/keys/*': No such file or directory
+ chown -R omreleng /home/omreleng/.ssh
+ chmod 755 /home/omreleng/.ssh
+ chmod 600 /home/omreleng/.ssh/known_hosts
chmod: cannot access '/home/omreleng/.ssh/known_hosts': No such file or directory
+ echo Running DeployHub Processes
Running DeployHub Processes
+ java -jar /opt/deployhub/webadmin/webapp-runner.jar --path /dmadminweb /opt/deployhub/webadmin/deployhub-webadmin.war
+ perl -pe '$_ = localtime.": $_"'
```

**Setup info**
- Kubernetes version: 1.19.9_1540
- Image repository: quay.io/ortelius/ortelius
- Image tag: master-v9.0.0.350-ga08ed02
- Istio version: 1.8

If you need more info please tell.

**Comment by sbtaylor15** [comment]
@hatati - let me take a look at what is happening.

**Comment by sbtaylor15** [comment]
Give the following image a try.  Should fix your issue.

`docker pull quay.io/ortelius/ortelius:maintenance-v9.0.0.360-gbe148b6`

**Comment by hatati** [comment]
Now I am not able to see or add any domains. Also, there is another TypeError this time. Without a domain, I can't test the component creations
![image](https://user-images.githubusercontent.com/8775749/114090719-147be380-98b8-11eb-8093-f4457d27a85c.png)

**Comment by sbtaylor15** [comment]
A sql file was missed in the merge from the downstream project.  Fixed now.  Use the following image
` docker pull quay.io/ortelius/ortelius:maintenance-v9.0.0.361-g2128af2`

**Comment by hatati** [comment]
Awesome, domains are present again and component creation is working. I'm closing this one. Thanks for the help!
