### ISSUE TITLE
microservice: dockerize and add helm chart and cloudbuild to bubble sort 2

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#262]
Do the following task one by one. Create for every separate task.

1. Dockerize the Bubble sort2 application.
2. Install and setup minikube on your machine and run the containerized image created above as pod and service.  (You need to do a read up on kubernetes, minikube, pod and services)
Output should be a yaml file that can be run kubernetes.
3. Create the helm chart for the above created POD and service. 
5.  Add cloud build changes
    See [CloudBuild example](https://github.com/ortelius/ortelius-ms-rpt-app2env/blob/master/cloudbuild/cloudbuild.yaml)
6. Once done replace the base image.
Base image: `tiangolo/meinheld-gunicorn-flask:python3.8-alpine3.11`
Additional packages: gcc libc-dev g++ libffi-dev libxml2 unixodbc-dev postgresql-dev

**Comment by ayesha-kr** [comment]
@BBimie I have added some details in the ticket please take a look at them.
