### ISSUE TITLE
Datatables warning appears randomly

### ISSUE THREAD

**Issue by camba1** [ortelius/ortelius#268]
Unfortunately, I do not know how to reproduce this consistently, but the warning below appears randomly while using the app:

`DataTables warning: table id=actionlist - Ajax eror. For more information about this error. please see http:/datatables.net/tn/7`

Looking at the error again , the table id seems to change, I am guessing depending on where I am in the app.

Using the latest Ortelius image from pulled from Quay

<img width="512" alt="Screen Shot 2021-04-14 at 12 39 17 PM" src="https://user-images.githubusercontent.com/7367366/114756249-29c19980-9d20-11eb-8f48-f0e17b6701bf.png">

**Comment by sbtaylor15** [comment]
We will need to look at the server logs to see why an exception is being thrown.  The data being returned is not parsable by the datatables js code.

**Comment by sbtaylor15** [comment]
closing.  fixed backend code
