### ISSUE TITLE
Getting a list of all environments

### ISSUE THREAD

**Issue by cawale** [ortelius/ortelius#27]
Is there a DMScript way to get all the environments?

I have used the rest service to retrieve them but I was wondering if there is a way within DMScript to get them directly?

Thanks

**Comment by sbtaylor15** [comment]
Do you want all of the environments that an application belong to?  Or just a complete list regardless of application?

**Comment by cawale** [comment]
A complete list like the rest api call does with the ‘all=y’ parameter.

**Comment by sbtaylor15** [comment]
You will need to call the Restful API from the DMScript.  DMScript will automatically parse the JSON into DMScript objects. See restful_get  in https://www.openmakesoftware.com/helpRE75/NetHelp/index.html#!Documents/restfulget.htm
