### ISSUE TITLE
Component details disappear after save of new component

### ISSUE THREAD

**Issue by camba1** [ortelius/ortelius#273]
Steps to recreate:

- Go to the components screen
- Click create new component 
- Enter a name (and anything else you need)
- click save
- Application saves and the details disappear. 
- Go back to search screen and notice the details of the component are still there (saved)
- Go into the component details and notice that the component details are still missing

This makes it really hard to modify components, it is easier to delete and recreate which will be a problem as amount of data in the system grows

Browser: Chrome 89.0.4389
Ortelius running in the latest image downloaded from Quay

Before save:

<img width="1312" alt="Screen Shot 2021-04-14 at 5 44 09 PM" src="https://user-images.githubusercontent.com/7367366/114790422-59859700-9d4a-11eb-9b57-3983d00f26cb.png">

After Save:
<img width="1312" alt="Screen Shot 2021-04-14 at 5 45 08 PM" src="https://user-images.githubusercontent.com/7367366/114790394-4d013e80-9d4a-11eb-9c15-04485159bba2.png">

Search Screen after save:
<img width="1312" alt="Screen Shot 2021-04-14 at 5 46 00 PM" src="https://user-images.githubusercontent.com/7367366/114790357-3f4bb900-9d4a-11eb-92ed-22dd86ba27f2.png">

**Comment by sbtaylor15** [comment]
Not able to recreate this.  We will need to do a web meeting to debug.
