### ISSUE TITLE
Package components screen visualization needs scrollbar

### ISSUE THREAD

**Issue by camba1** [ortelius/ortelius#276]
In the package components tab of the application tab, the visualization :
- Is off center and thus can lead to components overlapping the component selector section and limits the amount of usable space
- Really needs vertical and horizontal scrolling. As it stands, the real-estate provided is just enough for a small number of components displayed (given that an real microservice app could have hundreds of components)

<img width="1072" alt="Screen Shot 2021-04-15 at 5 12 20 PM" src="https://user-images.githubusercontent.com/7367366/114945459-f6aa0380-9e0e-11eb-91c8-0bc8e9f9dae0.png">

**Comment by sbtaylor15** [comment]
This page needs to be replaced with a table to fix the layout issues and handle 1000s of components associated to an application.  Also, the current layout is deceiving since it is the deployment order and not the component to component relationships.

**Comment by camba1** [comment]
I created issue 280 for the fact that this page effectively has a split personality disorder :)(https://github.com/ortelius/ortelius/issues/280)
This issue can remain to fix the more short term layout issue

**Comment by sbtaylor15** [comment]
closing.  New architecture will address this.
