### ISSUE TITLE
Run Task times out

### ISSUE THREAD

**Issue by cawale** [ortelius/ortelius#28]
I am trying to run a run task that takes a while to complete. The UI comes back with nothing or somethings an error. It is not the functions I am running because they all work individually. 

I assume there is a timeout setting somewhere.

Is this a setting I can update within the tool?

**Comment by sbtaylor15** [comment]
Do you get anything back in the log? Or just hung right at the beginning?

**Comment by cawale** [comment]
The script runs and everything but the UI fails.

When it completes you don’t get the completion dialog with the log info in it. It actually puts you back on the initial run dialog where you could start it running again. No text except for the dialog title.

**Comment by sbtaylor15** [comment]
What happens when you goto the Timeline and view the deployment log from there?  I just fixed an issue yesterday where Jenkins was sending NULL back to DeployHub which caused the deployment log to be empty.  This may be related.

**Comment by cawale** [comment]
There is no timeline since the run task is not associated with any application deployment.

**Comment by pgibbs-openmake** [comment]
There's no timeout as far as I recall. Normally, the dialog disappears as soon as you click OK. The "result" dialog only appears if the task is set to "Show Output" but that's not what's happening here. You're saying you're clicking OK and the dialog is not disappearing? Or it disappears and then reappears?

When you say "sometimes an error" - is this in the "result" popup dialog (with Show Output checked) or does this appear on the initial "Run Task" dialog. And - if you DO get an error - what does it say?

**Comment by cawale** [comment]
This is what I see once I have selected 'OK' and run the task.

![image](https://user-images.githubusercontent.com/34170905/37730914-39835e3e-2d17-11e8-85ab-3d872c92b897.png)

Then the loading stays there for the length of time it takes to run the task.

Once that is done I get the original dialog again.

![image](https://user-images.githubusercontent.com/34170905/37731318-25c8cb12-2d18-11e8-82da-53246fa25126.png)

 I have only seen an error once and that was "Run Task Failed" I believe.

**Comment by pgibbs-openmake** [comment]
Okay, we may have to take a look at that - if you have "show output" checked I think (from memory) it _has_ to hold the dialog until the job completes (since you probably don't want a pop-up dialog to appear asynchronously) ... but the dialog should eventually clear and show the output from the job.

Would you want the initial dialog to clear and the result dialog to appear whenever the job completes (regardless of what you may be doing at the time?)

How long does the task take to run?

**Comment by cawale** [comment]
I do have 'show output' on. What I would really like is to show the result dialog as soon as I press the 'OK' button and then show me the log lines as they are available. Like the log dialog for deployments. A refresh button would be OK too.

The script runs for about 5 minutes maybe a bit longer.

**Comment by pgibbs-openmake** [comment]
Okay, we'll file that under "enhancement request"! However, what you're describing sounds like a bug that manifests during long running tasks.

Steve - does the modal "Loading" dialog time out at some point? I didn't _think_ it did but I'm try to figure out what's going on here...

**Comment by sbtaylor15** [comment]
No, I should not have a timeout.

**Comment by pgibbs-openmake** [comment]
Okay, I wonder why it returns to the launch dialog when the task completes then?

Could you try and reproduce with a long-running task? Just stick a sleep(delay: 600) followed by echo "hello" into an Action, stick that onto a Run Task and see what happens...

**Comment by cawale** [comment]
Will do

**Comment by pgibbs-openmake** [comment]
Great, thanks. If you still get the same issue it should be easier for us to try and reproduce it at this end.

**Comment by cawale** [comment]
OK. So that ends in the same result. The original run task dialog showing.

![image](https://user-images.githubusercontent.com/34170905/37734054-6cfae81e-2d20-11e8-9505-28a662e6c55a.png)

**Comment by pgibbs-openmake** [comment]
Ok, sounds like something is definitely timing out somewhere. Leave it with us.

**Comment by cawale** [comment]
Thanks
