### ISSUE TITLE
Package components in applications should be divided into 2 pages

### ISSUE THREAD

**Issue by camba1** [ortelius/ortelius#280]
The Package components page in the application tab currently combines two purposes:

- Define deployment order of components 
- Define which components are associated with the application. In fact this is the only place you can associate a component to an app

However these two items are just loosely related and thus should be separated. For example, you probably want to associate a database to an application so that you can have a complete laundry list of everything related to the app. However, you may not want or need to deploy the database every time you deploy an application. So the database should be added to the components association list but not to the deployment order list.

**Comment by sbtaylor15** [comment]
No longer doing deployments
