### ISSUE TITLE
Missing image repository in component creation

### ISSUE THREAD

**Issue by hatati** [ortelius/ortelius#289]
When creating a new component of type container the image repository property doesn't get persisted when saving the component.
Here is an example
![ortelius-bug](https://user-images.githubusercontent.com/8775749/115880904-8113e800-a44b-11eb-8417-bc10c3474562.gif)

This is running in AKS Kubernetes version 1.19.2

**Image**: quay.io/ortelius/ortelius:master-v9.0.0.388-g2c13bda

**Comment by sbtaylor15** [comment]
Resolved in image:   quay.io/ortelius/ortelius:maintenance-v9.0.0.392-g67b80e7
Need to verify before pushing to main branch.
