### ISSUE TITLE
Please allow dashes in names e.g. DSL-BC or DSL-WEBAPPPL

### ISSUE THREAD

**Issue by svcautomator** [ortelius/ortelius#29]
I have noticed when creating credentials and repositories that - is not allowed.  When trying to set things up for multiple applications - (dash) is a very common separator.  Not a high priority, but a nice to have.

**Comment by pgibbs-openmake** [comment]
Unfortunately, this can break things since A-12 (for example) could be an equation as well as an identifier. For this reason, dashes are explicitly prevented from being used in identifier names.

Underscore is allowed, however.

**Comment by svcautomator** [comment]
ala Oracle... ok.
