### ISSUE TITLE
Access app at root instead of /dmadminweb/Home

### ISSUE THREAD

**Issue by camba1** [ortelius/ortelius#290]
Enhancement request: 

Currently accessing `http://<orteliusAddress>:<port>/ ` opens to an empty page. Can we instead redirect it to the application front page (`http://<orteliusAddress>:<port>/dmadminweb/Home`) ? 
This way user do not have to remember the additional url portion (plus that way in minikube I can just do `minikube service ortelius` to launch the app :)  )

**Comment by sbtaylor15** [comment]
Need to add ngnix to image an have it do the redirect since the tomcat webapp runner does not have a default ROOT context.
