### ISSUE TITLE
Component shows as never deployed even though it has been "deployed"

### ISSUE THREAD

**Issue by camba1** [ortelius/ortelius#295]
Component in the Component search screen shows as never having been deployed while the detail screen (and the related application) shows that it has indeed been deployed. Note that I used the default 'Deploy to environment' option to deploy manually.

<img width="1207" alt="Screen Shot 2021-04-24 at 2 46 35 PM" src="https://user-images.githubusercontent.com/7367366/115971141-60f82d80-a50c-11eb-84c8-008cbea6c08c.png">

<img width="1207" alt="Screen Shot 2021-04-24 at 2 45 42 PM" src="https://user-images.githubusercontent.com/7367366/115971085-22627300-a50c-11eb-943c-38cbdefcd04a.png">

**Comment by sbtaylor15** [comment]
The component was manually deployed to the environments so there is no log file to show.  The Last Deployment column shows the deployment log number for deployments that have been performed by the deployment engine.  "Never deployed" is trying to say that the deployment engine has not been used to deploy the component version.  

Any ideas on how to re-word this?  Maybe "Never deployed", "Manual Deployment" or the deployment number.

**Comment by camba1** [comment]
I think it should be as consistent as possible with what would happen if the deployment engine had performed the task. So, if the deployment engine normally  puts a number there, a manual deployment should do the same thing if possible

**Comment by sbtaylor15** [comment]
The hard part is that a manual deployment doesn't have a deployment number.  So all we can do is use "Manual Deployment" in that column.  Do you think that will be clear enough?

**Comment by camba1** [comment]
'Manual deployment' is definitely  better than 'Never deployed' for sure.
