### ISSUE TITLE
Question: What is the map option meant to show in the component tab?

### ISSUE THREAD

**Issue by camba1** [ortelius/ortelius#296]
Looking in the components tab, the list shows the mapping between the component and its domain. 
On the other hand, the map appears to show a mapping between the components and the applications consuming them.

Should the map and the list views be consistent on what they are trying to convey? Or maybe there should be an option to see either the component - application  view or/and the component - domain view?

Thanks!

**Comment by sbtaylor15** [comment]
The map from the components tab will show all of the application versions that are consuming the component version regardless of the domains.  This is the inverse of the map you get from the applications tab.

**Comment by TracyRagan** [comment]
We should update the documentation to clarify.

**Comment by jayesh-srivastava** [comment]
Hi. I would like to work on this issue if it's available. Can anyone please guide me a little bit as to what is to be done?

**Comment by TracyRagan** [comment]
Updated doc.
