### ISSUE TITLE
Setup Dev environment/access to k8s cluster for GitOps testing

### ISSUE THREAD

**Issue by bradmccoydev** [ortelius/ortelius#299]
As a Developer in the GitOps working group
I require access to test Ortelius and GitOps tools such as ArgoCD
So I can collaborate with others, and finish the whitepaper on "Automating GitOps with Ortelius"

This environment should either already exist or we have access to spin up a k8's cluster for testing.

@bradmccoydev has his own deployment scripts for GCP, AKS, EKS, etc if required.

If an environment already exists we would need some namespaces created and users with a role.

**Comment by tbulubas** [comment]
Hi @bradmccoydev 
I am interested in GitOps, particularly ArgoCD & Co. (working on automation right now, k8s and openshift and other stuff) I would like to help you with this. 
Regards, Taras

**Comment by bradmccoydev** [comment]
Hi @tbulubas thats great news, which time zone are you in?

**Comment by tbulubas** [comment]
Hi @bradmccoydev  I'm in Europe/Berlin Timezone, what about you?

**Comment by bradmccoydev** [comment]
@tbulubas great, we can catch up sometime 12pm Berlin time suits me if you are available one day then. We need someone to learn Flux, or Flagger, as we have two people learning Argo at the moment. Do you have interest in either of those?

**Comment by tbulubas** [comment]
hi @bradmccoydev 12pm Berin time is good, I am intersted in both frameworks, sounds perfect to me, flagger goes with flux together, let's talk later today

**Comment by sbtaylor15** [comment]
@tbulubas @bradmccoydev we received another 12 months of Azure credits.  The switch on the billing account will happen on 6/3.  I will work on AZ access control setup once the switch is done.

**Comment by bradmccoydev** [comment]
Hi all, this has been done.  @tbulubas I will speak to you tonight/ (lunch time berlin)
