### ISSUE TITLE
Calling Remote Procedure using strings with spaces in command line

### ISSUE THREAD

**Issue by cawale** [ortelius/ortelius#30]
Hi,

I am trying to run a remote script on an endpoint and the parameters that are required to be passed are stings with spaces. I cannot seem to find a way to get quotes put around the parameters. If I put them in the Action that calls the procedure then the deployment just fails because, I believe, of the double quotes that are in the DMScript that is generated 

  ws_create_jdbcprovider(Server: @"${was_server}", Classpath: @""${DERBY_JDBC_DRIVER_PATH}/derby.jar"", Implementation_Type: @""XA data source"", Database_Type: @"Derby", Name: @""Logger Derby JDBC Provider (XA)"", Provider_Type: @""Derby JDBC Provider"", Description: @""Derby embedded XA JDBC Provider. This provider is only configurable in version 6.0.2 and later nodes"", Cluster: @"${was_cluster}");
  return;

I can't tell what the crash actually is because when I run it from the command line dmtransfer fails with "Failed to create Target Directory". (It transfers fine when I run it from the GUI but that is another issue) So I cannot tell you where exactly it fails.

If I run it with no quotes 

  ws_create_jdbcprovider(Server: @"${was_server}", Classpath: @"${DERBY_JDBC_DRIVER_PATH}/derby.jar", Implementation_Type: @"XA data source", Database_Type: @"Derby", Name: @"Logger Derby JDBC Provider (XA)", Provider_Type: @"Derby JDBC Provider", Description: @"Derby embedded XA JDBC Provider. This provider is only configurable in version 6.0.2 and later nodes", Cluster: @"${was_cluster}");
  return;

I get this error when it tries to run the script:

bash: -c: line 0: syntax error near unexpected token `('
bash: -c: line 0: `sh -c cat - >/tmp/create_jdbcproviderws.py;/apps/ibm/websphere/appserver/v8552/bin/wsadmin.sh -lang jython -user **** -password ******** -p /export/home/walec/mysoap.client.props -f /tmp/create_jdbcproviderws.py -cluster SOACCluster -name Logger Derby JDBC Provider (XA) -description Derby embedded XA JDBC Provider. This provider is only configurable in version 6.0.2 and later nodes -impltype XA data source -providertype Derby JDBC Provider -server  -databasetype Derby -classpath    /derby.jar   '

Pretty sure it is complaining about the bracket as part of the (XA) text which it thinks is part of the command line not part of the script parameters.

Thoughts?

**Comment by cawale** [comment]
I did some more testing and I am not sure if the 'Preserve with "" when not present' option is working when defining procedure parameters.

It does not seem to make any difference on the resulting command line.

**Comment by sbtaylor15** [comment]
So it should be:

`
-name 'Logger Derby JDBC Provider (XA)' -description 'Derby embedded XA JDBC Provider'`

with single ticks around the parameters with spaces?

**Comment by cawale** [comment]
That is what I would expect but that is not what is happening.

**Comment by sbtaylor15** [comment]
Try putting in 'Logger Derby JDBC Provider (XA)' or "Logger Derby JDBC Provider (XA)"  (with the single tick or double quotes) as the value in the entry field.

**Comment by cawale** [comment]
With single quotes I get:

INFO: Deployed File hsc_s_loggerserviceEAR-2.0.4.ear -> Dev WebSphere 8_5 Admin:/export/home/walec/deploy/hsc_s_loggerserviceEAR-2.0.4.ear

bash: -c: line 0: syntax error near unexpected token `('bash: -c: line 0: `sh -c cat - >/tmp/create_jdbcdatasourcews.py;/apps/ibm/websphere/appserver/v8552/bin/wsadmin.sh -lang jython -user xxxxx -password xxxxx -p /export/home/walec/mysoap.client.props -f /tmp/create_jdbcdatasourcews.py -cluster SOACCluster -server  -datasourcename Derby JDBC Driver XA DataSource -helperclass com.ibm.websphere.rsadapter.DerbyDataStoreHelper -jndiname jdbc/failoverDB -containermanagepersistence true -providername Derby JDBC Provider (XA) -resourceprops [databaseName java.lang.String /data/AppSrvSOAC/DerbyFailover]'

with double quotes crashes out and the debug.out log shows:

protocol_put(hsc_s_loggerserviceEAR-2.0.4.ear)
cmd=[sshexec -sftp  -m "10.77.10.251" -port "22" -usr "xxxxx" -pw 'xxxxxx' put "hsc_s_loggerserviceEAR-2.0.4.ear" "/export/home/walec/deploy/hsc_s_loggerserviceEAR-2.0.4.ear"]
OMExecuteCmd returns 0
line=[cat: output error (0/100 characters written)
]
line=[Broken pipe
]
about to return res=1

**Comment by cawale** [comment]
Any ETA on this?

**Comment by sbtaylor15** [comment]
So create_jdbcdatasourcews.py should be copied from the DeployHub engine to the end point or does it already exist?

**Comment by sbtaylor15** [comment]
Also, can you check to see if you have a /tmp/trans.txt file.  If so, please send the dmtransfer line for this deployment.  I need to verify that the parameters to dmtransfer are quoted correctly.

**Comment by cawale** [comment]
create_jdbcdatasourcews.py is transferred to the endpoint correctly. I can see it in the tmp folder. The error occurs after that.

**Comment by cawale** [comment]
This is all that I am seeing in the trans.txt file for this deployment

dmtransfer "-protocol" "sftp" "-sourcedir" "/tmp/tdm.67285.1" "-targetdir" "/export/home/walec/deploy" "-user" "xxxxx" "-password" "xxxxxx" "-target" "unix" "-server" "10.77.10.251"

**Comment by sbtaylor15** [comment]
Add the following to the start of the sshexec.  We need to record the arguments being passed in.   I am trying to figure out how the parameters with spaces are handled.  Let me  know the results of the /tmp/args.txt

```
echo "START" >> /tmp/args.txt
for i in $*; do 
  echo $i >> /tmp/args.txt
done
echo "END" >> /tmp/args.txt
```

**Comment by cawale** [comment]
So when I put double quotes around the string it never gets to the dmtransfer step. When I put it in with single quotes it does. Here is the output from the args.txt.
[args.txt](https://github.com/OpenMake-Software/DeployHub/files/1894940/args.txt)

**Comment by cawale** [comment]
also here is the current sshexec script
[sshexec.txt](https://github.com/OpenMake-Software/DeployHub/files/1894945/sshexec.txt)

**Comment by sbtaylor15** [comment]
Looks like the spaced parameters are coming in as separate arguments instead of as a single one.  Let me do some debugging.

Thanks Steve

**Comment by sbtaylor15** [comment]
What happens when you don't put any single quotes or double quotes?  Send the args.txt if it runs.

**Comment by cawale** [comment]
Here you go.

[args.txt](https://github.com/OpenMake-Software/DeployHub/files/1895500/args.txt)

**Comment by sbtaylor15** [comment]
I found a difference in shell between using $* and "$@" in the loops for the parameters.

Change 

```
echo sshexec $@ >> /tmp/sshexec.out

echo "START" >> /tmp/args.txt
for i in $*; do 
  echo $i >> /tmp/args.txt
done
echo "END" >> /tmp/args.txt

```
to

```
echo sshexec "$@" >> /tmp/sshexec.out

echo "START" >> /tmp/args.txt
for i in "$@"; do 
  echo $i >> /tmp/args.txt
done
echo "END" >> /tmp/args.txt
```

And run without any single or double quotes on the DeployHub GUI side.  Send me the args.txt from that run.

**Comment by cawale** [comment]
here you go.
[args.txt](https://github.com/OpenMake-Software/DeployHub/files/1908105/args.txt)

**Comment by sbtaylor15** [comment]
Base on the last output it looks like the parameters are coming into sshexec script correctly but not being passed across to the remote machine with the right quotes in place.  I need to rework sshexec to create a temporary file with the remote call in it instead of trying to do everything in one go.

**Comment by sbtaylor15** [comment]
Ansible replaces sshexec.  Quoting of parameters is now working.
