### ISSUE TITLE
Help writing/formatting Whitepaper for Automating GitOps with Ortelius

### ISSUE THREAD

**Issue by bradmccoydev** [ortelius/ortelius#300]
As a Developer doing research into Automating GitOps with Ortelius
I need to write a whitepaper and don't have time in google docs to format it and manage it
I need someone to help with this, and they don't need to be technical.

I have already created the structure of the whitepaper, and need help linking the table of contents, etc to make it presentable to everyone.

@bradmccoydev is also happy to teach you some GitOps if you want learn also

**Comment by bradmccoydev** [comment]
here is a good link for content on what gitops is: https://gitops-community.github.io/kit/#what-is-gitops

**Comment by scanalesespinoza** [comment]
Hi @bradmccoydev I had a google presentation I use to customers, is related to RedHat but at the end ar community projects, share me and google email if you want to review it

**Comment by bradmccoydev** [comment]
@scanalesespinoza thanks that would be great it's bradmccoydev@gmail.com

**Comment by scanalesespinoza** [comment]
Shared! if you want we can coodinate a working session for this

**Comment by sbtaylor15** [comment]
@bradmccoydev do you have a shared doc link for the white paper?

**Comment by Arvind644** [comment]
@bradmccoydev I want to work on this issue

**Comment by Aju100** [comment]
@bradmccoydev can I work on this issue it's inactive and need a few drafts or guidelines
