### ISSUE TITLE
Fixing broken link for Pull Request (PR) Cheat Sheet in documentation

### ISSUE THREAD

**Issue by karamjotsingh** [ortelius/ortelius#303]
For this page [Developer Resources](https://docs.ortelius.io/guides/contributorguide/developer-resouces/) the link associated with the text **PR Cheat Sheet** is broken as pointing to an invalid resource. Needs to be fixed with this [link](https://docs.ortelius.io/guides/contributorguide/pull-request-cheat-sheet/).

**Comment by sbtaylor15** [comment]
@Javailabe can you please take a look at the broken link?

**Comment by Javailabe** [comment]
@sbtaylor15 Thank you for this assignment. I pushed updated version - it should work now.
