### ISSUE TITLE
Investigate tooling around integrating swagger/openapi specs for services within the service catalog

### ISSUE THREAD

**Issue by obowersa** [ortelius/ortelius#306]
Issue created off the back of the architecture meeting.

We want to look into integrating swagger/openapi specs with the service catalog.  At a high level, we want to look into how we can import openapi/swagger specs  + version information and integrate it with services in the service catalog to provide additional information about which API's a service provides.

Creating this initially as a placeholder to expand on with tooling/examples in the wider ecosystem, and a place to better define the requirements.

**Comment by sbtaylor15** [comment]
@jessegonzalez and @peRFectBeliever  please find a JS library that we can incorporate into Component Details page to render the swagger or openapi files.  We will store the files in database so they are versioned and match up with the Component Version.

**Comment by jessegonzalez** [comment]
Do we have a licensing requirement? Apache, MIT, others?

> We will store the files in database so they are versioned and match up with the Component Version.

Regarding storing in the DB, thoughts on storing the OpenAPI document in a ConfigMap? We could standardize on the ConfigMap name, maybe something like `openapi-<component><-component version?>.`

Maybe we should talk about the end user workflow to add/update the document in the database.

**Comment by sbtaylor15** [comment]
For licensing, Apache or MIT.  One of the licenses that are unrestrictive.

1. Lets say the swagger json file is checked into the git repo with the source code then we could pull from the git repo and add it to the ortelius db as part of the CI/CD pipeline.
2. Or we use a pointer to the file and pull it at render time. 

Option 1 enables us to be disconnected from the repo and render at anytime.

The end user would add the file location in the CI/CD workflow tool such as the Jenkinsfile or via a toml file that the CI/CD Ortelius Plugin would read.  See a sample [Jenkinsfile](https://github.com/ortelius/compupdate/blob/main/Jenkinsfile) for the integration.  Line 50 is where we look for the README to associate with the component version.

**Comment by sbtaylor15** [comment]
@jessegonzalez any luck finding a JS library we can use?

**Comment by sbtaylor15** [comment]
dependent upon #326

**Comment by sbtaylor15** [comment]
completed
