### ISSUE TITLE
microservice: python function for database connection and retry.

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#307]
Currently, the microservices connect to the db on startup.  If the database is not available the startup fails which causes "crashloopbackoff".   Also, if the db is taken down while the container is running then connection variable in the python code is no longer valid.

Need a function that will see if the microservice is connected to the db.  if not then retry otherwise use the existing connection.

**Comment by sbtaylor15** [comment]
@scanalesespinoza suggested [pybreaker](https://pypi.org/project/pybreaker/).  

Goal is to have a very small simple way to handle the use case.

**Comment by sbtaylor15** [comment]
FYI, need to return failure back to the caller to avoid hang the client side.  It should then continue trying to correct itself.

**Comment by scanalesespinoza** [comment]
Got it, and I was thinking the seman when I was helping Munnie with the connection error. Ok working on it

**Comment by tbulubas** [comment]
What about this: 1. implement DB healthcheck (simple new connect/select/close sql) that microservice 'readiness' uses during start (will not be ready to serve request untill DB runs OK) 2. using it for liveness would cause microservice to restart, so connection pool will be refreshed. I suppose miscoservice runs under k8s in container.

**Comment by sbtaylor15** [comment]
@tbulubas something like that could work.  Need to pin down the logic since we would not necessarily want to connect to the db on startup but delay it for the first transaction.  For example, 100 microservices in the k8s and only 20 of them are used frequently.    

if we connect on startup then we have 100 db connections.  If we connect on usage, then only 20.  We will have a cost hit for first transaction to establish a connection but should be minimal. Once a connection is established then reuse it.

I think your idea of incorporating the health check could work if we can figure out where to hook it into the microservice.

**Comment by sbtaylor15** [comment]
@scanalesespinoza can you post the pybreaker code that you have working so far to a repo so I can grab it and take a look at it?

**Comment by scanalesespinoza** [comment]
Hi @sbtaylor15 , I was working based on this repo https://github.com/gjorgjinac/recommender_server
Similar what we have

**Comment by scanalesespinoza** [comment]
Hi @sbtaylor15  here is a PR with the local tested circuit breaker https://github.com/ortelius/ortelius-ms-dep-pkg-cud/pull/5
Need a peer review o tested from my fork in another environment just to double check.
Maybe @tbulubas can do the review

**Comment by sbtaylor15** [comment]
Looks good and simple.  Merged the PR.  Thanks for working on this.
