### ISSUE TITLE
Is there a way to disable deploy tasks at the environment domain level?

### ISSUE THREAD

**Issue by cawale** [ortelius/ortelius#31]
I don't want developers to shortcut the gating/move process by selecting the deploy task at environment domains. I want to force them to deploy from the application object. 

Is there a way to do this?

**Comment by sbtaylor15** [comment]
Which level is your deploy task defined?  Can you send a screen shot?

Thanks, Steve

**Comment by cawale** [comment]
Is this the screenshot you were looking for?

![image](https://user-images.githubusercontent.com/34170905/37794217-4015cbee-2de7-11e8-89a2-ab06c958f37c.png)

**Comment by sbtaylor15** [comment]
If you run the deployment task from by right clicking on the Development subdomain you will be presented with the Application Versions and Environments that you would like to deploy to.  This is the same as selecting an Application Version with right click deploy task.  The Application Version is pre-selected in this case in the drop down along with the Environments list.

Both ways are will go through the same logic once the deployment is submitted.

**Comment by cawale** [comment]
Right but I don't want developers deploying, to say the System Testing environment, unless there is a move task executed so that the application has been moved to that environment. At this point I can select an environment domain and deploy any application to it including those that are not in that environment yet.

![image](https://user-images.githubusercontent.com/34170905/37795566-32fa3450-2deb-11e8-9322-aced1ae27adf.png)

**Comment by sbtaylor15** [comment]
Reworked UI.  Need to test that the dropdown is listing the environments correctly.

**Comment by TracyRagan** [comment]
Deployments have been removed. Issue can be closed.
