### ISSUE TITLE
Create Helm chart for ArgoCD for the AKS-Cluster

### ISSUE THREAD

**Issue by bradmccoydev** [ortelius/ortelius#319]

**Comment by scanalesespinoza** [comment]
Hi @bradmccoydev what information is needed to get acces to the cluster?

**Comment by bradmccoydev** [comment]
Hey @scanalesespinoza, @sbtaylor15 will have to add you to the group.  We will be creating a namespace called gitops and will be deploying ArgoCD to it

**Comment by bradmccoydev** [comment]
@tbulubas we will deploy this tomorrow

**Comment by bradmccoydev** [comment]
This has now been complete
