### ISSUE TITLE
Uploading patterns in a massive way

### ISSUE THREAD

**Issue by alanromo** [ortelius/ortelius#32]
Is there a way to upload patterns in a massive way?
What I would like to be able to do is to add a big list of file names to be deployed in the patterns tab of a connection.
Think about this as a huge set of arbitrary file names  (they don't follow any pattern name ... I can't use wildcards)
Adding one by one using the GUI can be a tiresome task and prone to make typos.
I know beneath Deployhub there are a set of Postgress tables. Perhaps If I was able to interact directly with those tables I would be able to upload a csv file into the table holding those patterns.

Any suggestion?

**Comment by sbtaylor15** [comment]
Would a recursive directory list work?  Or do you need to pick and choose files?

**Comment by sbtaylor15** [comment]
Also, do all of those files belong to single component or multiple ones?

**Comment by alanromo** [comment]
I need to pick an choose. A recursive list wouldn't work
Belong to a single component

**Comment by sbtaylor15** [comment]
I just looked at the API set and I need to add one to create a Component and the corresponding Component Items.  You will be able to drive this mass update from a script.

**Comment by sbtaylor15** [comment]
I have the APIs needed exposed now on my dev machine.  Let me put together a sample script for using the API calls to do the bulk load.

**Comment by alanromo** [comment]
Any news on this topic?

**Comment by sbtaylor15** [comment]
What type of repository are you using for the Component Items, file system or http?

**Comment by alanromo** [comment]
file system

**Comment by sbtaylor15** [comment]
Which version (OSS vs Pro) and OS are you using for DeployHub?

**Comment by alanromo** [comment]
OSS running on Windows 10 Enterprise.1709

**Comment by sbtaylor15** [comment]
You will need an updated war file that contains the new APIs.

[dmadminweb.war.zip](https://github.com/DeployHubProject/DeployHub/files/1956517/dmadminweb.war.zip)

To install -

1. Stop the DeployHub Web Admin Service
2. Backup the dmadminweb/WEB-INF/web.xml (under the web app install)
3. Delete the dmadminweb directory
4. Unzip the the above war file into dmadminweb
5. Copy the backup web.xml into dmadminweb/WEB-INF/web.xml
6. Start the DeployHub Web Admin Service
7. Make sure the structure of the web app directory is identical before and after the expanding the new war

Here is a sample script that uses curl to do the restful API calls.  The flow is as follows:

1. Login
2. Create a new Component Version based on the last version
3. Create a new Component Item for the Component Version created in step 2.  The removeall=Y is used to cleanup items copied over from the previous version
4. Create another new Component Item for the Component Version created in step 2.  The removeall is not used so no delete is performed

NOTE: The urls need special characters escaped, ie spaces and semi colons.

[bulkloaditems.sh.zip](https://github.com/DeployHubProject/DeployHub/files/1956535/bulkloaditems.sh.zip)

**Comment by alanromo** [comment]
thanks, I'll work this and let you know results

**Comment by alanromo** [comment]
thanks, I'll work this and let you know results

**Comment by alanromo** [comment]
I'm trying to follow your instructions.
Regarding step 2... I only can find with that name on my lap top the file C:\Program Files\Openmake Software\DeployHub\WebAdmin\libs\dmadminweb.war
I can't find such directory-file: dmadminweb/WEB-INF/web.xml
I'm showing hidden files and I can't find it.
Any idea where it is?

**Comment by sbtaylor15** [comment]
The war is exploded out as part of the installer.  Its under  C:\Program Files\Openmake Software\DeployHub\WebAdmin\tomcat\webapps in the dmadminweb directory.  Backup C:\Program Files\Openmake Software\DeployHub\WebAdmin\tomcat\webapps\dmadminweb\WEB-INF\web.xml.  Then delete  C:\Program Files\Openmake Software\DeployHub\WebAdmin\tomcat\webapps\dmadminweb.  Followed by unzipping the .war into a new  C:\Program Files\Openmake Software\DeployHub\WebAdmin\tomcat\webapps\dmadminweb directory.  Finally, put your web.xml file back and restart the service.

Thanks, Steve
