### ISSUE TITLE
remotescript command not working

### ISSUE THREAD

**Issue by alanromo** [ortelius/ortelius#33]
Hi 
I have a component with a postaction invoking this function :
-----------------------
echo "Running script on end point ${server.name}";
echo "before executing /home/MyDirectory/MyChmod.ksh";
remotescript(filepath: "/home/MyDirectory/MyChmod.ksh");
echo "exit status is $?";
return 0;
------------------------
When I see the execution log I see:

Running script on end point az70
before executing /home/MyDirectory/MyChmod.ksh
exit status is 0

But the script never is executed in the end point
am I missing something?
I have tried invoking a none existing remote script as well and I always get an rc= 0
Is there a way to at least get an rc <> 0 and know it is failing when trying to execute the remote script?

**Comment by pgibbs-openmake** [comment]
Hi, sorry for the delay in replying. I presume the target machine is Unix/Linux?
1) Could you confirm that the component is being delivered to the target machine (in other words, the Component Type mapping is correct to the end point)
2) The target server type is set correctly.
3) If you open the deployment log after the deployment completes and check the "Reports" tab, is the Remote Script listed as a Deployment Step?

**Comment by alanromo** [comment]
Yes, the target machine is Linux
1. The component files are being delivered correctly
2. The target server type is ...End Point type: unix, End Point component types: application File
3. Yes it is listed there

![image](https://user-images.githubusercontent.com/26904911/40250563-4a65a1be-5a9c-11e8-80f6-49bf44173d08.png)
![image](https://user-images.githubusercontent.com/26904911/40250640-85c3a422-5a9c-11e8-9f56-334aa9cae586.png)
![image](https://user-images.githubusercontent.com/26904911/40250679-aac4a668-5a9c-11e8-89b2-61768c488876.png)
![image](https://user-images.githubusercontent.com/26904911/40250733-ddc3f87a-5a9c-11e8-8cf5-53a52340f444.png)
![image](https://user-images.githubusercontent.com/26904911/40250808-0fe8d348-5a9d-11e8-9df6-0c1acad8f7f5.png)

**Comment by pgibbs-openmake** [comment]
I see that the transfer protocol is FTP ... running commands remotely over FTP is only supported by a small number of FTP Servers. I'm not sure Linux is one of them.

Now, clearly that should be reporting a failure rather than returning 0 - we can certainly look at that with a view to sorting out a fix. In the meantime, can you change the transfer protocol to SFTP? I assume your remote Linux server is running SSH?

**Comment by alanromo** [comment]
Thanks a lot, changing to sftp the protocol at the end point solved the issue
