### ISSUE TITLE
Documentation: The architecture image is for DeployHub for 'Processing'

### ISSUE THREAD

**Issue by TracyRagan** [ortelius/ortelius#333]
We need to replace the image for the processing flow image. https://docs.ortelius.io/guides/userguide/concepts/processing/

**Comment by jayesh-srivastava** [comment]
Hi, can you please clarify with which image the existing image needs to be replaced?

**Comment by TracyRagan** [comment]
On this page https://docs.ortelius.io/guides/userguide/concepts/processing/  It is the bottom one. The flow is wrong. We don't have a 'release' in Ortelius, and it says DeployHub.  The logic of the flow is not making sense either.  You can find the original, created in powerpoint here: https://docs.google.com/presentation/d/1uudTYvoM5XHtMg71sOUoychsAf39dJn4jLu1hep7jC0/edit#slide=id.p

**Comment by jayesh-srivastava** [comment]
Okay I understood. Should a new image be created or we have to use any other image?

**Comment by sbtaylor15** [comment]
Need to update the image to state Ortelius instead of DeployHub and create a new .png that can be inserted into the doc.
