### ISSUE TITLE
documentation: Why Use Ortelius

### ISSUE THREAD

**Issue by boucains** [ortelius/ortelius#336]
Under Agentless Delivery:

"Ubantu, Redhat, SuSe, Debina" should be "Ubuntu, Redhat, SuSe, Debian"

**Comment by Arvind644** [comment]
@sbtaylor15 I want to work on this issue

**Comment by sbtaylor15** [comment]
@Arvind644  Fork the [ortelius/ortelius-docs](https://github.com/ortelius/ortelius-docs) repo, install hugo and the markdown plugins for VS Code and you should be set to start making changes.  See [setup-for-documenation-updates](https://docs.ortelius.io/guides/contributorguide/how-to/#setup-for-documenation-updates)

**Comment by Arvind644** [comment]
@sbtaylor15 I have setup hugo and markdown for contributing to docs

**Comment by Arvind644** [comment]
somebody already correct the issues discuss above before. I think now we can close this issue
