### ISSUE TITLE
No domains in the GUI

### ISSUE THREAD

**Issue by alanromo** [ortelius/ortelius#34]
Hello,
Suddenly the domains tree disappeared from the GUI.
All the options in the main menu stopped showing any action .
I uninstalled DeployHub and resinstalled it many times expecting to get back its functionality, but the result is always the same.
I'm working on Windows 10
Any idea where the problem can be ?

**Comment by sbtaylor15** [comment]
Can you send a screenshot of the domain tree?

**Comment by pgibbs-openmake** [comment]
Just checking - do you get the login screen but the domain tree is missing after you login? I'm wondering if the database has an issue (reinstalling the app will not remove the database schema since that's how we do upgrades). If you can login successfully then it sounds like the database itself is functioning okay.

Also, just double-checking that you're logging in with an "admin" account? Does the same issue occur with any other account?

There are three log files worthy of note:
C:\Program Files\Openmake Software\DeployHub\install.log
C:\Program Files\Openmake Software\DeployHub\WebAdmin\log\deployhub.log
C:\Program Files\Openmake Software\DeployHub\PostgreSQL\log\logfile.txt

Could you add these files to this issue log and we can see if anything stands out?

Cheers,

P.

**Comment by alanromo** [comment]
Since the problem started, DeployHub GUI shows up without asking any id/password. It just simply shows up without presenting the domains tree. The main menu options don't do anything.
I took a look to the logs you mentioned and I can see a java exception in the deployHub.log file... I don't know if that is the issue. I'm attaching files
Thanks in advance for your help.
![image](https://user-images.githubusercontent.com/26904911/40621779-e802bb68-6263-11e8-807e-b4b766250547.png)
[install.log](https://github.com/DeployHubProject/DeployHub/files/2045580/install.log)
[deployhub.log](https://github.com/DeployHubProject/DeployHub/files/2045581/deployhub.log)

**Comment by sbtaylor15** [comment]
Can you go into pgAdmin and backup the database and send us the backup?

1. Open the database in pgAdmin.
2. Navigate to the "dm" schema
3. Right click and select Backup...
4. Put in a file name for the backup and then run the backup

**Comment by alanromo** [comment]
Well, I already had deleted the dm schema expecting to have a clean installation from zero
But the result is the same. When I install it back there in no functionality at all,
Is it worth to send you the dm schema anyway ? As far as I can see it only contains the default and demo values)

**Comment by sbtaylor15** [comment]
Yes, send me the dm schema.  I want to verify that all of the tables are created correctly.

**Comment by alanromo** [comment]
Here the dm schema backup
I put it in plain format 
[dmSchema.txt](https://github.com/DeployHubProject/DeployHub/files/2059220/dmSchema.txt)

**Comment by alanromo** [comment]
I have uninstalled and reinstalled the tool many times expecting to see it working again. But sometimes I see the following message.... perhaps it could help
![image](https://user-images.githubusercontent.com/26904911/40847900-35ce1988-6583-11e8-8fc0-53ef74b0b6f8.png)

**Comment by sbtaylor15** [comment]
Have you rebooted between installs?  The service may not be uninstalled correctly.

**Comment by alanromo** [comment]
Yes. every time

**Comment by sbtaylor15** [comment]
Can we do a web meeting to get this sorted out?  If so, send your contact info to: steve@deployhub.com

**Comment by sbtaylor15** [comment]
Did you get it working?

**Comment by alanromo** [comment]
No, I feel like I ran out of ideas. I stopped trying.

**Comment by sbtaylor15** [comment]
I would like to do a web meeting to take a look at your installation.  I looked at the database dump and it looks good.  I think it may be an issue with the database connection.

**Comment by sbtaylor15** [comment]
Determined that the expanded war file is missing .js files.  Attached is the war file that contains the missing .js.  

[dmadminweb.war.zip](https://github.com/DeployHubProject/DeployHub/files/2411938/dmadminweb.war.zip)

The war file goes in <install>/webadmin/libs.  Replacing the existing dmadminweb.war file.  Restart of the DeployHubWeb Services or reboot is needed of the file is in place.

**Comment by sbtaylor15** [comment]
Reworked UI to remove tree views.
