### ISSUE TITLE
GitOps: Implement Argo Http sensor

### ISSUE THREAD

**Issue by bradmccoydev** [ortelius/ortelius#346]
Implement the Argo Http sensor so that we can receive a payload post-deployment.

This is to be done in Golang or Python.

https://argoproj.github.io/argo-events/sensors/triggers/http-trigger/

Must have a helm chart, and be deployed into the Ortelius AKS cluster.

**Comment by ayesha-kr** [comment]
@bradmccoydev @sbtaylor15 Can i take this up? 
If yes then would be great to get some background

**Comment by bradmccoydev** [comment]
Hi @ayesha-kr sure, have you worked with Argo before?

**Comment by ayesha-kr** [comment]
Hi @bradmccoydev worked on kubernetes and app development.  Had lead a project that use Argo. 
So not hands on argo myself,  but know the concept. 
Shouldnt be a problem. 
Anything specific that i need to swiftly readup on?

**Comment by bradmccoydev** [comment]
hey @ayesha-kr lets catchup? https://calendly.com/bradmccoydev/15min

**Comment by shahkv95** [comment]
hey @bradmccoydev 
wanted to check with you if the issue is still open and if solving it will add value to the project.
if so, could you brief me a bit about it, and probably I can work on it thereafter?
Thank you!

**Comment by quassainraza** [comment]
@bradmccoydev  would it be better if I just write code for http sensor.?

**Comment by bradmccoydev** [comment]
hi sorry we dont need this anymore thanks, closing issue
