### ISSUE TITLE
Create swagger doc and API for rendering it for flask microservices

### ISSUE THREAD

**Issue by karamjotsingh** [ortelius/ortelius#347]
Code Repos : 
[ortelius-ms-dep-pkg-cud](https://github.com/ortelius/ortelius-ms-dep-pkg-cud)
[ortelius-ms-compitem-crud](https://github.com/ortelius/ortelius-ms-compitem-crud)
[ortelius-ms-textfile-crud](https://github.com/ortelius/ortelius-ms-textfile-crud)
[ortelius-ms-validate-user](https://github.com/ortelius/ortelius-ms-validate-user)
[ortelius-ms-dep-pkg-r](https://github.com/ortelius/ortelius-ms-dep-pkg-r)

1. Create API documentation through swagger doc as per OpenApi Specification.
2. Create an API endpoint to render the swagger API doc.

**Comment by sbtaylor15** [comment]
https://github.com/ortelius/ortelius-ms-dep-pkg-cud/pull/8

**Comment by sbtaylor15** [comment]
Added into component microsevices in svc_cat branch
