### ISSUE TITLE
Implement db connection pool for flask microservices

### ISSUE THREAD

**Issue by karamjotsingh** [ortelius/ortelius#348]
Code Repos : 
[ortelius-ms-dep-pkg-cud](https://github.com/ortelius/ortelius-ms-dep-pkg-cud)
[ortelius-ms-compitem-crud](https://github.com/ortelius/ortelius-ms-compitem-crud)
[ortelius-ms-textfile-crud](https://github.com/ortelius/ortelius-ms-textfile-crud)
[ortelius-ms-validate-user](https://github.com/ortelius/ortelius-ms-validate-user)
[ortelius-ms-dep-pkg-r](https://github.com/ortelius/ortelius-ms-dep-pkg-r)

Implement a connection pool for database connetions.

**Comment by sbtaylor15** [comment]
https://github.com/ortelius/ortelius-ms-dep-pkg-cud/pull/8

**Comment by sbtaylor15** [comment]
Added into component microsevices in svc_cat branch
