### ISSUE TITLE
Implement health check API for flask microservices

### ISSUE THREAD

**Issue by karamjotsingh** [ortelius/ortelius#349]
Code Repos : 
[ms-dep-pkg-cud](https://github.com/ortelius/ms-dep-pkg-cud)
[ms-compitem-crud](https://github.com/ortelius/ms-compitem-crud)
[ms-textfile-crud](https://github.com/ortelius/ms-textfile-crud)
[ms-validate-user](https://github.com/ortelius/ms-validate-user)
[ms-dep-pkg-r](https://github.com/ortelius/ms-dep-pkg-r)
[ms-scorecard](https://github.com/ortelius/ms-scorecard)

Implement API to provide the health status for the microservice.

**Comment by sbtaylor15** [comment]
https://github.com/ortelius/ortelius-ms-dep-pkg-cud/pull/8
