### ISSUE TITLE
Runtime error: Pattern is required for http repository

### ISSUE THREAD

**Issue by ramapokuri** [ortelius/ortelius#35]
Hi,
 I am trying to set up my project in deployhub with jenkins. I have done jenkins set up in deployhub for example Application103 and enviornment 103 and configured all seeting in Jenkins job configuration page and when i run the build it is throwing the below error 

**Runtime error: Pattern is required for http repository
18:22:57 
18:22:57 Stacktrace:
18:22:57 	repository Repository104
18:22:57 	dropzone 1
18:22:57 	deploy 
18:22:57 	component Component105
18:22:57 	application Application104
18:22:57 	avloop
18:22:57 	application Application104
18:22:57 	environment Environment104
18:22:57 	global
18:22:57 
18:22:57 INFO: Time taken 0.172000 seconds
18:22:57 IO Exception: java.lang.UnsupportedOperationException: Refusing to marshal net.sf.json.JSONObject for security reasons; see https://jenkins.io/redirect/class-filter/
18:22:57 Build step 'DeployHub Interface' marked build as failure
18:22:57 Finished: FAILURE**

Please can you advise what went wrong, I want deploy the .net webapp folder to target folder not single file .

**Comment by sbtaylor15** [comment]
The http repository for the Component Item is missing the "pattern" parameter.  Update the pattern entry field for the Component Item.   The Component Item will be part of the Component Version that is being updated by Jenkins.

**Comment by ramapokuri** [comment]
i am new to deployhub can u please explain more how to do this

**Comment by sbtaylor15** [comment]
Are you using the DeployHub Plugin for Jenkins?

**Comment by ramapokuri** [comment]
Yes iam using deployhub plugin for jenkins

**Comment by ramapokuri** [comment]
today again i started the with from scratch and giving the same issue, 


**INFO: Starting deployment #137
--
INFO: Deploying Application "testapp" into Environment "testenv"
INFO: Deploying Component testcomp
Failed to open  for logging
Runtime error: Pattern is required for http repository
Stacktrace:    repository testrepo    dropzone 1    deploy     component iseekcomp    application iseekapp    avloop    application testapp    environment testenv    global
INFO: Time taken 0.281000 seconds**

**Comment by sbtaylor15** [comment]
Here is a screen shot of a Jenkins Repository definition:

![image](https://user-images.githubusercontent.com/14826572/41013265-7e543156-6902-11e8-8c1c-1ba1a9fd2134.png)

And a screenshot of the Component Item definition for the "pattern" to use:

![image](https://user-images.githubusercontent.com/14826572/41013220-49c4c612-6902-11e8-9d2a-39fe843771c3.png)

Also, did you define a Build Engine and link the Build Job to the Component?  The Build Engine is the link to have Jenkins update information into DeployHub.

**Comment by ramapokuri** [comment]
thanks , I will try and let you know the results, I am building the .net code , i want deploy webapp folder to target folder , so can i mention 'webapp' in pattern section , please advise

**Comment by sbtaylor15** [comment]
So the example I gave was to pickup the .war file that is being archived against the Jenkins Job.  Where are you archiving your files to?  Or are you just leaving them on the file system under the jobs directory for Jenkins?

**Comment by ramapokuri** [comment]
i am just leaving  my archiving files in Jenkins work space

**Comment by sbtaylor15** [comment]
If DeployHub is installed on the same machine as Jenkins or if the Jenkins machine is Windows then we can use a file system repository.  Can you let me know more about your setup?

**Comment by ramapokuri** [comment]
![capture](https://user-images.githubusercontent.com/39910994/41098328-96150fbe-6a78-11e8-8adc-755ced6d2d9e.PNG)
I am using file system repository and getting some errors. please advise , i will give provide my set up details

**Comment by ramapokuri** [comment]
![capture1](https://user-images.githubusercontent.com/39910994/41100930-40c0aebc-6a80-11e8-8323-476e46f95ae1.PNG)

here is my component details name is dotnetcomp

**Comment by ramapokuri** [comment]
![capture2](https://user-images.githubusercontent.com/39910994/41101011-867baed4-6a80-11e8-87ca-498633c84c45.PNG)
here is my build engine

**Comment by ramapokuri** [comment]
![capture4](https://user-images.githubusercontent.com/39910994/41101202-20833a88-6a81-11e8-90c6-7c0594923f06.PNG)

here is my environment end point details base directory i have givenas my target folder  i have given E://BitBucket

**Comment by ramapokuri** [comment]
here is my file system repo 

![capture5](https://user-images.githubusercontent.com/39910994/41101257-4c40b51a-6a81-11e8-92fa-9e54ad72219d.PNG)

**Comment by ramapokuri** [comment]
file path i haven given is my source direcotry i mean jenkins artifactory files

**Comment by ramapokuri** [comment]
please can you advise what went wrong here is

**Comment by ramapokuri** [comment]
INFO: Starting deployment #154
--
INFO: Deploying Application "dotnetapplication" into Environment "dotnetenv"
INFO: Deploying Component dotnetcomp
INFO: Item "dotnet": Checked out 0 file(s) from repository "dotnetrepo"
INFO: Deploying Component dotnetcomp to Server dotnetend
No error
Exception at line 0: dmtransfer did not execute successfully
Stacktrace:    server dotnetend    dropzone 1    deploy     component dotnetcomp    application dotnetapplication    avloop    application dotnetapplication    environment dotnetenv    global
INFO: Time taken 0.421000 seconds

**Comment by sbtaylor15** [comment]
It looks like the pattern entry field is missing on the Component Item screen.  Let me do some investigation.

**Comment by sbtaylor15** [comment]
Goto the dotnetrepo repository -> Properties Tab and delete the following properties:  pattern, recursive and version.

Next, go back to your Component and edit the dotnet component item.  Add *.* in for the pattern.
Run the deployment again and let me know the results.

**Comment by ramapokuri** [comment]
I did the same , but getting the same error

**Comment by ramapokuri** [comment]
It is working for me now, i just mentioned *.* with recursive mode so it is deployed now. But How can i give the file path as environment variable but here i think i am hard coded my Jenkins work space path .

**Comment by sbtaylor15** [comment]
You can put variables in the filepath.  For example:   c:\jenkins\${workspace}\webapp

The "workspace" variable would be defined as an Attribute to the Component.   Here is a screen shot that defines environment variables.

![image](https://user-images.githubusercontent.com/14826572/41163440-e3e715ac-6af5-11e8-98a2-745e2758c457.png)

**Comment by ramapokuri** [comment]
Thanks Steve, Aha but there is one problem i am facing since few days regarding DeployHub jenkins plugin. 

Jenkins Job is failing but deployment gone through well and Jenkins job is throwing below error

**12:04:38 Time Elapsed 00:00:09.33
12:04:40 Archiving artifacts
12:06:13 Logged in to DeployHub as user admin
12:06:16 Deploying application dotnetapplication11 to environment dotnetenv1
12:06:19 Deployment #161 started
12:06:19 IO Exception: java.lang.UnsupportedOperationException: Refusing to marshal net.sf.json.JSONObject for security reasons; see https://jenkins.io/redirect/class-filter/
12:06:19 Build step 'DeployHub Interface' marked build as failure
12:06:20 Finished: FAILURE** 

But i see deployment successful. I did some work around for this issue as i noticed that the problem with DeployHub plugin for Jenkins. I uninstall deployhub plugin in jenkins and ran the job and it was successfully and again i installed DeployHub plugin and ran the job it has failed due to the above error. Please can you advise .

**Comment by ramapokuri** [comment]
My jenkins version is 2.107.3 and DeployHub 8.0.1

**Comment by sbtaylor15** [comment]
Does this happen when you run the deployment from DeployHub directly instead of through the Jenkins plugin?  Trying to figure out what is throwing that exception.

Thanks, Steve

**Comment by sbtaylor15** [comment]
Also, are you using the DeployHub Groovy Library to do the deployment from a pipeline?

**Comment by sbtaylor15** [comment]
DeployHub 8.0.10 is the latest version of the plugin.  Can you install that version?

https://plugins.jenkins.io/deployhub

**Comment by ramapokuri** [comment]
Does this happen when you run the deployment from DeployHub directly instead of through the Jenkins plugin? Trying to figure out what is throwing that exception.  - i just installed deployhub plugin which is available in Jenkins manage plugin page

**Comment by ramapokuri** [comment]
Also, are you using the DeployHub Groovy Library to do the deployment from a pipeline? - no i am not using DeployHub Groovy library, how can i do this , please can you advise

**Comment by ramapokuri** [comment]
Hi Steve, I have installed Deployhub plugin 8.0.10 And still it is giving the same error  error .12:06:19 IO Exception: java.lang.UnsupportedOperationException: Refusing to marshal net.sf.json.JSONObject for security reasons; see https://jenkins.io/redirect/class-filter/
12:06:19 Build step 'DeployHub Interface' marked build as failure
12:06:20 Finished: FAILURE

**Comment by ramapokuri** [comment]
How can i add the DeployHub Groovy library in jenkins / DeployHub , Please advise

**Comment by ramapokuri** [comment]
Hi Steve, Can you please advise the above one

**Comment by sbtaylor15** [comment]
![image](https://user-images.githubusercontent.com/14826572/41568710-74dcc5bc-7324-11e8-97e5-dcffa871afd4.png)

Here is a screen shot of adding the library to Jenkins.  The library gets pulled from GitHub

**Comment by ramapokuri** [comment]
thanks, But my build server no internet connectivity , so what i did is i just cloned Master branch to my Bit Bucket server and mentioned in Gloabl library section but still it is giving "IO Exception: java.lang.UnsupportedOperationException: Refusing to marshal net.sf.json.JSONObject for security reasons; see https://jenkins.io/redirect/class-filter/" same error and i have installed groovy 2.5.0 also in my build server. please find my screen shot

**Comment by ramapokuri** [comment]
![capture6](https://user-images.githubusercontent.com/39910994/41660524-ef6816c4-74b9-11e8-9369-06df75545dc1.PNG)

**Comment by ramapokuri** [comment]
![capture7](https://user-images.githubusercontent.com/39910994/41660599-2b48c60c-74ba-11e8-96e7-55a9eb5eab3c.PNG)

**Comment by sbtaylor15** [comment]
Does Jenkins print a full stack trace for either the DeployHub plugin or the DeployHub Groovy library?  

I have the latest version of Jenkins install and not getting the error that you are seeing.

Thanks, Steve

**Comment by sbtaylor15** [comment]
There is a new plugin available [8.0.13](https://repo.jenkins-ci.org/releases/com/openmake/deployhub/8.0.13/) that removes all dependencies on net.sf.json.JSONObject.   Give that one a try and let me know the results.

Thanks Steve

**Comment by ramapokuri** [comment]
Thanks Steve, Now it is giving some error, 
"Logged in to DeployHub as user admin
Deploying application dotnetapplication1123 to environment Env1234
Could not find appropriate deploy task
Build step 'DeployHub Interface' marked build as failure
Finished: FAILURE"

**Comment by ramapokuri** [comment]
I am using 8.0.10 Deploy Hub OSS version.

**Comment by ramapokuri** [comment]
![app](https://user-images.githubusercontent.com/39910994/41908422-87ae10d6-7961-11e8-9648-56ccd2e856a9.PNG)

**Comment by ramapokuri** [comment]
![comp](https://user-images.githubusercontent.com/39910994/41908433-91a21ccc-7961-11e8-938d-87652ab889d5.PNG)

**Comment by ramapokuri** [comment]
![env](https://user-images.githubusercontent.com/39910994/41908445-a0aaeae6-7961-11e8-95ff-ac5f42ac31c7.PNG)

**Comment by ramapokuri** [comment]
![repo](https://user-images.githubusercontent.com/39910994/41908463-ae374c18-7961-11e8-927d-6b3df52a5316.PNG)

**Comment by ramapokuri** [comment]
Please can you advise what went wrong here

**Comment by ramapokuri** [comment]
![conf](https://user-images.githubusercontent.com/39910994/41908660-65df3786-7962-11e8-9765-bb408914209a.PNG)

**Comment by ramapokuri** [comment]
![deploy](https://user-images.githubusercontent.com/39910994/41909220-1b589d2c-7964-11e8-9d19-79c46d6b9fa2.PNG)

**Comment by sbtaylor15** [comment]
Go to the Domains menu which will bring up the Domains Tree View on the left.  Expand My Pipeline and select the "Testing" node.  The right hand panel should show the Tasks defined for that stage of the pipeline.  Can you send a screen shot of those tasks?  I think a Deploy task may be missing for Testing stage of the pipeline.

Thanks, Steve

**Comment by ramapokuri** [comment]
Sure i will test it , can you diff between Pro and OSS version of deployhub, in feature we may think about go for enterprise

**Comment by sbtaylor15** [comment]
Here is the [comparison table](https://www.deployhub.com/deployhub-pro-vs-deployhub-oss/).  Let me know if you need more details.

Thanks, Steve

**Comment by sbtaylor15** [comment]
Also, in the Pro version your enhancement requests and bug fixes are prioritized over the OSS.

**Comment by ramapokuri** [comment]
Hi Steve, I have created Add Deploy Task names "test1" but where i can mention this task for deployment. 
Here is my set up, This is worked for me Few days ago with out deploy task, 
Component 
====
![comp1](https://user-images.githubusercontent.com/39910994/41963756-02a42870-7a16-11e8-8273-f00a01decf9d.PNG)
![comp2](https://user-images.githubusercontent.com/39910994/41963757-02f2441a-7a16-11e8-9ca6-aa5c8a9f9717.PNG)

**Comment by ramapokuri** [comment]
Application set up 
![app1](https://user-images.githubusercontent.com/39910994/41963789-1380a632-7a16-11e8-92fb-0943d8f97e2f.PNG)
![app2](https://user-images.githubusercontent.com/39910994/41963790-13fbfe9a-7a16-11e8-8e29-f0e2db828d81.PNG)

**Comment by ramapokuri** [comment]
Env Details 

![env1](https://user-images.githubusercontent.com/39910994/41963819-26af0eba-7a16-11e8-82c9-447261c5e6f8.PNG)

**Comment by ramapokuri** [comment]
Repo details

**Comment by ramapokuri** [comment]
![repo](https://user-images.githubusercontent.com/39910994/41963859-3de2d198-7a16-11e8-9138-0736fe44be7e.PNG)
![Uploading repo12.PNG…]()

**Comment by ramapokuri** [comment]
![Uploading repo.PNG…]()

**Comment by ramapokuri** [comment]
I just created deploy task test1 , abd ran again it is giving saem error, could not find deploy task, where i can mention this to understand the jenkins and deployhub 
![domain](https://user-images.githubusercontent.com/39910994/41963970-7cd8dc58-7a16-11e8-9961-b756c61a7879.PNG)

**Comment by ramapokuri** [comment]
![conf](https://user-images.githubusercontent.com/39910994/41964169-fb1543ea-7a16-11e8-826f-0022c43a782b.PNG)


this is my jenkins config details

**Comment by sbtaylor15** [comment]
A Deploy Task is needed for each stage of the pipeline.  We have this requirement in order to setup different security levels for the different stages.  The deploy task that will be used is derived based on where the application version is in pipeline.  

As for your error, make sure there is a Deploy Task is defined for each stage of the pipeline.  Also, you need to assign the right Group Access.  In the screen shot for the "test1" task there is no Group Access defined. 

Double check everything by performing a deployment from the DeployHub UI then give a go from Jenkins.

Thanks, Steve

**Comment by ramapokuri** [comment]
Thanks , it is working now , Great. again thanks a lot for your advise and inputs

**Comment by ramapokuri** [comment]
How to do roll back if something wrong through deployhub

**Comment by sbtaylor15** [comment]
Wrong in what way?  You want to rollback a deployment or you changed some data in the UI and want to roll it back.

Thanks, Steve

**Comment by ramapokuri** [comment]
for example deployment 130 has been pushed to dev server. i want to roll back deployment 130.

**Comment by sbtaylor15** [comment]
To do a roll back and roll forwards you need to use Component Versions and Application Versions.

1. Goto your base version of your Component, then Versions Tab.
2. Right click and create a new Component Version
3. Edit the new Component Version's Component item.  This should point to the new version of the artifact file.
4. Add a Create Version Task to Development Pipeline from the Domains tree view -> General Tab
5. Goto your base Application and right click to choose the new Create Version task
6. Edit the new Application Version and update Component Versions to include the new Component Version created above.  (Not all components versions have to be updated for a new Application Version, only the ones that have changed since last deployment)
7. Now deploy the Application Version that you would like to have in the environment.  DeployHub will figure out if it is a rollback or roll forward.

You will need to have at the minimum the Base Application Version, Application Version 1 and Application Version 2 in place in order to roll forward or back.   Also, you can have as many versions you would like.  Here is video of the rollback/roll forward process:  https://www.youtube.com/watch?v=vQoZcMcqCeM&t=135s

Let me know if you need help on any of the steps.  

Thanks, Steve
