### ISSUE TITLE
Documentation - Need to document the new Install process for Ortelius version 10 (Service Catalog)

### ISSUE THREAD

**Issue by TracyRagan** [ortelius/ortelius#354]
Ortelius is now using microservices which change the install process. The new architecture and install process needs to be updated. This needs to be included in the install documentation, and a blog written.

**Comment by nishantminerva** [comment]
Hello @TracyRagan I am new here, Can you help me? - just tell me what I have to do.

**Comment by TracyRagan** [comment]
Updated in doc
https://docs.ortelius.io/guides/userguide/installation-and-support/0-on-premise-installation-for-pro/
