### ISSUE TITLE
Create DNS record for ortelius DevOps Cluster

### ISSUE THREAD

**Issue by bradmccoydev** [ortelius/ortelius#359]
The Ortelius DevOps cluster is used by the GitOps working group to use ArgoCD etc and requires a custom DNS record.

Steps: 
1. @sbtaylor15 decide on name eg devops.ortelius.com whatever the CDF have as a domain.
2. Give to @bradmccoydev and he makes txt record validation record
3. @bradmccoydev gives record to @sbtaylor15 then we send to CDF with CNAME of the domain pointing to ortelius.z01.azurefd.net (our Azure Front Door)

**Comment by sbtaylor15** [comment]
Here is the page to ask for DNS changes.  Just use CDF for the project name and ortelius.io for the domain name.

https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2

**Comment by bradmccoydev** [comment]
keptn.ortelius.io ticket created: https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/IT-22914

**Comment by bradmccoydev** [comment]
argocd.ortelius.io created https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/IT-22915

**Comment by bradmccoydev** [comment]
This is now complete and confirmed.
