### ISSUE TITLE
Error: Could not find library ftplib.dll

### ISSUE THREAD

**Issue by ajhd** [ortelius/ortelius#36]
I'm trying to deploy a simple text file from "ftprep" type repository, but I got the following:

INFO: Starting deployment #152
INFO: Deploying Application "MyApp" into Environment "MyEnv"
INFO: Deploying Component MyComponent
Runtime error: Could not find library ftplib.dll
INFO: Time taken 0.010000 seconds

Can someone help me to resolve this?

I'm using the Linux DeployHub Open Source (OSS Latest version)

Thanks in advance!

**Comment by sbtaylor15** [comment]
What OS is your end-point running?  
Thanks, Steve

**Comment by ajhd** [comment]
Linux

**Comment by sbtaylor15** [comment]
The best way to go is to use sftp, which supports ssh.  You will need to create a credential for that end point.  The credential can be userid/password combo or public/private key.  

sftp will enable commands to be run pre and post deployment on the end point.  Regular ftp does not allow for any command execution.  

![image](https://user-images.githubusercontent.com/14826572/45903477-1daf0e80-bda7-11e8-808d-834a7fa0a2ad.png)

![image](https://user-images.githubusercontent.com/14826572/45903503-2c95c100-bda7-11e8-97c3-4fe6523d3de6.png)

**Comment by ajhd** [comment]
I don't have any problem with my End-point my settings are like your images with protocol = sftp and ssh port number = 22, and I also created a credential with my external userid and password.
I think the problem is with the repository, because I already did a test. I transferred a file from my local machine to this same End-Point and it was successful, but when I tried from an external repository using ftprep instead of filesystem, I got that error.

**Comment by sbtaylor15** [comment]
Ok, got it.  I thought the problem was on the end point side.  Let me check on the repository side.

Thanks, Steve

**Comment by ajhd** [comment]
Sure, Thank you! = D

**Comment by sbtaylor15** [comment]
I was able to recreate the issue.  Let me debug it to figure out what is going on.

**Comment by sbtaylor15** [comment]
Removed ftp support.  Use sftp instead.
