### ISSUE TITLE
Create GitHub Token for argo to access ortelius repos

### ISSUE THREAD

**Issue by bradmccoydev** [ortelius/ortelius#361]
Create GitHub Token for argo cd to access Ortelius repos

**Comment by sbtaylor15** [comment]
@bradmccoydev looks like you are an admin at the ortelius org level.  Try creating a token and see what you run into

**Comment by bradmccoydev** [comment]
Hey @sbtaylor15 yes I can this ticket is just for auditing and heads up to get approval from you. I will proceed today and document
