### ISSUE TITLE
Idle connection closed by server in python microservices

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#367]
Need to recover from a closed connection.

```
10.244.0.111:36494 - "GET /msapi/deppkg?deptype=license&compid=106&_=1632753114902 HTTP/1.1" 401
Exception during reset or similar
Traceback (most recent call last):
  File "/app/main.py", line 142, in getCompPkgDeps
    cursor.execute(sql, params)
psycopg2.OperationalError: SSL SYSCALL error: EOF detected


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 682, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 887, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 667, in do_rollback
    dbapi_connection.rollback()
psycopg2.InterfaceError: connection already closed
SSL SYSCALL error: EOF detected

```

**Comment by sbtaylor15** [comment]
I think we need to tell sqlalchemy to cleanup and retry when we get an psycopg2.OperationalError.  Perhaps adding, pool_pre_ping=True to the engine creation may help.

**Comment by karamjotsingh** [comment]
https://docs.sqlalchemy.org/en/14/core/pooling.html#dealing-with-disconnects

sqlalchemy handles disconnects well on its own and will handle the invalidation of existing connections and re-establishing new connections. 

pool_pre_ping can be used as an extra step before executing our queries, similar to 'SELECT 1', making sure that the connection is good.

The application can decide whether to retry the transaction or abandon it completely, during a disconnect scenario.

**Comment by codeWithUtkarsh** [comment]
implement connection retry in case of failure for these repos, hence closing this issue.
ortelius/ortelius-ms-compitem-crud, 
ortelius/ortelius-ms-textfile-crud, 
ortelius/ortelius-ms-dep-pkg-cud , 
ortelius/ortelius-ms-dep-pkg-r , 
ortelius/ortelius-ms-validate-user.
