### ISSUE TITLE
installing: create shell script to pull helm charts and install into k8s

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#373]
Need a shell script that can pull the helm charts from the poly repos and then perform a helm upgrade to k8s.  We should be able to run this `curl -sSL https://ortelius.io/install | sh`  where install is the full shell script.

**Comment by sbtaylor15** [comment]
Should pull helm charts from artifacthub.io.  The charts should include a main chart that includes the sub charts.
See #377

**Comment by sbtaylor15** [comment]
Steps to install from artifacthub.io (something like this):

1.  helm repo add --force-update ortelius https://ortelius.io
2. helm update
2. helm upgrade --install ortelius-release ortelius

Need parent and child charts.

**Comment by sbtaylor15** [comment]
Looks like we need to host our charts from our hugo server https://ortelius.io or GitHub Pages.  See https://helm.sh/docs/topics/chart_repository/

**Comment by bradmccoydev** [comment]
@benhpoh

**Comment by AshishKmrSingh** [comment]
Hello. Please add me.

**Comment by sachajw** [comment]
Ashish already has experience in solving this issue, so I will work with Ashish on this issue.

**Comment by AshishKmrSingh** [comment]
Hey @sbtaylor15 @sachajw 

There is a GitHub action 'helm-chart-releaser' for this in place already. The point that we discussed about how we are going collect different helm charts to work together and collect them as a single artifact, the functionality for that is already there. 
This action will combine these charts and create a zip artifact updating the gh-pages branch->index.yml file of the ortelius repo. Infact, it will also host our repo as a helm chart repo. So, we do not even need to create a separate helm chart repo. I verified that the Github Pages is already hosted for ortelius repo and that is our helm repo. 

Now, the work related to this ticket. We only need shell script which can supply the environment variables and then deploy it as helm install. 
This took a while to understand this. Didn't know that a lot of the surrounding work is already implemented, which has reduced the size of this ticket to a minimum. I will be working on the actual part now i.e. the script for this.

P.S: This is the first time I have seen Github Action working. That loose coupling of the helm repo with the code base is awesome. My TRYST with Open Source.

**Comment by sachajw** [comment]
Excellent @AshishKmrSingh and thank you very much!

**Comment by sachajw** [comment]
I have this so far 
apiVersion: v2
name: Ortelius
description: A Parent Helm chart for Ortelius
type: application
version: 0.1.0
appVersion: 0.1.0

dependencies:
  - name: dh-ms-ui
    version: 0.1.0
    repository: "@ms-ui"
  - name: ortelius-console
    version: 0.1.0
    repository: "@ortelius-console"

**Comment by sbtaylor15** [comment]
completed
