### ISSUE TITLE
uploading helm charts for applications to artifacthub.io

### ISSUE THREAD

**Issue by karamjotsingh** [ortelius/ortelius#377]
Need to upload helm charts for Ortelius repo and each of the microservices repo onto https://artifacthub.io/.

**Comment by sbtaylor15** [comment]
@Ujwal90210 and @karamjotsingh - touch base with each other on this so we don't duplicate work.

**Comment by sbtaylor15** [comment]
@bradmccoydev, @Checksumz, @Ujwal90210, @karamjotsingh  
@guna-interaslabs 
### Charts locations:

- [ortelius](https://github.com/ortelius/ortelius/tree/svc_cat) **svc_cat** branch
  - chart/ms-general
  - chart/ms-ui
  - chart/ms-nginx
- [ortelius-ms-dep-pkg-cud](https://github.com/ortelius/ortelius-ms-dep-pkg-cud/tree/deploy) **deploy** branch
   - chart/ms-dep-pkg-cud
- [ortelius-ms-dep-pkg-r](https://github.com/ortelius/ortelius-ms-dep-pkg-r/tree/deploy)  **deploy** branch
   - chart/ms-dep-pkg-r
- [ortelius-ms-textfile-crud](https://github.com/ortelius/ortelius-ms-textfile-crud/tree/deploy)  **deploy** branch
   -   chart/ms-textfile-crud
- [ortelius-ms-compitem-crud](https://github.com/ortelius/ortelius-ms-compitem-crud/tree/deploy)  **deploy** branch
   - chart/ms-compitem-crud
- [ortelius-ms-validate-user](https://github.com/ortelius/ortelius-ms-validate-user/tree/deploy)  **deploy** branch
   - chart/ms-validate-user

**Comment by sbtaylor15** [comment]
Need a driver helm chart that includes the child ones so a single helm upgrade command can be run to install everything into k8s

**Comment by bradmccoydev** [comment]
This will be great to have them on Artifact hub!

**Comment by sbtaylor15** [comment]
Looks like we need to host our charts from our hugo server https://ortelius.io or GitHub Pages. See https://helm.sh/docs/topics/chart_repository/.

Then you link our repo over to artifacthub.io

**Comment by bradmccoydev** [comment]
Hi is there any insight on when this ticket will be done, it relates to my work

**Comment by bradmccoydev** [comment]
@benhpoh

**Comment by benhpoh** [comment]
Using helm-chart-releaser (https://github.com/helm/chart-releaser-action), we can automate the `helm package` and `helm repo index` steps.

This creates new releases (in the Ortelius Github repo) whenever any changes are made to the charts, and the index.yaml is updated.

Once Artifact Hub is linked to the Ortelius GitHub page, it will automatically get the latest versions of any charts

**Comment by bradmccoydev** [comment]
This has been done, closing issue. Thanks folks
