### ISSUE TITLE
Add missing values to ortelius/chart/ms-nginx/templates/deployment.yaml

### ISSUE THREAD

**Issue by bradmccoydev** [ortelius/ortelius#392]
Add missing values to ortelius/chart/ms-nginx/templates/deployment.yaml
Image pull policy is missing in this wierd looking values.yaml file.

Steps:
1. get latest changes to your ortelius repo 
2. look at the ortelius/chart/ms-nginx/templates and match with the values file to see if anything is missing
3. Study basic Helm if you need to
4. image pull policy can be IfNotPresent for now

hint:

image:
  pullPolicy: IfNotPresent

Learning: https://kubernetes.io/docs/concepts/containers/images/

**Comment by bradmccoydev** [comment]
@ayesha-kr this could be a good one for you

**Comment by Arvind644** [comment]
It may be ortelius/chart/ms-ui/templates/deployment.yaml as after chart only ms-ui and ortelius-console is showing

**Comment by bradmccoydev** [comment]
Forgot to mention deploy branch

**Comment by Arvind644** [comment]
It didn't have any deploy branch

**Comment by bradmccoydev** [comment]
Sorry I mean cat_sec or svc_cat

**Comment by Arvind644** [comment]
Got it. Thank you for helping me
