### ISSUE TITLE
Merge svc_cat helm chart into main for source of truth

### ISSUE THREAD

**Issue by bradmccoydev** [ortelius/ortelius#396]
Repo: ortelius/ortelius repo

Merge svc_cat helm chart into main for the source of truth as we will be producing release artifacts to host charts on Artifact Hub.

This will have to be done for the other Repos we want to host on the artifact hub.

**Comment by sbtaylor15** [comment]
We need to keep the svc_cat branch around so we can support the current version which is on main and the new version that is on svc_cat.
