### ISSUE TITLE
Add chart-releaser-action GitHub Action to microservice repos

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#401]
https://github.com/ortelius/ortelius/blob/svc_cat/.github/workflows/helm-chart-releaser.yml needs to be added to the following repos with the additional parameter **charts_repo_url** set to **https://ortelius.github.io/ortelius**:

- [ortelius-ms-dep-pkg-cud](https://github.com/ortelius/ortelius-ms-dep-pkg-cud/tree/deploy) **deploy** branch
   - chart/ms-dep-pkg-cud
- [ortelius-ms-dep-pkg-r](https://github.com/ortelius/ortelius-ms-dep-pkg-r/tree/deploy)  **deploy** branch
   - chart/ms-dep-pkg-r
- [ortelius-ms-textfile-crud](https://github.com/ortelius/ortelius-ms-textfile-crud/tree/deploy)  **deploy** branch
   -   chart/ms-textfile-crud
- [ortelius-ms-compitem-crud](https://github.com/ortelius/ortelius-ms-compitem-crud/tree/deploy)  **deploy** branch
   - chart/ms-compitem-crud
- [ortelius-ms-validate-user](https://github.com/ortelius/ortelius-ms-validate-user/tree/deploy)  **deploy** branch
   - chart/ms-validate-user

**Comment by benhpoh** [comment]
PR for:
ortelius-ms-dep-pkg-cud deploy branch - https://github.com/ortelius/ortelius-ms-dep-pkg-cud/pull/15
ortelius-ms-dep-pkg-r deploy branch - https://github.com/ortelius/ortelius-ms-dep-pkg-r/pull/9

**Comment by benhpoh** [comment]
PR for:
ortelius-ms-textfile-crud - [ortelius/ortelius-ms-dep-pkg-cud#15](https://github.com/ortelius/ortelius-ms-textfile-crud/pull/10)
ortelius-ms-compitem-crud - [ortelius/ortelius-ms-dep-pkg-r#9](https://github.com/ortelius/ortelius-ms-compitem-crud/pull/11)

**Comment by benhpoh** [comment]
ortelius-ms-validate-user completed

**Comment by bradmccoydev** [comment]
This has been done, closing issue
