### ISSUE TITLE
Cloudbuild: add application version to microservices

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#402]
Need to add COMPONENT_APPLICATION_VERSION:

args: ['-c', 'env | sed "s/^/export /" >> /workspace/cloudbuild-general.sh']
volumes:
\- name: 'ssh'
  path: /root/.ssh
env: 
  \- 'COMPONENT_APPLICATION=GLOBAL.ortelius.saas.ortelius-devops'
  **\- 'COMPONENT_APPLICATION_VERSION=10.0.0'**

and add the parameter to dh cli:

/workspace/cloudbuild-general.sh;dh updatecomp --dhurl https://console.deployhub.com --appname "$$COMPONENT_APPLICATION" **--appversion "$$COMPONENT_APPLICATION_VERSION"**

**Comment by Arvind644** [comment]
In which file we have to make these changes

**Comment by sbtaylor15** [comment]
The file is in /cloudbuild/cloudbuild.yaml for each of the microservices.  See #401 for the list of those repos and branches.  Make sure to do the PR against the deploy branch and not main.

**Comment by Arvind644** [comment]
svc_cat is the deploy branch, right ?

**Comment by sbtaylor15** [comment]
Correct

**Comment by sbtaylor15** [comment]
removed cloudbuild for GH Actions
