### ISSUE TITLE
ms-nginx config - server_name needs to change from dev.ortelius.io to _

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#403]
[nginx.conf](https://github.com/ortelius/ortelius/blob/svc_cat/dmadminweb/microservice/nginx.conf) needs server_name changed to _ on line 117 and 125

**Comment by xguhx** [comment]
This issue still open?
Can I work on it?
Thank you so much.

**Comment by Ujwal90210** [comment]
Working on it, in an hour or so
