### ISSUE TITLE
Status check to endpoint failing

### ISSUE THREAD

**Issue by piyush94** [ortelius/ortelius#41]
I am running via docker container.
After adding the end point status check is failing:
![image](https://user-images.githubusercontent.com/11614204/54737729-4c336800-4bd7-11e9-9a05-196d74c1cd73.png)

But if TTY into the container i am able to issue ping to the endpoint.

**Comment by sbtaylor15** [comment]
Which docker container did you download, the OSS or Pro version?

**Comment by sbtaylor15** [comment]
Also, what is the end point type, windows or linux?

**Comment by piyush94** [comment]
I used this image quay.io/ortelius/ortelius. Is this correct for OSS?
Endpoint is a linux RHEL vm.

**Comment by sbtaylor15** [comment]
Go ahead and download the latest container image.  We had found a similar issue in the Pro version that was fixed but not pulled into the OSS version.  I pulled the changes into OSS.  Also, the .ssh keys will be accessible from /home/omreleng/.ssh/<private key name>.  They get copied from the host to /keys in the container and then into /home/omreleng/.ssh in the container.

Let me know the results.

**Comment by piyush94** [comment]
I took the latest image and it's still failing,
Though i had found a workaround, when i run the docker container like this:
`docker run -u root <rest_of_command>`
then i am not facing this issue.

**Comment by piyush94** [comment]
Another issue has popped up after updating to latest image, base directory check is failing.
![image](https://user-images.githubusercontent.com/11614204/54804412-54ec7280-4c99-11e9-9949-0ffc5da064c6.png)

**Comment by sbtaylor15** [comment]
What type of credential are you using to access the remote end point?   I tested my side with a public/private key credential and it was successful.  Send me a screen shot of the end point definition (ie general tab).

**Comment by piyush94** [comment]
I am using a username/password based login. The VM is in a private cloud and is accessible from inside the container.

**Comment by sbtaylor15** [comment]
What was the result that you were getting when you ran the docker container without -u root?  Also, is your docker daemon running as root or a different userid?

**Comment by piyush94** [comment]
Without -u root all the status checks are failing.
Docker daemon is running as root.

**Comment by sbtaylor15** [comment]
I will need to debug why -u root is needed on a web meeting on your machine since I cannot recreate it.

**Comment by sbtaylor15** [comment]
Updated the Status check to show the underlying OS error.  Please pull the latest mage.  

docker pull quay.io/ortelius/ortelius

**Comment by piyush94** [comment]
Error:
`Base directory "/opt" is invalid or inaccessible /opt/deployhub/engine/lib/sshexec: line 84: //.ssh/known_hosts.unique: No such file or directory
/opt/deployhub/engine/lib/sshexec: line 85: //.ssh/known_hosts: No such file or directory
cat: //.ssh/known_hosts: No such file or directory
/opt/deployhub/engine/lib/sshexec: line 88: //.ssh/known_hosts.unique: No such file or directory
/opt/deployhub/engine/lib/sshexec: line 89: //.ssh/known_hosts: No such file or directory
grep: //.ssh/known_hosts: No such file or directory
/opt/deployhub/engine/lib/sshexec: line 97: //.ssh/known_hosts.unique: No such file or directory
/opt/deployhub/engine/lib/sshexec: line 98: //.ssh/known_hosts: No such file or directory
Could not create directory '/.ssh'. `

**Comment by piyush94** [comment]
Hi, issue has been fixed by reinstalling Docker.

**Comment by sbtaylor15** [comment]
Do you still need to pass with -u root after reinstalling Docker?

**Comment by piyush94** [comment]
No, not required anymore.
