### ISSUE TITLE
Create repo for helm charts

### ISSUE THREAD

**Issue by benhpoh** [ortelius/ortelius#418]
We currently have charts spread across a number of repos:
- ortelius
- ortelius-ms-dep-pkg-cud 
- ortelius-ms-dep-pkg-r
- ortelius-ms-textfile-crud
- ortelius-ms-compitem-crud
- ortelius-ms-validate-user

This should be consolidated into a single index.yaml to be uploaded onto ArtifactHub.

**Comment by benhpoh** [comment]
Charts are to be hosted in the following repo: https://github.com/ortelius/ortelius-charts

**Comment by bradmccoydev** [comment]
this has been done, closing
