### ISSUE TITLE
Add endpoint to deploy action

### ISSUE THREAD

**Issue by piyush94** [ortelius/ortelius#42]
I have create a new action of category deploy.
`action DoMongoDBInstall
{
  deploy(repository: "GlobalRepo", path: @'software', pattern: "installers/mongodb-linux-x86_64-rhel70-3.6.3.tgz");
  deploy(repository: "GlobalRepo", path: @'software', pattern: "scripts/ase/mongodb-install.sh");
  ExecMongoDBInstall;
  return;
}`

And i am running this task like this:
![image](https://user-images.githubusercontent.com/11614204/55073900-eeaa8a00-50b4-11e9-8872-7541d9ccf3eb.png)
and then:
![image](https://user-images.githubusercontent.com/11614204/55073926-01bd5a00-50b5-11e9-8200-b6cf1d7870b1.png)

But it is not asking for endpoint where to run.

**Comment by sbtaylor15** [comment]
What is the ExecMongoDBInstall?  Can you send me the details on it?

**Comment by piyush94** [comment]
It's a procedure to execute the shell script on the endpoint.

**Comment by sbtaylor15** [comment]
Ok, got it.  Make an Action (ExecMongoDBInstallAction) to call the ExecMongoDBInstall procedure.  Then for your application version add the MongoDB component first in the layout, then the MongoDB Install Script component.  

Make sure the MongoDB component has no pre/post/custom actions assigned.  For the MongoDB Install Script component set pre and custom actions to blank and post action to ExecMongoDBInstallAction.  

The DoMongoDBInstall task and action are not needed.   

DeployHub will send out the MongoDB tar file first to the end point, then send the install sh to the end point.  The post action on the MongoDB Install Script component will get executed after everything is on the end point.

An application is assigned to and environment and that environment has end points (servers) defined to it.  You will deploy the application to an environment and that is how DeployHub know which end points are being deployed to.

Send me the log output if you run into issues.

**Comment by piyush94** [comment]
Yes, this way we are able to push the files and execute the script. But wanted to know if it's possible by creating custom actions. Is it not possible?

**Comment by sbtaylor15** [comment]
What you initially setup will execute a custom action but its outside the context of environments and servers.  You need to tie the custom action to a component so it has a context to work within.  

See the following link for details on the deployment logic.  

https://www.deployhub.com/helpdh/NetHelp/DeploymentProcessing.html

**Comment by sbtaylor15** [comment]
FYI, custom actions at the component level are used for components that require an alternate method of delivery, such as REST Post (Salesforce and IBM Data Power work this way).

**Comment by piyush94** [comment]
Is there a way to just run some commands on an endpoint through application action without deploying anything?

**Comment by sbtaylor15** [comment]
There is no direct way to do that.   There is a work around in which you create a component with no component items in it.  Then associate what you want to run to the components custom action.   The component will need to be associated to an application.  Running the Deploy Task against the application will in turn run the components custom action.
