### ISSUE TITLE
Add Readme to Helm Charts for better presentation in ArtifactHub

### ISSUE THREAD

**Issue by bradmccoydev** [ortelius/ortelius#431]
Now that we have our helm charts on Artifact hub we need to make them more presentable. If we have a readme.md file then that will come up in artifacthub. See below the example. And reach out to @bradmccoydev if you need help

Example: 
Repo: https://github.com/direktiv/direktiv-charts/tree/main/charts/direktiv
Artifact Hub: https://artifacthub.io/packages/helm/direktiv/direktiv

cc: @benhpoh

**Comment by Aju100** [comment]
@bradmccoydev can you share helm chart name and docs I would like to work on this issue

**Comment by bradmccoydev** [comment]
@benhpoh can you recommend a repo for @Aju100 please

**Comment by benhpoh** [comment]
Hey @Aju100 , give this repo a shot - https://github.com/ortelius/ortelius-ms-dep-pkg-cud

The helm chart sits in the deploy branch under /chart/ms-dep-pkg-cud/
https://github.com/ortelius/ortelius-ms-dep-pkg-cud/tree/deploy/chart/ms-dep-pkg-cud

**Comment by Aju100** [comment]
@bradmccoydev  @benhpoh well, I didn't find the helm chart artifact ? Can you provide the resources for it so I document the guide to install helm chart of ms-dep-pkg-cud
