### ISSUE TITLE
CookieCutter or similar integration to create backend pieces for a new microservice

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#432]
How can we leverage [CookieCutter](https://github.com/cookiecutter/cookiecutter) or similar to on-board a new microservice creating the information in Ortelius as well as the backend pieces (git repo, skeleton code, test cases, CI/CD).

**Comment by scanalesespinoza** [comment]
Analisis between CoockieCutter and Devfiles

CoockieCutter has a masive and active community to support his usage, on the other hand Devfile looks less masive but stronger in his design, lets comparate it in the following table:

|Features| CookieCutter | Devfile |
| ------ | ------ | ------ |
|Kind of tool| CLI | IDE/CICD/AUTOMATION Tool |
|File type| Json | Yaml |
|API| Missing | Present |
|IDE Integration| Missing | Present |
|Contributors| 247 | 5 |
|Operator| Missing | Present |
|Kubernetes Integration| Missing | Present |
|Registry| Missing | Present |
|Template Stack| Decentralized | Centralized/Decentralized |

References:
https://devfile.io/docs/devfile/2.1.0/user-guide/index.html
https://github.com/cookiecutter/cookiecutter

**Comment by scanalesespinoza** [comment]
@sbtaylor15 I think Devfile is a more standarized solution as my conclusion, any comments?  let me know if enought to close the issue

**Comment by scanalesespinoza** [comment]
Closing with comparation as output and aceptance criteria
