### ISSUE TITLE
Add CycloneDX SBOM to ortelius-ms-dep-pkg-cud

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#434]
As part of the Google Cloud Build we need to generate the SBOM/SPDX files and store them somewhere for reference.  https://github.com/opensbom-generator/spdx-sbom-generator

**Comment by sbtaylor15** [comment]
Add sytf to our cloubbuild.yaml to produde the Cyclonedx SBOM.

**Comment by sbtaylor15** [comment]
We need to update the cloudbuild.yaml to run https://github.com/anchore/syft after the docker build has been completed. Syft should scan the docker image and produce a cyclone-dx json file.  The cyclone-dx json file should be uploaded using the existing `dh updatecomp` command line call. This upload is done by adding the `--deppkg 'cyclonedx@/workspace/cyclonedx.json'` to the `dh updatecomp` parameters.

Update need for microservice  - [ortelius-ms-dep-pkg-cud](https://github.com/ortelius/ortelius-ms-dep-pkg-cud)

**Comment by hamidgholami** [comment]
Hi @sbtaylor15,
I have committed the changes in deploy branch.
https://github.com/ortelius/ortelius-ms-dep-pkg-cud/commit/029a64aec80caaf3ad0cb4d5066815a8e1d293de
