### ISSUE TITLE
Need to bump npm dependencies to fix audit issues

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#438]
package.json for [ortelius/website](https://github.com/ortelius/website) and [ortelius/ortelius-docs](https://github.com/ortelius/ortelius-docs) need to be updated to use latest versions of the npm modules.  

  "autoprefixer": "^10.4.2",
    "postcss-cli": "^9.1.0"

**Comment by shimmyt** [comment]
@Aju100 seems to have fixed this, and this issue should be closed.
