### ISSUE TITLE
Microservices are having security issues reported on artifactory.io 

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#439]
Need to figure out why we have an F score.  https://artifacthub.io/packages/search?ts_query_web=ortelius&sort=relevance&page=1

![image](https://user-images.githubusercontent.com/14826572/149194469-f1aa932c-df21-4469-988f-6efb651c1b59.png)

**Comment by karamjotsingh** [comment]
![image](https://user-images.githubusercontent.com/17989443/151222256-3c31979e-3bd9-4b7f-8c5d-fb98dc50d16b.png)

Done for the following microservices:
[ortelius-ms-compitem-crud](https://github.com/ortelius/ortelius-ms-compitem-crud)
[ortelius-ms-dep-pkg-cud](https://github.com/ortelius/ortelius-ms-dep-pkg-cud)
[ortelius-ms-dep-pkg-r](https://github.com/ortelius/ortelius-ms-dep-pkg-r)
[ortelius-ms-textfile-crud](https://github.com/ortelius/ortelius-ms-textfile-crud)
[ortelius-ms-validate-user](https://github.com/ortelius/ortelius-ms-validate-user)
