### ISSUE TITLE
credentials not working

### ISSUE THREAD

**Issue by piyush94** [ortelius/ortelius#44]
credentials not working.
endpoint connect fails.

new verion:
![image](https://user-images.githubusercontent.com/11614204/57504243-59d0b880-7311-11e9-89aa-6e5de73a3639.png)

old version:
![image](https://user-images.githubusercontent.com/11614204/57504251-6228f380-7311-11e9-8d45-9c837c3550e8.png)

**Comment by piyush94** [comment]
![image](https://user-images.githubusercontent.com/11614204/57504277-7bca3b00-7311-11e9-8312-71a6245fc509.png)

**Comment by sbtaylor15** [comment]
What type of credential are you using, encrypted in db, private key etc?  Send a screen shot of editing the credential.

**Comment by piyush94** [comment]
![image](https://user-images.githubusercontent.com/11614204/57597096-8f70de00-756b-11e9-8dc0-0730cbcbfaf7.png)

**Comment by piyush94** [comment]
I suspect username is not getting stored correctly because after clicking edit username is not prefilled even it is saved earlier.

**Comment by sbtaylor15** [comment]
The encryption of the userid and password are done by the deployment engine.  I think this maybe related to #45.
