### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by anupamgogoi0907** [ortelius/ortelius#442]
Hi Team,

In the link, https://ortelius.io/contributor/, the below link is broken.

![image](https://user-images.githubusercontent.com/21226874/150604767-aca83d21-9092-4975-9ebd-7323b1904e8b.png)

**Broken Link:** https://console.deployhub.com/dmadminweb/signup.html/

Thanks.

**Comment by syp1xd** [comment]
Can i take this up?

**Comment by TracyRagan** [comment]
Removed the Ortelius Sign-up. We currently do not have a hosted site.
