### ISSUE TITLE
NullPointerException on /dmadminweb/Home

### ISSUE THREAD

**Issue by tishan18927** [ortelius/ortelius#444]
I am trying to install ortelius locally in my development enviornment. When I start the docker image as mentioned in the documentation I get the following error in the homepage.

> Type Exception Report
> 
> Description The server encountered an unexpected condition that prevented it from fulfilling the request.
> 
> Exception
> 
> java.lang.NullPointerException
> 	dmadmin.DMSession.getInstance(DMSession.java:473)
> 	dmadmin.HttpServletBase.internalHandleRequest(HttpServletBase.java:61)
> 	dmadmin.HttpServletBase.doGet(HttpServletBase.java:46)
> 	javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
> 	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
> Note The full stack trace of the root cause is available in the server logs.

Container logs are as follows.

> + DBLOCAL=
> + [[ '' == '' ]]
> + sudo chown -R postgres:postgres /var/lib/pgsql
> + sudo chmod -R 777 /opt/deployhub
> + pkill postgres
> + sudo test -f /var/lib/pgsql/data/pg_hba.conf
> + mkdir /tmp/data
> + sudo chown postgres:postgres /tmp/data
> + sudo -u postgres /usr/pgsql-10/bin/pg_ctl initdb --pgdata=/tmp/data
> sudo: /usr/pgsql-10/bin/pg_ctl: command not found
> + sudo cp -rp /tmp/data /var/lib/pgsql
> + sudo chown -R postgres:postgres /var/lib/pgsql
> + sudo chmod 700 /var/lib/pgsql/data
> + sudo grep -qxF 'host all all 0.0.0.0/0 trust' /var/lib/pgsql/data/pg_hba.conf
> grep: /var/lib/pgsql/data/pg_hba.conf: No such file or directory
> + sudo sed -i '$ a\host all all 0.0.0.0/0 trust' /var/lib/pgsql/data/pg_hba.conf
> sed: can't read /var/lib/pgsql/data/pg_hba.conf: No such file or directory
> + sudo grep -qxF 'listen_addresses = '\''*'\''' /var/lib/pgsql/data/postgresql.conf
> grep: /var/lib/pgsql/data/postgresql.conf: No such file or directory
> + sudo sed -i '$ a\listen_addresses = '\''*'\''' /var/lib/pgsql/data/postgresql.conf
> sed: can't read /var/lib/pgsql/data/postgresql.conf: No such file or directory
> + sudo -u postgres /usr/pgsql-10/bin/pg_ctl start --pgdata=/var/lib/pgsql/data
> sudo: /usr/pgsql-10/bin/pg_ctl: command not found
> + sleep 10
> + sudo -u postgres /usr/pgsql-10/bin/pg_ctl status --pgdata=/var/lib/pgsql/data
> sudo: /usr/pgsql-10/bin/pg_ctl: command not found
> + '[' '!' -e /opt/deployhub/logs ']'
> + sudo mkdir /opt/deployhub/logs
> + '[' '!' -e /opt/deployhub/engine ']'
> + sudo chmod -R 777 /opt/deployhub
> + sudo chown -R omreleng /opt/deployhub
> + cd /opt/deployhub/engine
> + export LD_LIBRARY_PATH=/opt/deployhub/engine/lib:/opt/deployhub/engine/bin
> + LD_LIBRARY_PATH=/opt/deployhub/engine/lib:/opt/deployhub/engine/bin
> + export PATH=/opt/deployhub/engine/lib:/opt/deployhub/engine/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/google-cloud-sdk/bin:/usr/pgsql-10/bin:/usr/local/google-cloud-sdk/bin
> + PATH=/opt/deployhub/engine/lib:/opt/deployhub/engine/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/google-cloud-sdk/bin:/usr/pgsql-10/bin:/usr/local/google-cloud-sdk/bin
> ++ cut -d: -f6
> +++ whoami
> ++ getent passwd omreleng
> + HOME=/home/omreleng
> + export HOME
> + sudo cp -r '/keys/*' /root/.ssh
> cp: cannot stat '/keys/*': No such file or directory
> + sudo chown -R root /root/.ssh
> + sudo chmod 755 /root/.ssh
> + '[' -e /root/.ssh/known_hosts ']'
> + cp -r '/keys/*' /home/omreleng/.ssh
> cp: cannot stat '/keys/*': Permission denied
> + chown -R omreleng /home/omreleng/.ssh
> + chmod 755 /home/omreleng/.ssh
> + chmod 600 /home/omreleng/.ssh/known_hosts
> chmod: cannot access '/home/omreleng/.ssh/known_hosts': No such file or directory
> + [[ '' == '' ]]
> + '[' '' == OFF ']'
> + sudo nginx
> nginx: [warn] could not build optimal types_hash, you should increase either types_hash_max_size: 1024 or types_hash_bucket_size: 64; ignoring types_hash_bucket_size
> + java -jar /opt/deployhub/webadmin/webapp-runner.jar --port 9191 --path /dmadminweb /opt/deployhub/webadmin/deployhub-webadmin.war
> + perl -pe '$_ = localtime.": $_"'

According to the logs some files and directories are not created properly.

I tried exec into the container and figured out there is no `/usr/pgsql-10/bin/pg_ctl` file available and there is a `/usr/pgsql-13/bin/pg_ctl` instead. 

Please help me to figure out the issue. I tried using `latest (c6fb89a92f5c 13 days ago)` image and `main-v9.0.0.468-gb376a52   (9abdec3e8bcf   7 weeks ago)` image for my setup. None of them worked.

**Comment by codeWithUtkarsh** [comment]
@tishan18927 The code is fixed, try using the latest ortelius image.
