### ISSUE TITLE
Change Code of Conduct to latest version

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#445]
Need to use this one - https://www.contributor-covenant.org/version/2/1/code_of_conduct/

Main repo ortelius/ortelius should have references to the code of conduct.  That needs to be updated along with any others in the repos.  We should use the special .git repo to consolidate this.

**Comment by Aju100** [comment]
Hey @sbtaylor15 can I work on this issue ?

**Comment by sbtaylor15** [comment]
@Aju100 - Let me provide more background on this.  The Code of Conduct that Ortelius uses is adopted from contributor-covenant.org.

https://www.contributor-covenant.org/version/2/1/code_of_conduct/ will be the starting point for the new Ortelius version.  The Ortelius Code of Conduct version number should be iterated and the email address should be changed to conduct@cd.foundation.

Let me know if you have any questions on this.

**Comment by Aju100** [comment]
Hi @sbtaylor15 , I have updated and changed the mail address too.
