### ISSUE TITLE
Timed out waiting for deployment to start Unhandled exception: Current user not set - can't deploy

### ISSUE THREAD

**Issue by piyush94** [ortelius/ortelius#45]
![image](https://user-images.githubusercontent.com/11614204/57609890-63feeb00-758d-11e9-9bea-359c76f80494.png)

**Comment by sbtaylor15** [comment]
Can you please restart the docker container and see if the issue still persists?

**Comment by piyush94** [comment]
Restarting the docker container didn't solve either issue #44 or this one.

**Comment by sbtaylor15** [comment]
Can we setup a web meeting to look at these issues?  I cannot recreate them from my side.

**Comment by piyush94** [comment]
I have scheduled a call for today for discussion.

**Comment by sbtaylor15** [comment]
The state of the database connection caused the issue.  Please pull the latest image that fixes the issue.

`docker pull quay.io/ortelius/ortelius`

**Comment by sbtaylor15** [comment]
This will fix #44 as well.

**Comment by piyush94** [comment]
Still i am facing the issue:
![image](https://user-images.githubusercontent.com/11614204/57905215-65812980-7893-11e9-935f-98e3aa2eaad9.png)

![image](https://user-images.githubusercontent.com/11614204/57905224-6ca83780-7893-11e9-9e90-134b73179a35.png)

![image](https://user-images.githubusercontent.com/11614204/57905242-76319f80-7893-11e9-89fa-acd8680ad41b.png)

![image](https://user-images.githubusercontent.com/11614204/57905257-834e8e80-7893-11e9-8684-6c3988351199.png)

**Comment by piyush94** [comment]
[deployhub-17-5-2019.log](https://github.com/ortelius/ortelius/files/3190011/deployhub-17-5-2019.log)

**Comment by sbtaylor15** [comment]
Looks like an intermittent segfault is happening.  Let me dig into the logs some more to see whats happening.

**Comment by sbtaylor15** [comment]
I figured out why the segfault was happening.  I added in a default value to fix the fault.  Please pull the latest image.

`docker pull quay.io/ortelius/ortelius`

**Comment by piyush94** [comment]
Thanks, it's working now.
