### ISSUE TITLE
Create DNS entry for prometheus.ortelius.io

### ISSUE THREAD

**Issue by bradmccoydev** [ortelius/ortelius#459]
Brad to create a DNS entry support ticket to route prometheus.ortelius.io to our Azure Front Door instance

CNAME Entry needs to go to prometheus.ortelius.io = ortelius.z01.azurefd.net
TXT entry _dnsauth.prometheus.ortelius.io = t04g4r5kbty0gr80mftyqbkpk6l8cqxr

old example https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/IT-22914

**Comment by bradmccoydev** [comment]
Ticket Created: https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/IT-23594

**Comment by TracyRagan** [comment]
@bradmccoydev can we close this yet?

**Comment by bradmccoydev** [comment]
yes thanks @TracyRagan closing now
