### ISSUE TITLE
Deploy to Kubernetes using Helm

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#46]
@piyush94 - I want to make sure we handle your use case for deploying using Helm.  What is your Kubernetes cluster running on, AWS, GKE?  I need to make sure the authentication happens correctly prior to running Helm.  Also, I am assuming that Triller is already configured.

Thanks, Steve

**Comment by piyush94** [comment]
Hi Steve,
Our Kubernetes cluster is running on On Premise VMWare VMs. And to manage Helm we have an instance of Harbor that stores the helm charts published from developer's local machine. We are not directly using helm cli to run/manage helm charts. So i think we are looking at something like taking Helm charts from Harbor registery and deploying them onto the Kubernetes cluster from Deployhub, Correct me if i am wrong.

Regards,
Piyush

**Comment by sbtaylor15** [comment]
Looks helm needs to be configured to use Harbor as the remote repo.  Using `helm add repo`  from there on out the `helm install` will pull the chart from the repo and execute it.  I will add into the DeployHub Helm Action to connect to Harbor.

Thanks, Steve

**Comment by piyush94** [comment]
Hi Steve,
Any update regarding this.
Regards, Piyush

**Comment by sbtaylor15** [comment]
We are testing out the changes for using `helm add repo` call to the process.

**Comment by sbtaylor15** [comment]
Please pull the latest image and then follow the instructions in the PDF.  The zip file contains the DeployHub procedures that you will need to import.  Thanks, Steve

[HelmProcedures.zip](https://github.com/ortelius/ortelius/files/3238240/HelmProcedures.zip)
[Helm Chart Action Setup and Usage.pdf](https://github.com/ortelius/ortelius/files/3238241/Helm.Chart.Action.Setup.and.Usage.pdf)

**Comment by piyush94** [comment]
Hi Steve,
I need some help and clarification regarding the steps in the pdf. Can we have a call today preferably or tomorrow for this,
Regards,
Piyush

**Comment by sbtaylor15** [comment]
I have a meeting first thing tomorrow at a customer site.  Can we do Wednesday instead?

Thanks, Steve

**Comment by piyush94** [comment]
I have scheduled a call for Wednesday.

Regards, Piyush

**Comment by sbtaylor15** [comment]
Hi @piyush94,

Let do another web meeting once your minikube security is sorted out.  I had my minikube messed up so I started over by running  `minikube delete` and then wipeout the `~/.minikube` directory.

Also, pull the latest image `docker pull quay.io/ortelius/ortelius:latest`.  I fixed the status check error you were running into.

Thanks, Steve

**Comment by sbtaylor15** [comment]
Helm 2 and Helm 3 are installed as part of the image.  Helm is called as part of the custom action for the component.
