### ISSUE TITLE
Add grafana.ortelius.io DNS Records

### ISSUE THREAD

**Issue by bradmccoydev** [ortelius/ortelius#460]
Brad to create a DNS entry support ticket to route grafana.ortelius.io to our Azure Front Door instance

CNAME Entry needs to go to grafana.ortelius.io = ortelius.z01.azurefd.net
TXT entry _dnsauth.grafana.ortelius.io = r246hb38hv4d37rycbwv7mq1svd56yp6

old example https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/IT-22914

**Comment by bradmccoydev** [comment]
https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/IT-23595

**Comment by TracyRagan** [comment]
@bradmccoydev can we close this issue?

**Comment by bradmccoydev** [comment]
yes closing now thanks @TracyRagan
