### ISSUE TITLE
Update component.toml, Dockerfile and cloudbuild.yaml for ortelius-ms-apphist-3d

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#468]
Use [ortelius/store-recommendationservice](https://github.com/ortelius/store-recommendationservice) as reference

**Comment by Arvind644** [comment]
@sbtaylor15 it has all the JavaScript code. Where to put the build file and which image to use for Dockerfile

**Comment by sbtaylor15** [comment]
removed hipster store sample
