### ISSUE TITLE
ArtifactHub showing F Grade due to CVEs

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#477]
Need to figure out where the CVEs are coming from and update either the docker files or the helm charts.  Artifacthub may be pointing to old image versions.  @karamjotsingh did work on the dockerfiles a while back.

**Comment by karamjotsingh** [comment]
Looking at the vulnerabilities on Artifacthub, these are new CVEs. 

The following change in [python base docker file](https://github.com/ortelius/ortelius/blob/main/docker/DockerfilePythonMSBase) might solve the CVEs. 

Replacing the line 
RUN apk add expat=2.4.3-r0;
with
RUN apk add expat=2.4.7-r0 libuuid=2.37.4-r0;

Need to create a new base image and update it in the charts.

**Comment by bradmccoydev** [comment]
If we are not using dependabot i highly recommend it for this. It will do small PR's itself to fix itself. and will remove security insights issues

**Comment by bradmccoydev** [comment]
or use distroless or wolfi

**Comment by sbtaylor15** [comment]
Used cgr.dev/chainguard/python,  cgr.dev/chainguard/jdk:latest, and python:3.10-alpine, eclipse-temurin:8-jdk-alpine base images.  The cgr.dev ones work great if you do not have additional packages (openssl) to install otherwise alpine is needed.

cgr.dev is based on wolfi.  Google distroless has vulnerabilities in the base image so they should not be used.
