### ISSUE TITLE
PRs workflow failing due to error in Trivy code scan

### ISSUE THREAD

**Issue by codeWithUtkarsh** [ortelius/ortelius#479]
Getting an error while running Trivy code scan on the PRs.

```
Incorrect Usage. flag provided but not defined: -timeout 
```

![image](https://user-images.githubusercontent.com/29374436/158459595-65c1e787-e30d-4a47-92c9-007d4fac709b.png)

**Comment by codeWithUtkarsh** [comment]
This issue is basically due to migration from "trivy" to "trivy image". Most of the options are not supported now for "trivy" command therefore we need to migrate to "trivy image" command.

Reference:  https://github.com/aquasecurity/trivy/discussions/1515

CC @sbtaylor15

**Comment by sbtaylor15** [comment]
Resolved #524
