### ISSUE TITLE
Add CycloneDX SBOM for ortelius/ortelius-ms-compitem-crud

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#480]
We need to update the cloudbuild.yaml to run https://github.com/anchore/syft after the docker build has been completed. Syft should scan the docker image and produce a cyclone-dx json file.  The cyclone-dx json file should be uploaded using the existing `dh updatecomp` command line call. This upload is done by adding the `--deppkg 'cyclonedx@/workspace/cyclonedx.json'` to the `dh updatecomp` parameters.

Update need for microservice  - [ortelius-ms-compitem-crud](https://github.com/ortelius/ortelius-ms-compitem-crud)

**Comment by shahkv95** [comment]
@sbtaylor15 is the issue fixed or are contributors still working on it? 
if not, I can take this issue?

**Comment by sbtaylor15** [comment]
completed
