### ISSUE TITLE
Add CycloneDX SBOM to ortelius-ms-textfile-crud

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#481]
We need to update the cloudbuild.yaml to run https://github.com/anchore/syft after the docker build has been completed. Syft should scan the docker image and produce a cyclone-dx json file.  The cyclone-dx json file should be uploaded using the existing `dh updatecomp` command line call. This upload is done by adding the `--deppkg 'cyclonedx@/workspace/cyclonedx.json'` to the `dh updatecomp` parameters.

Update need for microservice  - [ortelius-ms-textfile-crud](https://github.com/ortelius/ortelius-ms-textfile-crud)

**Comment by hamidgholami** [comment]
Hi @sbtaylor15,
I have committed the changes in deploy branch.
https://github.com/ortelius/ortelius-ms-textfile-crud/commit/adc234e6286cddca00e073b829cf8ffc27f7f202
