### ISSUE TITLE
Add CycloneDX SBOM to ortelius-ms-validate-user

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#482]
We need to update the cloudbuild.yaml to run https://github.com/anchore/syft after the docker build has been completed. Syft should scan the docker image and produce a cyclone-dx json file.  The cyclone-dx json file should be uploaded using the existing `dh updatecomp` command line call. This upload is done by adding the `--deppkg 'cyclonedx@/workspace/cyclonedx.json'` to the `dh updatecomp` parameters.

Update need for microservice  - [ortelius-ms-validate-user](https://github.com/ortelius/ortelius-ms-validate-user)

**Comment by hamidgholami** [comment]
Hi @sbtaylor15,
I have committed the changes in deploy branch.
https://github.com/ortelius/ortelius-ms-validate-user/commit/0c2c13ec76e55a742f2bca7947216471fd35b457
