### ISSUE TITLE
Add CycloneDX SBOM to ortelius-ms-dep-pkg-r

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#483]
We need to update the cloudbuild.yaml to run https://github.com/anchore/syft after the docker build has been completed. Syft should scan the docker image and produce a cyclone-dx json file.  The cyclone-dx json file should be uploaded using the existing `dh updatecomp` command line call. This upload is done by adding the `--deppkg 'cyclonedx@/workspace/cyclonedx.json'` to the `dh updatecomp` parameters.

Update need for microservice  - [ortelius-ms-dep-pkg-r](https://github.com/ortelius/ortelius-ms-dep-pkg-r)

**Comment by sbtaylor15** [comment]
Use ortelius/ortelius-ms-compitem-crud cloudbuild.yaml as an example

**Comment by hamidgholami** [comment]
Hi,
Thanks for your help. But I checked this file:
https://github.com/ortelius/ortelius-ms-compitem-crud/blob/main/cloudbuild/cloudbuild.yaml
And I don't find any section regarding "syft".
You mean this section?  "# Capture new component version in DeployHub"

**Comment by sbtaylor15** [comment]
@hamidgholami its on the 'deploy' branch in that repo.  About 3/4 way down in the cloudbuild.yaml file.  Sorry for the confusion.

**Comment by hamidgholami** [comment]
@sbtaylor15 I have committed on deploy branch.
https://github.com/ortelius/ortelius-ms-dep-pkg-r/commit/5d75fa05ad70adb32872373ce574b9c3f02a8398
Since it was my first PR. I would appreciate it if  you could check it and tell me if I'm wrong.
Also can we close this issue or not?
Thanks,
