### ISSUE TITLE
Add Application Table to base Application version

### ISSUE THREAD

**Issue by TracyRagan** [ortelius/ortelius#485]
Application versions need to be associated to the primary application list. The consolidate 'Applicaiton list' should only show the high-level application (base version). When you go into the 'Applicaiton base version'  it will show the list of all its 'versions'. This consolidates all data about a single application in one place.

**Comment by sbtaylor15** [comment]
Changed UI for Application Versions and Component Versions to act like GitHub Commits. Showing the latest version with button to see older versions.
