### ISSUE TITLE
Component version list moved to 'base version' view

### ISSUE THREAD

**Issue by TracyRagan** [ortelius/ortelius#486]
Component versions need to be associated to the primary component list. The consolidated 'Component list' should only show the high-level component (base version). When you go into the 'Component base version'  it will show the list of all its 'versions'. This consolidates all data about a single component in one place.

**Comment by sbtaylor15** [comment]
Changed UI for Application Versions and Component Versions to act like GitHub Commits. Showing the latest version with button to see older versions.
