### ISSUE TITLE
Use Azure Active Directory for user authentication

### ISSUE THREAD

**Issue by TracyRagan** [ortelius/ortelius#487]
Need to integrate with Azure's active directory for logging in.

**Comment by basiq-brad** [comment]
i can help with this if needed @codeWithUtkarsh

**Comment by bradmccoydev** [comment]
i can help with this is needed @codeWithUtkarsh

**Comment by codeWithUtkarsh** [comment]
This is done @bradmccoydev.  I forgot to close this. @sbtaylor15 Closing this issue as this was completed.
