### ISSUE TITLE
General Deploy Setup Description says "under under" for Environment

### ISSUE THREAD

**Issue by rightker** [ortelius/ortelius#5]
Setup view -> General Deploy Setup -> Next button -> Second bullet point says "An Environment represents a target for deployment and contains one or more End Points. Environments can be found under under the Data Center view."

**Comment by pgibbs-openmake** [comment]
Fixed and submitted to git for both Pro and OSS.

**Comment by rightker** [comment]
Downloaded latest, looks good. Closing this issue.
