### ISSUE TITLE
[DOCS] Ortelius Deploys Kube YAML

### ISSUE THREAD

**Issue by agardnerIT** [ortelius/ortelius#504]
Given the following YAML file, how would I set Ortelius up to deploy these components as an application?

```
https://raw.githubusercontent.com/cncf/podtato-head/main/delivery/kubectl/manifest.yaml
```

I have Ortelius running on localhost and have created the components for each body part and assigned to an application. How do I do the equivalent of `kubectl apply` or perhaps that isn't in Ortelius' remit?

<img width="531" alt="image" src="https://user-images.githubusercontent.com/26523841/161369426-46db263c-ecc5-4908-b1cd-d8ebf497e79b.png">

**Comment by sbtaylor15** [comment]
Ortelius used helm to deploy to Kubetnetes.  You will need a helm chart for each component.  The chart can reside in the got repo.  So you have each component in the same repo or separate repos (mono vs poly repos)
