### ISSUE TITLE
Starring repo triggers the Trivy Code Scan github action

### ISSUE THREAD

**Issue by mflanneryii** [ortelius/ortelius#509]
There appears to be a defect with your github action setup for Trivy code scanning such that merely starring the repo is enough to kick off a Trivy Scan _(which subsequently fails due to invalid commandline parameters for Trivy)_

**Comment by bradmccoydev** [comment]
Hi is this for the ortelius/ortelius repo?

**Comment by mflanneryii** [comment]
Yes. See https://github.com/ortelius/ortelius/actions/runs/2416643856 as an
example that was kicked off after I starred the repo.

**Comment by peRFectBeliever** [comment]
https://github.com/ortelius/ortelius/pull/523

**Comment by sbtaylor15** [comment]
Resolved #523
