### ISSUE TITLE
Create new badge in badgr for contributors first contribution

### ISSUE THREAD

**Issue by bradmccoydev** [ortelius/ortelius#516]
We are getting lots of new contributors to come to join Ortelius but keeping them sticky and actively contributing is a different story.  Having a badge for folks' first contribution will give them a sense of achievement and encourage them to do more.  It will also be good for Ortelius branding as they will share on Twitter etc and attract more folks to the project.

We also spoke at the last meeting about a new community role around some project management with new contributors that @sachajw was interested in.

**Comment by TracyRagan** [comment]
Done - I've also added Brad McCoy as an issuer.
