### ISSUE TITLE
Move documentation to Docsy

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#52]
Currently the documentation is in word doc and uses Doc2Help to convert to html pages.  Need to convert to markdown and use Docsy to serve up the pages.

**Comment by divya-mohan0209** [comment]
@sbtaylor15 I'd like to help with this!

**Comment by markjacksonfishing** [comment]
That would be awesome!

**Comment by sbtaylor15** [comment]
Created [ortelius/ortelius-docs](https://github.com/ortelius/ortelius-docs).  Need to setup permissions.

**Comment by sbtaylor15** [comment]
@divya-mohan0209 - initial load of the docs has been done in the [ortelius/ortelius-docs](https://github.com/ortelius/ortelius-docs) repo.  All set for you to dig in.

**Comment by organicit** [comment]
@divya-mohan0209 I was interested in helping out as well here.  Can you ping me in discord and so we can coordinate efforts?

**Comment by qemtrails** [comment]
@divya-mohan0209 can you ping me on the discord channel to coordinate?  I would like to help out with the docs as well.
