### ISSUE TITLE
Normalize CycloneDX SBOM json for NTF storage

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#528]
**8 <img src="https://user-images.githubusercontent.com/14826572/194954041-610ed1b8-5104-4d3d-b215-df978d19d6f9.png" width="30px" height="30px"> Bounty**

Need to normalize the SBOM data to eliminate storing redundant data.  See [Normalized vs Denormalized Data](https://www.youtube.com/watch?v=vRqzFBTgGJA).   The normalized and minimized data will be placed as an NFT into ntf.storage and referenced via the IPFS CID.

**Comment by peRFectBeliever** [comment]
We could use https://github.com/iakovmarkov/json-schema-normalizer to normalize  JSON data with schema present. do we want to integrate with any module?

**Comment by sbtaylor15** [comment]
@peRFectBeliever - here is some clarification on what we need.

# SBOM snippet - Transposed from:

```json
        {
            "description": "Composable command line interface toolkit",
            "hashes": [
                {
                    "alg": "MD5",
                    "content": "b4233221cacc473acd422a1d54ff4c41"
                },
                {
                    "alg": "SHA-256",
                    "content": "dacca89f4bfadd5de3d7489b7c8a566eee0d3676333fbb50030263894c38c0dc"
                }
            ],
            "licenses": [
                {
                    "license": {
                        "name": "BSD-3-Clause"
                    }
                }
            ],
            "modified": false,
            "name": "click",
            "publisher": "",
            "purl": "pkg:pypi/click@7.1.2",
            "type": "library",
            "version": "7.1.2"
        }
```

# Into multiple NFTs:

### Package Details NFT - ipfs://bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi
```json
{
  "description": "Composable command line interface toolkit",
  "modified": false,
  "name": "click",
  "publisher": "",
  "purl": "pkg:pypi/click@7.1.2",
  "type": "library",
  "version": "7.1.2",
  "hashes": [
    {
      "alg": "MD5",
      "content": "b4233221cacc473acd422a1d54ff4c41"
    },
    {
      "alg": "SHA-256",
      "content": "dacca89f4bfadd5de3d7489b7c8a566eee0d3676333fbb50030263894c38c0dc"
    }
  ]
}
```

### License NFT -  ipfs://bafybeigvgzoolc3drupxhlevdp2ugqcrbcsqfmcek2zxiw5wctk3xjpjwy

```json
{
  "shortid": "BSD-3-Clause",
  "fullname": "BSD 3-Clause 'New' or 'Revised' License",
  "definitionurl": "https://spdx.org/licenses/BSD-2-Clause.html"
}
```

### Package NFT - ipfs://f01701220c3c4733ec8affd06cf9e9ff50ffc6bcd2ec85a6170

```json
{
  "purl": "pkg:pypi/click@7.1.2",
  "details": "ipfs://bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi",
  "licenses": [
    "ipfs://bafybeigvgzoolc3drupxhlevdp2ugqcrbcsqfmcek2zxiw5wctk3xjpjwy"
  ]
}
```

This split will enable us to reuse the _License_ NFT and _Package Details_ NFT across multiple SBOMs and only store them once in ntf.storage.  The _Package_ NFT is where the sub NFTs are associated back together representing the original SBOM.

**Comment by codeWithUtkarsh** [comment]
@peRFectBeliever Just a suggestion. If possible do not use any third-party library unless it is required. I see a function can be written with the inbuild libraries to achieve this task.

**Comment by codeWithUtkarsh** [comment]
Assigning this to me since no update. @sbtaylor15
