### ISSUE TITLE
NodeJS to add/retrieve minimized json to/from nft.storage

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#531]
**4 <img src="https://user-images.githubusercontent.com/14826572/194954041-610ed1b8-5104-4d3d-b215-df978d19d6f9.png" width="30px" height="30px"> Bounty**

## Summary
Need to take an SBOM json, minimize it and store in nft.storage recording the IPFS CID.  Then take the IPFS CID and retrieve the SBOM json from nft.storage

## References
See [nft.storage developer setup](https://github.com/nftstorage/nft.storage/blob/main/DEVELOPMENT.md)
[Demo for using nft.storage](https://www.youtube.com/watch?v=IWv_m4JT_9k&list=PLJQ55Tj1hIVZi8N1e_dTodg816QzKc9SX&index=13)

Minimizing JSON in NodeJS #525
[Minimizing JSON data PR #5](https://github.com/ortelius/la-sbom-ledger/pull/5)

## Deliverable
Working program that will take an SBOM json, minimize it, add it to nft.storage, record the ISPF CID, retrieve the SBOM json using the IPFS CID and compare the minimized data to prove success.

**Comment by akshatKunwar** [comment]
Hi Team, I have registered for the Blockchain work group. I would like to work on this issue. @sbtaylor15 Can you please assign this issue to me? I am new to blockchain but I have some hands-on with javascript.
