### ISSUE TITLE
Update ArtifactHub with how to run

### ISSUE THREAD

**Issue by TracyRagan** [ortelius/ortelius#538]
We need to add to the instructions on ArtifactHub how to bring up Ortelius once it has been downloaded.

**Comment by TracyRagan** [comment]
Step 2 - Access Ortelius from your browser
Run the following command to find your IP address for the Ortelius URL.

kubectl get svc -n ortelius ms.nginx 
This will display the external IP address you need to run the URL.

Step 3 - Access the Ortelius URL and Login
Access the URL from the following address:

http://<External IP Address from above step>/dmadminweb/Home
To log in please use userId: admin and password: admin.

Note:
You can create your own Administrator UserID and remove the default userid and password.

**Comment by TracyRagan** [comment]
@sachajw Can you verify the new steps to bring up Ortleius once you have installed locally?

**Comment by sachajw** [comment]
For the local dev environment on a Kind cluster, the Terraform automation takes care of the following:
- Kind K8s cluster 
- Deploying Ortelius from the Helm Charts in Artifact Hub
-  Please refer to https://github.com/ortelius/dev-env-setup for more info
- For now, a port forward can be used until I can figure out the NodePort override for the ms-nginx microservice
- The better way is to override the NodePort with a fixed value and then add an extra port mapping to the Kind configuration in Terraform

Added this now to the readme 
### How to access Ortelius
- Use a port forward with kubectl to the ms-nginx microservice service
- `kubectl port-forward TYPE/NAME [options] LOCAL_PORT:REMOTE_PORT`
- kubectl port-forward help
```
kubectl port-forward -h
```
- 8080 represents the local port on your machine http://localhost:8080
```
kubectl port-forward svc/ms-nginx 8080:80 -n ortelius
```
- 8443 represents the local port on your machine http://localhost:8443
```
kubectl port-forward svc/ms-nginx 8443:443 -n ortelius
```

**Comment by TracyRagan** [comment]
Updated the [ortelius-charts](https://github.com/ortelius/ortelius-charts)/[charts](https://github.com/ortelius/ortelius-charts/tree/main/charts)/[ortelius](https://github.com/ortelius/ortelius-charts/tree/main/charts/ortelius)/README.md with access info. Should display in ArtifactHub now.
