### ISSUE TITLE
Documentation | Development Environment documentation clean-up

### ISSUE THREAD

**Issue by sachajw** [ortelius/ortelius#542]
Clean up the documentation | language | sentence structures | obsolete content
https://docs.ortelius.io/guides/contributorguide/dev-environment/

**Comment by TracyRagan** [comment]
@sachajw 
Is there more work to be done on this? Wondering if we can close.

**Comment by sachajw** [comment]
Hi Tracy,

I will take a look at the docs and update here. :-)
