### ISSUE TITLE
Transpose Application Version to JSON for NFT storage

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#552]
**160 <img src="https://user-images.githubusercontent.com/14826572/194954041-610ed1b8-5104-4d3d-b215-df978d19d6f9.png" width="30px" height="30px"> Bounty**

Take a application version and all of the associated information from the Postgres db and transpose to json for nft storage.  

Deliverable: This method will need to read the Postgres DB to retrieve the data for a application version, transpose it to json, store in nft storage, retrieve the nft and compare to ensure it is the same as the original one.

**Comment by TracyRagan** [comment]
Waiting on architecture doc finalization before assigning.

**Comment by sbtaylor15** [comment]
Closing at this time.  Starting from scratch to add data to ArangoDB and NTF Storage.  Will reopen if needed for customer migration.
