### ISSUE TITLE
Add Brad McCoy to community management for Ortelius Project in LFX Insights

### ISSUE THREAD

**Issue by bradmccoydev** [ortelius/ortelius#553]
Add Brad McCoy to community management for Ortelius Project in LFX Insights so I can see more contributor insights.

Now I get this error:
```
No Access
Sorry, you do not appear to have access to Community Management.
Please contact your community manager with any questions. Thank you.
```

Please add me so I can get insights and help grow the project

https://insights-v2.lfx.linuxfoundation.org/cdf-ortelius/community/project/people?cohort=new-and-promising

**Comment by sbtaylor15** [comment]
Sent email to Michelle @ LF to get Brad added.
