### ISSUE TITLE
Create Maintainer Group in Github

### ISSUE THREAD

**Issue by bradmccoydev** [ortelius/ortelius#557]
Now we only have a dev group in Github. This means some people (especially new people) have more permissions than they need.  At a minimum, we should create a Maintainer group so that only admins can have special permission.

Example: https://backstage.ortelius.io/catalog/default/group/dev

**Comment by sbtaylor15** [comment]
@bradmccoydev is there a way to use a maintainers file?

**Comment by sbtaylor15** [comment]
Need to document the user of CODEOWNERS and [peribolos.yaml](https://github.com/ortelius/.github/blob/main/peribolos.yaml)

**Comment by antriksh-9** [comment]
Hey @bradmccoydev @sbtaylor15  I want to work on this issue. 
But I am not able to get a clear approach of creating a group.
Can you help me with this?

**Comment by sbtaylor15** [comment]
@antriksh-9 checkout the [peribolos.yaml](https://github.com/ortelius/.github/blob/main/peribolos.yaml).  We have switch to managing the GH Access as code.  Let me know if we are missing anything.
