### ISSUE TITLE
Helm chart: DBConnectionString is invalid (secret pgcred is wrong)

### ISSUE THREAD

**Issue by agardnerIT** [ortelius/ortelius#567]
DBConnectionString is semi-hardcoded to `jdbc:pgsql://%s:%s/%s` where `%s` are: `$dbhost`, `$dbport` and `$dbname`.

This means that even though I pass:

```
helm upgrade --install \
-n ortelius --create-namespace \
ortelius https://github.com/ortelius/ortelius-charts/releases/download/ortelius-$ORTELIUS_VERSION/ortelius-$ORTELIUS_VERSION.tgz \
--set ms-nginx.ingress.nodePort=30000 \
--set ms-general.dbhost=ortelius-postgresql.ortelius.svc.cluster.local
```

The `pgcred` secret is set to:

```
$ ko get secret pgcred -oyaml
apiVersion: v1
data:
  DBConnectionString: amRiYzpwZ3NxbDovL29ydGVsaXVzLXBvc3RncmVzcWwub3J0ZWxpdXMuc3ZjLmNsdXN0ZXIubG9jYWw6NTQzMi9wb3N0Z3Jlcw==
  DBHost: b3J0ZWxpdXMtcG9zdGdyZXNxbC5vcnRlbGl1cy5zdmMuY2x1c3Rlci5sb2NhbA==
  DBName: cG9zdGdyZXM=
  DBPassword: cG9zdGdyZXM=
  DBPort: NTQzMg==
  DBUserName: cG9zdGdyZXM=
```

`base64` decoding the `DBConnectionString` shows: `jdbc:pgsql://ortelius-postgresql.ortelius.svc.cluster.local:5432/postgres` where I believe it should be: `jdbc:postgresql://ortelius-postgresql.ortelius.svc.cluster.local:5432/postgres`.

The `ms-general` pod reads the secret value but the `ms-ui` pod formats it correctly (as per the latter, "full" connection string.

`ms-ui` uses (what I believe to be) the correct string: `jdbc:postgresql://ortelius-postgresql.ortelius.svc.cluster.local:5432/postgres`

**Comment by sbtaylor15** [comment]
Fixed in commit [e20607c01c](https://github.com/ortelius/ortelius/commit/e20607c01cbe6e44ca127e68b2a0a108584c95b8)
