### ISSUE TITLE
Need to add badges 

### ISSUE THREAD

**Issue by TracyRagan** [ortelius/ortelius#572]

**Comment by sachajw** [comment]
I have also found this
https://github.com/atrox/github-actions-badge
Badges for GitHub Actions can be created here.
![image](https://user-images.githubusercontent.com/32266273/224009836-afa01f09-271a-4d73-9234-205acb46dcd1.png)

**Comment by sachajw** [comment]
@sbtaylor15 awesome find for finding a fantastic solution to this issue! :-)

 ![GitHub release (latest SemVer)](https://img.shields.io/github/v/release/ortelius/ortelius-charts)

https://shields.io/

**Comment by sachajw** [comment]
@sbtaylor15 can we close this issue?

**Comment by sbtaylor15** [comment]
- [x] [ms-sbom-export](https://github.com/ortelius/ms-sbom-export)
- [x] [ms-validate-user](https://github.com/ortelius/ms-validate-user)
- [x] [ms-dep-pkg-r](https://github.com/ortelius/ms-dep-pkg-r)
- [x] [ms-dep-pkg-cud](https://github.com/ortelius/ms-dep-pkg-cud)
- [x] [ms-compitem-crud](https://github.com/ortelius/ms-compitem-crud)
- [x]  [ms-textfile-crud](https://github.com/ortelius/ms-textfile-crud)
- [x]  [ms-scorecard](https://github.com/ortelius/ms-scorecard)
- [x]  [ortelius](https://github.com/ortelius/ortelius)

**Comment by sbtaylor15** [comment]
Completed.  Had to remove mega-linter badge from the ortelius/ortelius repo since linting is skipped for that mono repo
