### ISSUE TITLE
Create microservice repositories

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#586]
**8 <img src="https://user-images.githubusercontent.com/14826572/194954041-610ed1b8-5104-4d3d-b215-df978d19d6f9.png" width="30px" height="30px"> Bounty**

Create new repositories that include the GH Workflows, Helm Charts and stub golang program

**Comment by Arvind644** [comment]
@sbtaylor15 I want to work on this issue. Can you give me some more details about it.

**Comment by sbtaylor15** [comment]
@Arvind644 Please copy the files from the [scec-domain](https://github.com/ortelius/scec-domain.git) repo over to the following ones:

* [scec-app-tag](https://github.com/ortelius/scec-app-tag.git)
* [scec-appver](https://github.com/ortelius/scec-appver.git)
* [scec-comp-tag](https://github.com/ortelius/scec-comp-tag.git)
* [scec-compver](https://github.com/ortelius/scec-compver.git)
* [scec-vulnerability](https://github.com/ortelius/scec-vulnerability.git)
* [scec-deployment](https://github.com/ortelius/scec-deployment.git)
* [scec-deppkg](https://github.com/ortelius/scec-deppkg.git)
* [scec-environment](https://github.com/ortelius/scec-environment.git)
* [scec-group](https://github.com/ortelius/scec-group.git)
* [scec-scorecard](https://github.com/ortelius/scec-scorecard.git)
* [scec-textfile](https://github.com/ortelius/scec-textfile.git)
* [scec-user](https://github.com/ortelius/scec-user.git)
* [scec-usergroup](https://github.com/ortelius/scec-usergroup.git)
* [scec-validate-provenance](https://github.com/ortelius/scec-validate-provenance.git)
* [scec-validate-signing](https://github.com/ortelius/scec-validate-signing.git)
* [scec-validate-user](https://github.com/ortelius/scec-validate-user.git)

> Note: Do NOT copy the .git directory since the new repos already have that directory.

**Comment by Arvind644** [comment]
@sbtaylor15  I will start working on it now. Does I have to change any file names also or just I have to copy it.

**Comment by sbtaylor15** [comment]
@Arvind644 Please rename the chart directory from `chart/scec-domain` to the new `chart/<newname>` and update the name in the `chart/<newname>/Chart.yaml`

The rest should be good to go.

**Comment by Arvind644** [comment]
@sbtaylor15 okay I will do all the updates and create a PR on main repo. And can you create this repository -  scec-validate-provenance . It is not present but you mentioned above.

**Comment by Arvind644** [comment]
@sbtaylor15 Also cannot fork because the repository is empty is showing to me on the above repo. Can you initialize those repo with a readme

**Comment by sbtaylor15** [comment]
@Arvind644 you will need to clone each repo locally, then copy the files from the scec-domain repo ignoring the .git directory, make the chart naming changes, git commit and git push.

**Comment by Arvind644** [comment]
@sbtaylor15 can you check at the fork section in this pic 
![image](https://user-images.githubusercontent.com/65646063/236278984-5d076a2c-0a60-49b0-88c6-cd174517c2b9.png)

**Comment by sbtaylor15** [comment]
@Arvind644 you should be able to work with the repos directly and skip the forking.  Let me know if you can clone and push directly back.

**Comment by Arvind644** [comment]
@sbtaylor15 I need permission to push directly to this branch. It is giving me that error. And also since the repo is still blank, it is taking default branch to master. Check the last two git command here
![image](https://user-images.githubusercontent.com/65646063/236283715-b52be15d-13ac-4011-ba99-5f3a1966c6c6.png)

**Comment by sbtaylor15** [comment]
@Arvind644 try it again. I updated your permissions

**Comment by Arvind644** [comment]
@sbtaylor15 it is still giving me same error
![image](https://user-images.githubusercontent.com/65646063/236297304-c8e64f1e-a114-4c65-9330-a0bcb1e881d8.png)

**Comment by sbtaylor15** [comment]
@Arvind644 Give it another try.

**Comment by Arvind644** [comment]
@sbtaylor15 I am still getting the same error. It seems like there is something wrong in my system or account

**Comment by Arvind644** [comment]
@sbtaylor15 I have copy files to all the repo now. What should I do next or we can close this issue

**Comment by sbtaylor15** [comment]
@Arvind644 how long did it take you to create all the repos?

**Comment by Arvind644** [comment]
@sbtaylor15 it took me around 2 hours to debug the error and creating all the repos
