### ISSUE TITLE
Creating Test folder in src/test for adding Tests in /ortelius/ortelius

### ISSUE THREAD

**Issue by anandbhagwat** [ortelius/ortelius#61]
Currently, there are no ways we can see and distinguish the Testing of each piece of modules. It will be good to add test folder that may contain API, UI, Integration Tests

**Comment by sbtaylor15** [comment]
@anandbhagwat there is also a command line interface in the https://github.com/ortelius/compupdate repo.  It uses most of the core API calls.  Maybe we can extend that into the test driver.  Or should we have smaller individual "unit" tests for the APIs?

**Comment by anandbhagwat** [comment]
@sbtaylor15 If I understood you correct, you mentioning about all API are present in this [repo](https://github.com/ortelius/compupdate/blob/master/deployhub/dhapi.py)? But seems these are code files but there seems no API tests added to it? I would like to know what each API mean and what kind of Test we can develop  and also I would like to  suggest to have an end-user journey cover by an API with the different Use case, Positive and Negative Scenario as well and we can run it every commits? I guess we should have develope tests based on Microservices level, like specific to each module etc. wdyt?

**Comment by sbtaylor15** [comment]
@anandbhagwat correct there are no specific api tests.  The [cli](https://github.com/ortelius/compupdate/blob/master/bin/dh) just uses the APIs.  We should create the individual APIs tests.
Here is the [list of the APIs](https://docs.deployhub.com/userguide/restapi/).  The doc is from the downstream but is identical to the [Ortelius Docs](https://github.com/ortelius/ortelius-docs).  (We in the process of standing up the Ortelius Doc server).

I think the test cases should be centered around the functional areas, ie. applications, components etc.

**Comment by anandbhagwat** [comment]
@sbtaylor15 Okay, so would you recommend to have src/test in this [location](https://github.com/ortelius/ortelius/tree/master/dmadminweb/src/dmadmin) or do you think we should add a test folder somewhere else. quite new to me, but The ideal way should be
Each Microservice have
1. API Functional Suites like **/src/test/APISuite**/applications, /src/test/APISuite/components, /src/test/APISuite/login, etc.

**Comment by sbtaylor15** [comment]
@anandbhagwat I think a **/test/APISuite** location at the root of the project would be best.  That way we can organize UI tests at that level down the road.  Also, each microservice will eventually have its own repo and moving the test cases over will be easier with the proposed structure.

**Comment by TracyRagan** [comment]
Sent email to the contributors looking for help in this area.
