### ISSUE TITLE
Killacoda | Standup Ortelius in a box on Killacoda

### ISSUE THREAD

**Issue by sachajw** [ortelius/ortelius#619]
As a DevOps Engineer I need to add this repo https://github.com/ortelius/dev-env-setup to Killacoda.

**Comment by agardnerIT** [comment]
Do you need any help with this?

**Comment by sbtaylor15** [comment]
This has been resolved.  See [instructions](https://artifacthub.io/packages/helm/ortelius/ortelius#installing-on-kubernetes-on-killercoda)
