### ISSUE TITLE
[Documentation] Improve Readme.md to explain what each component mean and how they function in Ortelius 

### ISSUE THREAD

**Issue by anandbhagwat** [ortelius/ortelius#62]
**The Readme.md file  lacks following information:**
We should have below details in README.md of Ortelius 
1. What is mean by Ortelius, a small Overview
2. Detail about how one can contribute
3. What are the components in Project
4. What each project folder contains
5. Contributor Names, point of contacts
6. Discord link

**Comment by sbtaylor15** [comment]
Install section is old.  Should be similar to https://docs.deployhub.com/userguide/installation-and-support/0-on-premise-installation-for-pro/.  Waiting on this until the docs are live on https://docs.ortelius.com

**Comment by sbtaylor15** [comment]
Also, discord link is missing

**Comment by sbtaylor15** [comment]
Discord Link - https://discord.gg/ZtXU74x

**Comment by TracyRagan** [comment]
completed and reviewed with Steve.
