### ISSUE TITLE
Ortelius v11 | Terraform scec-charts

### ISSUE THREAD

**Issue by sachajw** [ortelius/ortelius#620]
the main helm charts for Ortelius V11  are now up and running.  Can you do your terraform magic to run these in kind?  https://github.com/ortelius/scec-charts/blob/gh-pages/index.yaml

**Comment by sachajw** [comment]
helm_release.ortelius: Creating...
╷
│ Error: could not download chart: looks like "https://github.com/ortelius/scec-charts/" is not a valid chart repository or cannot be reached: failed to fetch https://github.com/ortelius/scec-charts/index.yaml : 404 Not Found
│

Sacha Wharton — Today at 21:58
tried this too
[21:58]
Plan: 1 to add, 0 to change, 0 to destroy.
helm_release.ortelius: Creating...
╷
│ Error: could not download chart: looks like "https://ortelius.github.io/ortelius-charts/ortelius-scc" is not a valid chart repository or cannot be reached: failed to fetch https://ortelius.github.io/ortelius-charts/ortelius-scc/index.yaml : 404 Not Found
│
│   with helm_release.ortelius,
│   on main.tf line 48, in resource "helm_release" "ortelius":
│   48: resource "helm_release" "ortelius" {

**Comment by sbtaylor15** [comment]
We can no longer use terraform due to Hashicorp licensing
