### ISSUE TITLE
Create Repository for Reusable Workflows 

### ISSUE THREAD

**Issue by codeWithUtkarsh** [ortelius/ortelius#624]
As a developer, I should be able to extract the workflows from the repositories  and create a repository with all the reusable workflows to avoid any duplicate code.

**Comment by codeWithUtkarsh** [comment]
Rolling out these changes to the required repositories as done for https://github.com/ortelius/ms-validate-user/blob/main/.github/workflows/build-push-chart.yml.

Out of total 56 repos. The changes will be added for the below-mentioned repositories:-

"https://api.github.com/repos/ortelius/ms-compitem-crud",
  "https://api.github.com/repos/ortelius/ms-cr-action",
  "https://api.github.com/repos/ortelius/ms-dep-pkg-cud",
  "https://api.github.com/repos/ortelius/ms-dep-pkg-r",
  "https://api.github.com/repos/ortelius/ms-postgres",
  "https://api.github.com/repos/ortelius/ms-release-action",
  "https://api.github.com/repos/ortelius/ms-sbom-action",
  "https://api.github.com/repos/ortelius/ms-scorecard",
  "https://api.github.com/repos/ortelius/ms-setenv-action",
  "https://api.github.com/repos/ortelius/ms-textfile-crud",
  "https://api.github.com/repos/ortelius/ms-trivy-action",
  "https://api.github.com/repos/ortelius/ms-validate-user",
"https://api.github.com/repos/ortelius/scec-app-tag",
  "https://api.github.com/repos/ortelius/scec-appver",
  "https://api.github.com/repos/ortelius/scec-charts",
  "https://api.github.com/repos/ortelius/scec-commons",
  "https://api.github.com/repos/ortelius/scec-comp-tag",
  "https://api.github.com/repos/ortelius/scec-compver",
  "https://api.github.com/repos/ortelius/scec-datasource-abs",
  "https://api.github.com/repos/ortelius/scec-deployment",
  "https://api.github.com/repos/ortelius/scec-deppkg",
  "https://api.github.com/repos/ortelius/scec-domain",
  "https://api.github.com/repos/ortelius/scec-environment",
  "https://api.github.com/repos/ortelius/scec-group",
  "https://api.github.com/repos/ortelius/scec-scorecard",
  "https://api.github.com/repos/ortelius/scec-textfile",
  "https://api.github.com/repos/ortelius/scec-user",
  "https://api.github.com/repos/ortelius/scec-usergroup",
  "https://api.github.com/repos/ortelius/scec-validate-provenance",
  "https://api.github.com/repos/ortelius/scec-validate-signing",
  "https://api.github.com/repos/ortelius/scec-validate-user",
  "https://api.github.com/repos/ortelius/scec-vulnerability",

@sbtaylor15  I have included all the repos starting with `ms-` and `scec`. Please mention if there are any other repos that needs to be included.

**Comment by codeWithUtkarsh** [comment]
1. Workflow for these repos are not updated because they had different implementation.
https://github.com/ortelius/ms-postgres/blob/main/.github/workflows/build-push-chart.yml

2. The repos that didn't has workflow.
https://github.com/ortelius/scec-datasource-abs
https://github.com/ortelius/scec-charts
https://github.com/ortelius/scec-commons

3. The docker build is failing for this repo because the bass image being used does not have python installed in it. need to check with @sbtaylor15 before making any change in base image.

![image](https://github.com/ortelius/ortelius/assets/29374436/223a8191-5cfd-4973-b98f-450b73fc9050)

**Comment by sbtaylor15** [comment]
@codeWithUtkarsh those three repos are reusable code libraries and don't create a docker image.  We will need to add workflows but they will be different than the microservice ones and not reusable workflows
