### ISSUE TITLE
Golang app for containerisation practice

### ISSUE THREAD

**Issue by Arvind644** [ortelius/ortelius#628]

**Comment by sbtaylor15** [comment]
@Arvind644 Can you please add details about this issue?

**Comment by Arvind644** [comment]
@sbtaylor15 I will add how to run a golang application locally and using docker. And I will write its docs and add it here https://docs.ortelius.io/guides/contributorguide/application-build-and-containerisation/

**Comment by sbtaylor15** [comment]
@Arvind644 take a look at ortelius/backlog#21.  There is a predefined GH action that we can use to build the golang app.

**Comment by Arvind644** [comment]
@sbtaylor15 Thanks a lot for mentioning it. I will use that GH action now
