### ISSUE TITLE
ACTION REQUIRED: Changes to pulling Chainguard Images

### ISSUE THREAD

**Issue by chainguard-alerter** [ortelius/ortelius#629]
Hey there [Chainguard](https://github.com/chainguard-dev) here.

We noticed that you are using [Chainguard Images](https://github.com/chainguard-images/images), thank you! We wanted to make you aware of an upcoming change that will impact your project.

Starting August 16, 2023 public users will no longer be able to pull images from our registry (cgr.dev/chainguard) by tags other than `latest` or `latest-dev`. Please see [the announcement](https://www.chainguard.dev/unchained/scaling-chainguard-images-with-a-growing-catalog-and-proactive-security-updates) for more information.

You are currently using the following.

In https://github.com/ortelius/ortelius/blob/57f50244555b5ab9c39b9e683d0cf30edbe35998/docker/DockerfileUI:

- cgr.dev/chainguard/jdk:openjdk-17

Our goal is to prevent your project from experiencing any disruptions. Please see [the migration guide](https://www.chainguard.dev/unchained/a-guide-on-how-to-use-chainguard-images-for-public-catalog-tier-users) for options.

If there's more we can do to help please reply to this issue or email us at [support@chainguard.dev](mailto:support@chainguard.dev).

Thank you!

**Comment by sbtaylor15** [comment]
This is not an issue since we use the sha in dockerfiles

**Comment by eddiezane** [comment]
Looks like this one is pulling by a tag that has been removed (`openjdk-17`).

https://github.com/ortelius/ortelius/blob/3475607da72e90e8c43869ce4a66f333e853dde0/docker/DockerfileUI#L8
