### ISSUE TITLE
[Issue] server did not start in time, And Also getting chmod: cannot access '/root/.ssh/known*': No such file or directory

### ISSUE THREAD

**Issue by anandbhagwat** [ortelius/ortelius#63]
**Steps to reproduce**: From Readme.md
1. docker pull quay.io/ortelius/ortelius
2. mkdir -p ~/ortelius/data
3. chmod 777 ~/ortelius/data
4. This step is wrong _docker run -v ~/ortelius/data:/var/lib/pgsql/data:Z -p 7171:8080 -d --hostname docker_dh -v ~/.ssh:/keys:Z ${IMAGE}_
5. So Instead of 4th Step Use: docker run -p 7173:8080 -v ~/ortelius/data:/var/lib/pgsql/data  -v ~/.ssh:/keys quay.io/ortelius/ortelius
6. Navigate to http://localhost:7173/

**Expected**: GUI should get open

**Actual Result:** 
Nothing is accesible and Logs says below information:
**Logs**
`docker run -p 7173:8080 -v ~/ortelius/data:/var/lib/pgsql/data  -v ~/.ssh:/keys quay.io/ortelius/ortelius
+ sudo chown -R postgres:postgres /var/lib/pgsql
+ chmod -R 777 /opt/deployhub
+ pkill postgres
/tmp/entrypoint.sh: line 6: pkill: command not found
+ sudo test -f /var/lib/pgsql/data/pg_hba.conf
+ echo 'Database already initialized'
+ sudo -u postgres pg_ctl start --pgdata=/var/lib/pgsql/data
Database already initialized
pg_ctl: another server might be running; trying to start server anyway
waiting for server to start....2020-08-10 17:14:58.658 UTC [15] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2020-08-10 17:14:58.658 UTC [15] LOG:  could not bind IPv6 address "::1": Cannot assign requested address
2020-08-10 17:14:58.658 UTC [15] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
2020-08-10 17:14:58.660 UTC [15] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2020-08-10 17:14:58.662 UTC [15] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-08-10 17:14:58.717 UTC [15] LOG:  redirecting log output to logging collector process
2020-08-10 17:14:58.717 UTC [15] HINT:  Future log output will appear in directory "log".
...........................................................pg_ctl: server did not start in time
 stopped waiting
+ sleep 10
+ sudo -u postgres pg_ctl status --pgdata=/var/lib/pgsql/data
pg_ctl: no server running
+ '[' '!' -e /opt/deployhub/logs ']'
+ mkdir /opt/deployhub/logs
+ cd /opt/deployhub/engine
+ export LD_LIBRARY_PATH=/opt/deployhub/engine/lib:/opt/deployhub/engine/bin
+ LD_LIBRARY_PATH=/opt/deployhub/engine/lib:/opt/deployhub/engine/bin
+ export PATH=/opt/deployhub/engine/lib:/opt/deployhub/engine/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ PATH=/opt/deployhub/engine/lib:/opt/deployhub/engine/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ cut -d: -f6
+++ whoami
++ getent passwd omreleng
+ export HOME=/home/omreleng
+ HOME=/home/omreleng
+ sudo cp -r /keys/id_rsa /keys/id_rsa.pub /keys/known_hosts /root/.ssh
+ sudo chown -R root /root/.ssh
+ sudo chmod 755 /root/.ssh
+ sudo chmod 600 '/root/.ssh/known*'
chmod: cannot access '/root/.ssh/known*': No such file or directory
+ cp -r /keys/id_rsa /keys/id_rsa.pub /keys/known_hosts /home/omreleng/.ssh
+ chown -R omreleng /home/omreleng/.ssh
+ chmod 755 /home/omreleng/.ssh
+ chmod 600 /home/omreleng/.ssh/known_hosts
Running DeployHub Processes
+ echo Running DeployHub Processes
+ java -jar /opt/deployhub/webadmin/webapp-runner.jar --path /dmadminweb /opt/deployhub/webadmin/deployhub-webadmin.war`

**Comment by anandbhagwat** [comment]
@sbtaylor15 Here is the screen shot and command I used below:
`docker run -p 7173:8080 -v ~/ortelius/data:/var/lib/pgsql/data -v ~/.ssh:/keys quay.io/ortelius/ortelius
`
<img width="1299" alt="Screenshot 2020-08-10 at 11 40 23 PM" src="https://user-images.githubusercontent.com/22328983/89815765-f14f3780-db62-11ea-9e2e-cab81ebf2fe3.png">

**Comment by anandbhagwat** [comment]
Also @sbtaylor15  GUI isn't open when  I navigate: http://localhost:7174/

Seems something related to exact steps I am using:

1. docker pull quay.io/ortelius/ortelius
2. mkdir -p ~/ortelius/data
3. chmod 777 ~/ortelius/data
4. This step is wrong docker run -v ~/ortelius/data:/var/lib/pgsql/data:Z -p 7171:8080 -d --hostname docker_dh -v ~/.ssh:/keys:Z ${IMAGE}
5. So Instead of 4th Step Use: docker run -p 7174:8080 -v ~/ortelius/data:/var/lib/pgsql/data -v ~/.ssh:/keys quay.io/ortelius/ortelius
6. Navigate to http://localhost:7174/

**Comment by anandbhagwat** [comment]
Solution to Above is:
1. Use Image ID instead of Image Name:

_docker run -v ~/ortelius/data:/var/lib/pgsql/data:Z -p 7171:8080 -d --hostname docker_dh -v ~/.ssh:/keys:Z <**IMAGE_ID**>

**Comment by sbtaylor15** [comment]
Url to UI is:  http://localhost:7171/dmadminweb/Home
