### ISSUE TITLE
Add dockerfile to build Svelte frontend image

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#656]
[ortelius/scec-frontend](https://github.com/ortelius/scec-frontend) needs a Dockerfile to build the Svelte frontend so it can run in k8s.

**Comment by devsargam** [comment]
@sbtaylor15 I am interested in picking this. Can you assign this issue to me???

**Comment by sbtaylor15** [comment]
@devsargam let me know if you need any help on this.

**Comment by sbtaylor15** [comment]
Dockerfile has been completed
