### ISSUE TITLE
helm chart needed for Svelte frontend

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#657]
[ortelius/scec-frontend](https://github.com/ortelius/scec-frontend) needs charts to deploy to k8s. These charts should contain the deployment, service and ingress defintions.  Dependent upon issue #656

**Comment by btwshivam** [comment]
hey, I want to work on it. assign me!

**Comment by sbtaylor15** [comment]
@shivam200446 all yours.  Let me know if you need any help on this.

**Comment by btwshivam** [comment]
@sbtaylor15 can you please elaborate on the issue more?

**Comment by sbtaylor15** [comment]
@shivam200446 Model the helm charts after the ones in [ortelius/scec-compver](https://github.com/ortelius/scec-compver), but the secret.yml and the ARANGO_* environment variables are not needed. 

Also, the port for the container will be on 4173.  So please have port 80 map to 4173 for the service.

**Comment by sbtaylor15** [comment]
Helm charts have been completed for the frontend
