### ISSUE TITLE
Broken link on the ortelius.io website & recommendation

### ISSUE THREAD

**Issue by roynielsen17** [ortelius/ortelius#71]
Hello,

This page ( https://ortelius.io/guidelines/community-information-guidelines ) returns a 404 error when I try to access it.

I clicked on the 'report a bug' link ( https://ortelius.io/guidelines/community-information-guidelines#i-d-like-to-report-a-bug  ), and got the 404 - so I'm not sure this bug fits your reporting format.

One of the 'nice to have' tools I've had on my todo list for tons of web related projects was to either find or create, is a crawler that will access a list of project web pages, and recursively crawl all the links on each of the target pages to make sure there aren't any broken links.  

Maybe a test could be developed for the ortelius.ip website to check this kind of functionality in a CI/CD type process before code is released to production?

Respectfully,
-Roy Nielsen

**Comment by sbtaylor15** [comment]
Hi Roy,

Screaming Frog and Google Webmaster Tools are what we use to check the site.  Right now, the process is manual.  Not sure if Screaming Frog has a batch mode or not. 

Also, the website uses wordpress so changes are made directly to the site vs a hugo website that can be driven by git.

The bad links have been fixed.

Thanks, Steve
