### ISSUE TITLE
Report of Application Versions -> Environments

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#80]
Create a table report showing Applications Versions to Environments

**Comment by sbtaylor15** [comment]
Repo is located [here](https://github.com/ortelius/ortelius-ms-rpt-app2env)

**Comment by sachajw** [comment]
I am working on the following:
Deploying APIs with Python and Docker
I have a basic container running in Google Cloud.
I used the Google SDK to login and push my container to the Google Cloud registry.
I used Google Cloud Build to publish the container on the internet.
The container allows you to list, delete and add places.
You can use Postman to test the api to list, delete and add places.
I am working on getting the port exposure working with Waitress.

**Comment by sachajw** [comment]
This is complete I just need to create a PR!

**Comment by sbtaylor15** [comment]
Ok, do a PR so we can get this shared with everyone.  Then we will do the next part of adding in the DB calls.  Lets go with pyodbc for the database driver.

**Comment by TracyRagan** [comment]
Will be addressed in Rocinante milestone.
