### ISSUE TITLE
Report of Environments -> Component Versions

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#82]
Create a table report showing Environments to Component Versions

**Comment by manthasri** [comment]
I can do this. But where do you want me to create this?

**Comment by sbtaylor15** [comment]
Looks like these reports are good candidates to be microservices.  Keep an eye out for the Architecture Working Group meeting so we can discuss.

**Comment by sbtaylor15** [comment]
Repo is located [here](https://github.com/ortelius/ortelius-ms-rpt-env2comp)

**Comment by TracyRagan** [comment]
Will be addressed in Rocinante milestone.
