### ISSUE TITLE
Add postgres instance to Azure for testing

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#89]
Create postgres db in azure and add data for testing.

**Comment by jgarverick** [comment]
I can take this one...is there a specific Azure subscription that we need to be using for this?

**Comment by sbtaylor15** [comment]
@jgarverick - I will send you the Azure details for this via email

**Comment by jgarverick** [comment]
Details received and PG instance has been created.  All applicable secrets have been added to the Key Vault in the resource group.
