### ISSUE TITLE
Blog on how Ortelius integrates with OSV.dev

### ISSUE THREAD

**Issue by TracyRagan** [ortelius/ortelius#964]
We need a blog that covers how and why Ortelius integrates with osv.dev to find vulnerabilities, real-time, based on the consumed SBOM for every component  and consuming application version.

**Comment by TracyRagan** [comment]
For help on the blog, check-out 
https://docs.ortelius.io/guides/userguide/integrations/spdx-syft-cyclonedx/
https://docs.ortelius.io/guides/userguide/2-define-components/
https://docs.ortelius.io/guides/userguide/addingtopipeline/

**Comment by JesseK123** [comment]
[Ortelius IntegrationWithOSV.dev_blog.md](https://github.com/user-attachments/files/17548602/Ortelius.IntegrationWithOSV.dev_blog.md)
![Vulnerabilities](https://github.com/user-attachments/assets/32680904-9e63-4323-8112-d9a3a3481ef3)
