### ISSUE TITLE
Blog on how Ortelius integrates and consumes SPDX and Cylcone DX SBOMS

### ISSUE THREAD

**Issue by TracyRagan** [ortelius/ortelius#965]
We need a blog that covers how and why Ortelius integrates with SPDX and Cyclone DX SBOMs  for every Component, and then aggregates the data up to the logical application with real-time vulnerability scans for both. 

For help on the blog, check-out 
https://docs.ortelius.io/guides/userguide/integrations/spdx-syft-cyclonedx/
https://docs.ortelius.io/guides/userguide/2-define-components/
https://docs.ortelius.io/guides/userguide/addingtopipeline/

**Comment by JesseK123** [comment]
[OrteliusIntegrationWithSPDXblog.md](https://github.com/user-attachments/files/17548536/OrteliusIntegrationWithSPDXblog.md)
![SPDXJSON Sample](https://github.com/user-attachments/assets/9de2
![CycloneDX JSON example](https://github.com/user-attachments/assets/c54e4916-41c7-43d3-a7ca-cd556527f831)
d13f-3afc-4468-8649-5b0f7aee
![sample sbom gets updated during the build](https://github.com/user-attachments/assets/d00fa9a3-bf62-4cc5-897e-c793bd8f3906)
1749)

**Comment by JesseK123** [comment]
[OrteliusIntegrationWithSPDXblog.md](https://github.com/user-attachments/files/17548576/OrteliusIntegrationWithSPDXblog.md)
![sample sbom gets updated during the build](https://github.com/user-attachments/assets/e2188ab4-a96a-421e-aa93-2554c5e06dfd)
![SPDXJSON Sample](https://github.com/user-attachments/assets/3f9c07fd-54b2-4519-8f10-6d8ebaaaf1a7)
![CycloneDX JSON example](https://github.com/user-attachments/assets/6704c280-bdd5-4a71-88df-ce3e52a99a23)
